/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-zWLHjG/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module PCIE_Synth(clk, reset_L, init, data_in_principal, push, pop, data_out0, data_out1, active_out, idle_out, error_out, Pausa_MF);
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire _0560_;
  wire _0561_;
  wire _0562_;
  wire _0563_;
  wire _0564_;
  wire _0565_;
  wire _0566_;
  wire _0567_;
  wire _0568_;
  wire _0569_;
  wire _0570_;
  wire _0571_;
  wire _0572_;
  wire _0573_;
  wire _0574_;
  wire _0575_;
  wire _0576_;
  wire _0577_;
  wire _0578_;
  wire _0579_;
  wire _0580_;
  wire _0581_;
  wire _0582_;
  wire _0583_;
  wire _0584_;
  wire _0585_;
  wire _0586_;
  wire _0587_;
  wire _0588_;
  wire _0589_;
  wire _0590_;
  wire _0591_;
  wire _0592_;
  wire _0593_;
  wire _0594_;
  wire _0595_;
  wire _0596_;
  wire _0597_;
  wire _0598_;
  wire _0599_;
  wire _0600_;
  wire _0601_;
  wire _0602_;
  wire _0603_;
  wire _0604_;
  wire _0605_;
  wire _0606_;
  wire _0607_;
  wire _0608_;
  wire _0609_;
  wire _0610_;
  wire _0611_;
  wire _0612_;
  wire _0613_;
  wire _0614_;
  wire _0615_;
  wire _0616_;
  wire _0617_;
  wire _0618_;
  wire _0619_;
  wire [5:0] \D0Fifo.Fifo_Data_in ;
  wire [5:0] \D0Fifo.Fifo_Data_in_int ;
  wire [5:0] \D0Fifo.memoria.Ram[0] ;
  wire [5:0] \D0Fifo.memoria.Ram[1] ;
  wire [5:0] \D0Fifo.memoria.Ram[2] ;
  wire [5:0] \D0Fifo.memoria.Ram[3] ;
  wire [1:0] \D0Fifo.memoria.iReadAddress ;
  wire \D0Fifo.memoria.iReadEnable ;
  wire [1:0] \D0Fifo.memoria.iWriteAddress ;
  wire \D0Fifo.memoria.iWriteEnable ;
  wire \D0Fifo.push ;
  wire [1:0] \D1Fifo.memoria.iReadAddress ;
  wire [5:0] \Demux_D0_D1.data_in ;
  wire \Demux_D0_D1.valid_in ;
  wire FIFO_empty;
  wire FIFO_error;
  wire Fifo_Empty_VC0;
  wire Fifo_Empty_VC1;
  wire [5:0] \MainFifo.Fifo_Data_in_int ;
  wire [5:0] \MainFifo.memoria.Ram[0] ;
  wire [5:0] \MainFifo.memoria.Ram[1] ;
  wire [5:0] \MainFifo.memoria.Ram[2] ;
  wire [5:0] \MainFifo.memoria.Ram[3] ;
  wire [1:0] \MainFifo.memoria.iReadAddress ;
  wire \MainFifo.memoria.iReadEnable ;
  wire [1:0] \MainFifo.memoria.iWriteAddress ;
  wire \MainFifo.memoria.iWriteEnable ;
  output Pausa_MF;
  wire [5:0] \VC0Fifo.Fifo_Data_in ;
  wire [5:0] \VC0Fifo.Fifo_Data_in_int ;
  wire [5:0] \VC0Fifo.memoria.Ram[0] ;
  wire [5:0] \VC0Fifo.memoria.Ram[1] ;
  wire [5:0] \VC0Fifo.memoria.Ram[2] ;
  wire [5:0] \VC0Fifo.memoria.Ram[3] ;
  wire [1:0] \VC0Fifo.memoria.iReadAddress ;
  wire \VC0Fifo.memoria.iReadEnable ;
  wire [1:0] \VC0Fifo.memoria.iWriteAddress ;
  wire \VC0Fifo.memoria.iWriteEnable ;
  wire [2:0] \VC0Fifo.num_mem ;
  wire \VC0Fifo.pop ;
  wire \VC0Fifo.push ;
  wire [5:0] \VC1Fifo.Fifo_Data_in ;
  wire [5:0] \VC1Fifo.Fifo_Data_in_int ;
  wire [5:0] \VC1Fifo.memoria.Ram[0] ;
  wire [5:0] \VC1Fifo.memoria.Ram[1] ;
  wire [5:0] \VC1Fifo.memoria.Ram[2] ;
  wire [5:0] \VC1Fifo.memoria.Ram[3] ;
  wire [1:0] \VC1Fifo.memoria.iReadAddress ;
  wire \VC1Fifo.memoria.iReadEnable ;
  wire [1:0] \VC1Fifo.memoria.iWriteAddress ;
  wire \VC1Fifo.memoria.iWriteEnable ;
  wire [2:0] \VC1Fifo.num_mem ;
  wire \VC1Fifo.pop ;
  wire \VC1Fifo.push ;
  output active_out;
  input clk;
  input [5:0] data_in_principal;
  output [5:0] data_out0;
  output [5:0] data_out1;
  output error_out;
  wire [4:0] \fsm_Control1.nxt_state ;
  wire [4:0] \fsm_Control1.state ;
  output idle_out;
  input init;
  input pop;
  input push;
  input reset_L;
  NOT _0620_ (
    .A(reset_L),
    .Y(_0031_)
  );
  NOR _0621_ (
    .A(Fifo_Empty_VC1),
    .B(Fifo_Empty_VC0),
    .Y(_0032_)
  );
  NOT _0622_ (
    .A(_0032_),
    .Y(_0033_)
  );
  NOR _0623_ (
    .A(_0033_),
    .B(FIFO_empty),
    .Y(_0034_)
  );
  NOR _0624_ (
    .A(_0034_),
    .B(_0031_),
    .Y(_0000_)
  );
  NAND _0625_ (
    .A(FIFO_error),
    .B(reset_L),
    .Y(_0035_)
  );
  NOR _0626_ (
    .A(_0035_),
    .B(_0032_),
    .Y(_0001_)
  );
  NOR _0627_ (
    .A(_0031_),
    .B(Fifo_Empty_VC0),
    .Y(_0002_)
  );
  NAND _0628_ (
    .A(reset_L),
    .B(Fifo_Empty_VC1),
    .Y(_0036_)
  );
  NOT _0629_ (
    .A(\VC1Fifo.pop ),
    .Y(_0037_)
  );
  NAND _0630_ (
    .A(_0037_),
    .B(_0031_),
    .Y(_0038_)
  );
  NAND _0631_ (
    .A(_0038_),
    .B(_0036_),
    .Y(_0039_)
  );
  NOR _0632_ (
    .A(_0039_),
    .B(_0002_),
    .Y(_0003_)
  );
  NOT _0633_ (
    .A(\D0Fifo.push ),
    .Y(_0042_)
  );
  NOT _0634_ (
    .A(\D0Fifo.memoria.iWriteAddress [0]),
    .Y(_0043_)
  );
  NOR _0635_ (
    .A(_0043_),
    .B(_0042_),
    .Y(_0044_)
  );
  NAND _0636_ (
    .A(_0043_),
    .B(_0042_),
    .Y(_0045_)
  );
  NAND _0637_ (
    .A(_0045_),
    .B(reset_L),
    .Y(_0046_)
  );
  NOR _0638_ (
    .A(_0046_),
    .B(_0044_),
    .Y(_0174_)
  );
  NOT _0639_ (
    .A(\D0Fifo.memoria.iWriteAddress [1]),
    .Y(_0047_)
  );
  NOT _0640_ (
    .A(_0044_),
    .Y(_0048_)
  );
  NOR _0641_ (
    .A(_0048_),
    .B(_0047_),
    .Y(_0049_)
  );
  NAND _0642_ (
    .A(_0048_),
    .B(_0047_),
    .Y(_0050_)
  );
  NAND _0643_ (
    .A(_0050_),
    .B(reset_L),
    .Y(_0051_)
  );
  NOR _0644_ (
    .A(_0051_),
    .B(_0049_),
    .Y(_0191_)
  );
  NOT _0645_ (
    .A(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0054_)
  );
  NOR _0646_ (
    .A(_0054_),
    .B(_0031_),
    .Y(_0209_)
  );
  NOT _0647_ (
    .A(\D0Fifo.memoria.iReadAddress [1]),
    .Y(_0056_)
  );
  NOR _0648_ (
    .A(_0056_),
    .B(_0031_),
    .Y(_0226_)
  );
  NOT _0649_ (
    .A(\D0Fifo.Fifo_Data_in [0]),
    .Y(_0058_)
  );
  NOR _0650_ (
    .A(_0058_),
    .B(_0031_),
    .Y(_0328_)
  );
  NAND _0651_ (
    .A(\D0Fifo.Fifo_Data_in [1]),
    .B(reset_L),
    .Y(_0061_)
  );
  NOT _0652_ (
    .A(_0061_),
    .Y(_0346_)
  );
  NAND _0653_ (
    .A(\D0Fifo.Fifo_Data_in [2]),
    .B(reset_L),
    .Y(_0062_)
  );
  NOT _0654_ (
    .A(_0062_),
    .Y(_0362_)
  );
  NAND _0655_ (
    .A(\D0Fifo.Fifo_Data_in [3]),
    .B(reset_L),
    .Y(_0064_)
  );
  NOT _0656_ (
    .A(_0064_),
    .Y(_0379_)
  );
  NAND _0657_ (
    .A(\D0Fifo.Fifo_Data_in [4]),
    .B(reset_L),
    .Y(_0065_)
  );
  NOT _0658_ (
    .A(_0065_),
    .Y(_0403_)
  );
  NAND _0659_ (
    .A(\D0Fifo.Fifo_Data_in [5]),
    .B(reset_L),
    .Y(_0067_)
  );
  NOT _0660_ (
    .A(_0067_),
    .Y(_0429_)
  );
  NOR _0661_ (
    .A(_0042_),
    .B(_0031_),
    .Y(_0439_)
  );
  NOT _0662_ (
    .A(\D0Fifo.memoria.iWriteEnable ),
    .Y(_0068_)
  );
  NOR _0663_ (
    .A(_0068_),
    .B(\D0Fifo.memoria.iWriteAddress [0]),
    .Y(_0069_)
  );
  NAND _0664_ (
    .A(_0069_),
    .B(_0047_),
    .Y(_0070_)
  );
  NOT _0665_ (
    .A(_0070_),
    .Y(_0071_)
  );
  NAND _0666_ (
    .A(_0071_),
    .B(\D0Fifo.Fifo_Data_in_int [0]),
    .Y(_0072_)
  );
  NAND _0667_ (
    .A(_0070_),
    .B(\D0Fifo.memoria.Ram[0] [0]),
    .Y(_0073_)
  );
  NAND _0668_ (
    .A(_0073_),
    .B(_0072_),
    .Y(_0473_)
  );
  NAND _0669_ (
    .A(_0071_),
    .B(\D0Fifo.Fifo_Data_in_int [1]),
    .Y(_0074_)
  );
  NAND _0670_ (
    .A(_0070_),
    .B(\D0Fifo.memoria.Ram[0] [1]),
    .Y(_0075_)
  );
  NAND _0671_ (
    .A(_0075_),
    .B(_0074_),
    .Y(_0501_)
  );
  NAND _0672_ (
    .A(_0071_),
    .B(\D0Fifo.Fifo_Data_in_int [2]),
    .Y(_0076_)
  );
  NAND _0673_ (
    .A(_0070_),
    .B(\D0Fifo.memoria.Ram[0] [2]),
    .Y(_0077_)
  );
  NAND _0674_ (
    .A(_0077_),
    .B(_0076_),
    .Y(_0526_)
  );
  NAND _0675_ (
    .A(_0071_),
    .B(\D0Fifo.Fifo_Data_in_int [3]),
    .Y(_0078_)
  );
  NAND _0676_ (
    .A(_0070_),
    .B(\D0Fifo.memoria.Ram[0] [3]),
    .Y(_0079_)
  );
  NAND _0677_ (
    .A(_0079_),
    .B(_0078_),
    .Y(_0555_)
  );
  NAND _0678_ (
    .A(_0071_),
    .B(\D0Fifo.Fifo_Data_in_int [4]),
    .Y(_0080_)
  );
  NAND _0679_ (
    .A(_0070_),
    .B(\D0Fifo.memoria.Ram[0] [4]),
    .Y(_0081_)
  );
  NAND _0680_ (
    .A(_0081_),
    .B(_0080_),
    .Y(_0582_)
  );
  NAND _0681_ (
    .A(_0071_),
    .B(\D0Fifo.Fifo_Data_in_int [5]),
    .Y(_0084_)
  );
  NAND _0682_ (
    .A(_0070_),
    .B(\D0Fifo.memoria.Ram[0] [5]),
    .Y(_0085_)
  );
  NAND _0683_ (
    .A(_0085_),
    .B(_0084_),
    .Y(_0610_)
  );
  NOT _0684_ (
    .A(\D0Fifo.memoria.iReadEnable ),
    .Y(_0088_)
  );
  NOR _0685_ (
    .A(\D0Fifo.memoria.Ram[2] [0]),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0089_)
  );
  NOT _0686_ (
    .A(\D0Fifo.memoria.Ram[3] [0]),
    .Y(_0091_)
  );
  NAND _0687_ (
    .A(_0091_),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0093_)
  );
  NAND _0688_ (
    .A(_0093_),
    .B(\D0Fifo.memoria.iReadAddress [1]),
    .Y(_0094_)
  );
  NOR _0689_ (
    .A(_0094_),
    .B(_0089_),
    .Y(_0095_)
  );
  NOT _0690_ (
    .A(\D0Fifo.memoria.Ram[1] [0]),
    .Y(_0096_)
  );
  NOR _0691_ (
    .A(_0096_),
    .B(_0054_),
    .Y(_0097_)
  );
  NOT _0692_ (
    .A(\D0Fifo.memoria.Ram[0] [0]),
    .Y(_0098_)
  );
  NOR _0693_ (
    .A(_0098_),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0099_)
  );
  NOR _0694_ (
    .A(_0099_),
    .B(_0097_),
    .Y(_0100_)
  );
  NOR _0695_ (
    .A(_0100_),
    .B(\D0Fifo.memoria.iReadAddress [1]),
    .Y(_0101_)
  );
  NOR _0696_ (
    .A(_0101_),
    .B(_0095_),
    .Y(_0102_)
  );
  NOR _0697_ (
    .A(_0102_),
    .B(_0088_),
    .Y(data_out0[0])
  );
  NOR _0698_ (
    .A(\D0Fifo.memoria.Ram[2] [1]),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0103_)
  );
  NOT _0699_ (
    .A(\D0Fifo.memoria.Ram[3] [1]),
    .Y(_0104_)
  );
  NAND _0700_ (
    .A(_0104_),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0105_)
  );
  NAND _0701_ (
    .A(_0105_),
    .B(\D0Fifo.memoria.iReadAddress [1]),
    .Y(_0106_)
  );
  NOR _0702_ (
    .A(_0106_),
    .B(_0103_),
    .Y(_0107_)
  );
  NOT _0703_ (
    .A(\D0Fifo.memoria.Ram[1] [1]),
    .Y(_0108_)
  );
  NOR _0704_ (
    .A(_0108_),
    .B(_0054_),
    .Y(_0109_)
  );
  NOT _0705_ (
    .A(\D0Fifo.memoria.Ram[0] [1]),
    .Y(_0110_)
  );
  NOR _0706_ (
    .A(_0110_),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0111_)
  );
  NOR _0707_ (
    .A(_0111_),
    .B(_0109_),
    .Y(_0112_)
  );
  NOR _0708_ (
    .A(_0112_),
    .B(\D0Fifo.memoria.iReadAddress [1]),
    .Y(_0113_)
  );
  NOR _0709_ (
    .A(_0113_),
    .B(_0107_),
    .Y(_0114_)
  );
  NOR _0710_ (
    .A(_0114_),
    .B(_0088_),
    .Y(data_out0[1])
  );
  NOR _0711_ (
    .A(\D0Fifo.memoria.Ram[2] [2]),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0115_)
  );
  NOT _0712_ (
    .A(\D0Fifo.memoria.Ram[3] [2]),
    .Y(_0116_)
  );
  NAND _0713_ (
    .A(_0116_),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0117_)
  );
  NAND _0714_ (
    .A(_0117_),
    .B(\D0Fifo.memoria.iReadAddress [1]),
    .Y(_0118_)
  );
  NOR _0715_ (
    .A(_0118_),
    .B(_0115_),
    .Y(_0119_)
  );
  NOT _0716_ (
    .A(\D0Fifo.memoria.Ram[1] [2]),
    .Y(_0120_)
  );
  NOR _0717_ (
    .A(_0120_),
    .B(_0054_),
    .Y(_0121_)
  );
  NOT _0718_ (
    .A(\D0Fifo.memoria.Ram[0] [2]),
    .Y(_0122_)
  );
  NOR _0719_ (
    .A(_0122_),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0123_)
  );
  NOR _0720_ (
    .A(_0123_),
    .B(_0121_),
    .Y(_0124_)
  );
  NOR _0721_ (
    .A(_0124_),
    .B(\D0Fifo.memoria.iReadAddress [1]),
    .Y(_0125_)
  );
  NOR _0722_ (
    .A(_0125_),
    .B(_0119_),
    .Y(_0127_)
  );
  NOR _0723_ (
    .A(_0127_),
    .B(_0088_),
    .Y(data_out0[2])
  );
  NOR _0724_ (
    .A(\D0Fifo.memoria.Ram[2] [3]),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0130_)
  );
  NOT _0725_ (
    .A(\D0Fifo.memoria.Ram[3] [3]),
    .Y(_0131_)
  );
  NAND _0726_ (
    .A(_0131_),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0132_)
  );
  NAND _0727_ (
    .A(_0132_),
    .B(\D0Fifo.memoria.iReadAddress [1]),
    .Y(_0133_)
  );
  NOR _0728_ (
    .A(_0133_),
    .B(_0130_),
    .Y(_0134_)
  );
  NOT _0729_ (
    .A(\D0Fifo.memoria.Ram[1] [3]),
    .Y(_0135_)
  );
  NOR _0730_ (
    .A(_0135_),
    .B(_0054_),
    .Y(_0136_)
  );
  NOT _0731_ (
    .A(\D0Fifo.memoria.Ram[0] [3]),
    .Y(_0137_)
  );
  NOR _0732_ (
    .A(_0137_),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0138_)
  );
  NOR _0733_ (
    .A(_0138_),
    .B(_0136_),
    .Y(_0139_)
  );
  NOR _0734_ (
    .A(_0139_),
    .B(\D0Fifo.memoria.iReadAddress [1]),
    .Y(_0140_)
  );
  NOR _0735_ (
    .A(_0140_),
    .B(_0134_),
    .Y(_0142_)
  );
  NOR _0736_ (
    .A(_0142_),
    .B(_0088_),
    .Y(data_out0[3])
  );
  NOR _0737_ (
    .A(\D0Fifo.memoria.Ram[2] [4]),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0144_)
  );
  NOT _0738_ (
    .A(\D0Fifo.memoria.Ram[3] [4]),
    .Y(_0145_)
  );
  NAND _0739_ (
    .A(_0145_),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0146_)
  );
  NAND _0740_ (
    .A(_0146_),
    .B(\D0Fifo.memoria.iReadAddress [1]),
    .Y(_0147_)
  );
  NOR _0741_ (
    .A(_0147_),
    .B(_0144_),
    .Y(_0148_)
  );
  NOT _0742_ (
    .A(\D0Fifo.memoria.Ram[1] [4]),
    .Y(_0149_)
  );
  NOR _0743_ (
    .A(_0149_),
    .B(_0054_),
    .Y(_0150_)
  );
  NOT _0744_ (
    .A(\D0Fifo.memoria.Ram[0] [4]),
    .Y(_0151_)
  );
  NOR _0745_ (
    .A(_0151_),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0152_)
  );
  NOR _0746_ (
    .A(_0152_),
    .B(_0150_),
    .Y(_0153_)
  );
  NOR _0747_ (
    .A(_0153_),
    .B(\D0Fifo.memoria.iReadAddress [1]),
    .Y(_0155_)
  );
  NOR _0748_ (
    .A(_0155_),
    .B(_0148_),
    .Y(_0157_)
  );
  NOR _0749_ (
    .A(_0157_),
    .B(_0088_),
    .Y(data_out0[4])
  );
  NOR _0750_ (
    .A(\D0Fifo.memoria.Ram[2] [5]),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0158_)
  );
  NOT _0751_ (
    .A(\D0Fifo.memoria.Ram[3] [5]),
    .Y(_0159_)
  );
  NAND _0752_ (
    .A(_0159_),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0160_)
  );
  NAND _0753_ (
    .A(_0160_),
    .B(\D0Fifo.memoria.iReadAddress [1]),
    .Y(_0161_)
  );
  NOR _0754_ (
    .A(_0161_),
    .B(_0158_),
    .Y(_0162_)
  );
  NOT _0755_ (
    .A(\D0Fifo.memoria.Ram[1] [5]),
    .Y(_0163_)
  );
  NOR _0756_ (
    .A(_0163_),
    .B(_0054_),
    .Y(_0164_)
  );
  NOT _0757_ (
    .A(\D0Fifo.memoria.Ram[0] [5]),
    .Y(_0165_)
  );
  NOR _0758_ (
    .A(_0165_),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0167_)
  );
  NOR _0759_ (
    .A(_0167_),
    .B(_0164_),
    .Y(_0168_)
  );
  NOR _0760_ (
    .A(_0168_),
    .B(\D0Fifo.memoria.iReadAddress [1]),
    .Y(_0170_)
  );
  NOR _0761_ (
    .A(_0170_),
    .B(_0162_),
    .Y(_0172_)
  );
  NOR _0762_ (
    .A(_0172_),
    .B(_0088_),
    .Y(data_out0[5])
  );
  NOR _0763_ (
    .A(_0068_),
    .B(_0043_),
    .Y(_0175_)
  );
  NAND _0764_ (
    .A(_0175_),
    .B(\D0Fifo.memoria.iWriteAddress [1]),
    .Y(_0176_)
  );
  NOT _0765_ (
    .A(_0176_),
    .Y(_0177_)
  );
  NAND _0766_ (
    .A(_0177_),
    .B(\D0Fifo.Fifo_Data_in_int [0]),
    .Y(_0178_)
  );
  NAND _0767_ (
    .A(_0176_),
    .B(\D0Fifo.memoria.Ram[3] [0]),
    .Y(_0179_)
  );
  NAND _0768_ (
    .A(_0179_),
    .B(_0178_),
    .Y(_0004_)
  );
  NAND _0769_ (
    .A(_0177_),
    .B(\D0Fifo.Fifo_Data_in_int [1]),
    .Y(_0181_)
  );
  NAND _0770_ (
    .A(_0176_),
    .B(\D0Fifo.memoria.Ram[3] [1]),
    .Y(_0182_)
  );
  NAND _0771_ (
    .A(_0182_),
    .B(_0181_),
    .Y(_0005_)
  );
  NAND _0772_ (
    .A(_0177_),
    .B(\D0Fifo.Fifo_Data_in_int [2]),
    .Y(_0183_)
  );
  NAND _0773_ (
    .A(_0176_),
    .B(\D0Fifo.memoria.Ram[3] [2]),
    .Y(_0184_)
  );
  NAND _0774_ (
    .A(_0184_),
    .B(_0183_),
    .Y(_0006_)
  );
  NAND _0775_ (
    .A(_0177_),
    .B(\D0Fifo.Fifo_Data_in_int [3]),
    .Y(_0185_)
  );
  NAND _0776_ (
    .A(_0176_),
    .B(\D0Fifo.memoria.Ram[3] [3]),
    .Y(_0186_)
  );
  NAND _0777_ (
    .A(_0186_),
    .B(_0185_),
    .Y(_0007_)
  );
  NAND _0778_ (
    .A(_0177_),
    .B(\D0Fifo.Fifo_Data_in_int [4]),
    .Y(_0187_)
  );
  NAND _0779_ (
    .A(_0176_),
    .B(\D0Fifo.memoria.Ram[3] [4]),
    .Y(_0188_)
  );
  NAND _0780_ (
    .A(_0188_),
    .B(_0187_),
    .Y(_0008_)
  );
  NAND _0781_ (
    .A(_0177_),
    .B(\D0Fifo.Fifo_Data_in_int [5]),
    .Y(_0189_)
  );
  NAND _0782_ (
    .A(_0176_),
    .B(\D0Fifo.memoria.Ram[3] [5]),
    .Y(_0190_)
  );
  NAND _0783_ (
    .A(_0190_),
    .B(_0189_),
    .Y(_0009_)
  );
  NAND _0784_ (
    .A(_0069_),
    .B(\D0Fifo.memoria.iWriteAddress [1]),
    .Y(_0193_)
  );
  NOT _0785_ (
    .A(_0193_),
    .Y(_0195_)
  );
  NAND _0786_ (
    .A(_0195_),
    .B(\D0Fifo.Fifo_Data_in_int [0]),
    .Y(_0196_)
  );
  NAND _0787_ (
    .A(_0193_),
    .B(\D0Fifo.memoria.Ram[2] [0]),
    .Y(_0198_)
  );
  NAND _0788_ (
    .A(_0198_),
    .B(_0196_),
    .Y(_0010_)
  );
  NAND _0789_ (
    .A(_0195_),
    .B(\D0Fifo.Fifo_Data_in_int [1]),
    .Y(_0199_)
  );
  NAND _0790_ (
    .A(_0193_),
    .B(\D0Fifo.memoria.Ram[2] [1]),
    .Y(_0200_)
  );
  NAND _0791_ (
    .A(_0200_),
    .B(_0199_),
    .Y(_0011_)
  );
  NAND _0792_ (
    .A(_0195_),
    .B(\D0Fifo.Fifo_Data_in_int [2]),
    .Y(_0201_)
  );
  NAND _0793_ (
    .A(_0193_),
    .B(\D0Fifo.memoria.Ram[2] [2]),
    .Y(_0202_)
  );
  NAND _0794_ (
    .A(_0202_),
    .B(_0201_),
    .Y(_0012_)
  );
  NAND _0795_ (
    .A(_0195_),
    .B(\D0Fifo.Fifo_Data_in_int [3]),
    .Y(_0203_)
  );
  NAND _0796_ (
    .A(_0193_),
    .B(\D0Fifo.memoria.Ram[2] [3]),
    .Y(_0204_)
  );
  NAND _0797_ (
    .A(_0204_),
    .B(_0203_),
    .Y(_0013_)
  );
  NAND _0798_ (
    .A(_0195_),
    .B(\D0Fifo.Fifo_Data_in_int [4]),
    .Y(_0205_)
  );
  NAND _0799_ (
    .A(_0193_),
    .B(\D0Fifo.memoria.Ram[2] [4]),
    .Y(_0206_)
  );
  NAND _0800_ (
    .A(_0206_),
    .B(_0205_),
    .Y(_0014_)
  );
  NAND _0801_ (
    .A(_0195_),
    .B(\D0Fifo.Fifo_Data_in_int [5]),
    .Y(_0207_)
  );
  NAND _0802_ (
    .A(_0193_),
    .B(\D0Fifo.memoria.Ram[2] [5]),
    .Y(_0208_)
  );
  NAND _0803_ (
    .A(_0208_),
    .B(_0207_),
    .Y(_0015_)
  );
  NAND _0804_ (
    .A(_0175_),
    .B(_0047_),
    .Y(_0210_)
  );
  NOT _0805_ (
    .A(_0210_),
    .Y(_0211_)
  );
  NAND _0806_ (
    .A(_0211_),
    .B(\D0Fifo.Fifo_Data_in_int [0]),
    .Y(_0212_)
  );
  NAND _0807_ (
    .A(_0210_),
    .B(\D0Fifo.memoria.Ram[1] [0]),
    .Y(_0213_)
  );
  NAND _0808_ (
    .A(_0213_),
    .B(_0212_),
    .Y(_0016_)
  );
  NAND _0809_ (
    .A(_0211_),
    .B(\D0Fifo.Fifo_Data_in_int [1]),
    .Y(_0214_)
  );
  NAND _0810_ (
    .A(_0210_),
    .B(\D0Fifo.memoria.Ram[1] [1]),
    .Y(_0215_)
  );
  NAND _0811_ (
    .A(_0215_),
    .B(_0214_),
    .Y(_0017_)
  );
  NAND _0812_ (
    .A(_0211_),
    .B(\D0Fifo.Fifo_Data_in_int [2]),
    .Y(_0216_)
  );
  NAND _0813_ (
    .A(_0210_),
    .B(\D0Fifo.memoria.Ram[1] [2]),
    .Y(_0217_)
  );
  NAND _0814_ (
    .A(_0217_),
    .B(_0216_),
    .Y(_0018_)
  );
  NAND _0815_ (
    .A(_0211_),
    .B(\D0Fifo.Fifo_Data_in_int [3]),
    .Y(_0218_)
  );
  NAND _0816_ (
    .A(_0210_),
    .B(\D0Fifo.memoria.Ram[1] [3]),
    .Y(_0219_)
  );
  NAND _0817_ (
    .A(_0219_),
    .B(_0218_),
    .Y(_0019_)
  );
  NAND _0818_ (
    .A(_0211_),
    .B(\D0Fifo.Fifo_Data_in_int [4]),
    .Y(_0220_)
  );
  NAND _0819_ (
    .A(_0210_),
    .B(\D0Fifo.memoria.Ram[1] [4]),
    .Y(_0221_)
  );
  NAND _0820_ (
    .A(_0221_),
    .B(_0220_),
    .Y(_0020_)
  );
  NAND _0821_ (
    .A(_0211_),
    .B(\D0Fifo.Fifo_Data_in_int [5]),
    .Y(_0223_)
  );
  NAND _0822_ (
    .A(_0210_),
    .B(\D0Fifo.memoria.Ram[1] [5]),
    .Y(_0225_)
  );
  NAND _0823_ (
    .A(_0225_),
    .B(_0223_),
    .Y(_0021_)
  );
  NOT _0824_ (
    .A(\D1Fifo.memoria.iReadAddress [0]),
    .Y(_0228_)
  );
  NOR _0825_ (
    .A(_0228_),
    .B(_0031_),
    .Y(_0022_)
  );
  NOT _0826_ (
    .A(\D1Fifo.memoria.iReadAddress [1]),
    .Y(_0229_)
  );
  NOR _0827_ (
    .A(_0229_),
    .B(_0031_),
    .Y(_0023_)
  );
  NOT _0828_ (
    .A(\Demux_D0_D1.valid_in ),
    .Y(_0232_)
  );
  NOR _0829_ (
    .A(_0232_),
    .B(_0031_),
    .Y(_0024_)
  );
  NAND _0830_ (
    .A(_0024_),
    .B(\Demux_D0_D1.data_in [0]),
    .Y(_0233_)
  );
  NOR _0831_ (
    .A(\Demux_D0_D1.valid_in ),
    .B(_0042_),
    .Y(_0234_)
  );
  NAND _0832_ (
    .A(_0234_),
    .B(_0328_),
    .Y(_0235_)
  );
  NAND _0833_ (
    .A(_0235_),
    .B(_0233_),
    .Y(_0025_)
  );
  NOT _0834_ (
    .A(_0234_),
    .Y(_0236_)
  );
  NOR _0835_ (
    .A(_0236_),
    .B(_0061_),
    .Y(_0026_)
  );
  NOR _0836_ (
    .A(_0236_),
    .B(_0062_),
    .Y(_0027_)
  );
  NOR _0837_ (
    .A(_0236_),
    .B(_0064_),
    .Y(_0028_)
  );
  NOR _0838_ (
    .A(_0236_),
    .B(_0065_),
    .Y(_0029_)
  );
  NOR _0839_ (
    .A(_0236_),
    .B(_0067_),
    .Y(_0030_)
  );
  NOT _0840_ (
    .A(\MainFifo.memoria.iReadAddress [0]),
    .Y(_0239_)
  );
  NOT _0841_ (
    .A(pop),
    .Y(_0240_)
  );
  NOR _0842_ (
    .A(_0240_),
    .B(push),
    .Y(_0241_)
  );
  NOT _0843_ (
    .A(_0241_),
    .Y(_0242_)
  );
  NOR _0844_ (
    .A(_0242_),
    .B(_0239_),
    .Y(_0243_)
  );
  NAND _0845_ (
    .A(_0242_),
    .B(_0239_),
    .Y(_0244_)
  );
  NAND _0846_ (
    .A(_0244_),
    .B(reset_L),
    .Y(_0245_)
  );
  NOR _0847_ (
    .A(_0245_),
    .B(_0243_),
    .Y(_0040_)
  );
  NAND _0848_ (
    .A(_0243_),
    .B(\MainFifo.memoria.iReadAddress [1]),
    .Y(_0246_)
  );
  NOT _0849_ (
    .A(\MainFifo.memoria.iReadAddress [1]),
    .Y(_0247_)
  );
  NOT _0850_ (
    .A(_0243_),
    .Y(_0249_)
  );
  NAND _0851_ (
    .A(_0249_),
    .B(_0247_),
    .Y(_0250_)
  );
  NAND _0852_ (
    .A(_0250_),
    .B(_0246_),
    .Y(_0252_)
  );
  NOR _0853_ (
    .A(_0252_),
    .B(_0031_),
    .Y(_0041_)
  );
  NOT _0854_ (
    .A(push),
    .Y(_0255_)
  );
  NOT _0855_ (
    .A(\MainFifo.memoria.iWriteAddress [0]),
    .Y(_0256_)
  );
  NOR _0856_ (
    .A(_0256_),
    .B(_0255_),
    .Y(_0257_)
  );
  NAND _0857_ (
    .A(_0256_),
    .B(_0255_),
    .Y(_0258_)
  );
  NAND _0858_ (
    .A(_0258_),
    .B(reset_L),
    .Y(_0259_)
  );
  NOR _0859_ (
    .A(_0259_),
    .B(_0257_),
    .Y(_0052_)
  );
  NOT _0860_ (
    .A(\MainFifo.memoria.iWriteAddress [1]),
    .Y(_0260_)
  );
  NOT _0861_ (
    .A(_0257_),
    .Y(_0262_)
  );
  NOR _0862_ (
    .A(_0262_),
    .B(_0260_),
    .Y(_0263_)
  );
  NAND _0863_ (
    .A(_0262_),
    .B(_0260_),
    .Y(_0264_)
  );
  NAND _0864_ (
    .A(_0264_),
    .B(reset_L),
    .Y(_0265_)
  );
  NOR _0865_ (
    .A(_0265_),
    .B(_0263_),
    .Y(_0053_)
  );
  NOT _0866_ (
    .A(data_in_principal[0]),
    .Y(_0266_)
  );
  NOR _0867_ (
    .A(_0266_),
    .B(_0031_),
    .Y(_0055_)
  );
  NOT _0868_ (
    .A(data_in_principal[5]),
    .Y(_0267_)
  );
  NOR _0869_ (
    .A(_0267_),
    .B(_0031_),
    .Y(_0057_)
  );
  NAND _0870_ (
    .A(pop),
    .B(reset_L),
    .Y(_0268_)
  );
  NOT _0871_ (
    .A(_0268_),
    .Y(_0059_)
  );
  NOR _0872_ (
    .A(_0255_),
    .B(_0031_),
    .Y(_0060_)
  );
  NOT _0873_ (
    .A(\MainFifo.memoria.iWriteEnable ),
    .Y(_0269_)
  );
  NOR _0874_ (
    .A(_0269_),
    .B(\MainFifo.memoria.iWriteAddress [0]),
    .Y(_0270_)
  );
  NAND _0875_ (
    .A(_0270_),
    .B(_0260_),
    .Y(_0272_)
  );
  NOT _0876_ (
    .A(_0272_),
    .Y(_0273_)
  );
  NAND _0877_ (
    .A(_0273_),
    .B(\MainFifo.Fifo_Data_in_int [0]),
    .Y(_0275_)
  );
  NAND _0878_ (
    .A(_0272_),
    .B(\MainFifo.memoria.Ram[0] [0]),
    .Y(_0276_)
  );
  NAND _0879_ (
    .A(_0276_),
    .B(_0275_),
    .Y(_0063_)
  );
  NAND _0880_ (
    .A(_0273_),
    .B(\MainFifo.Fifo_Data_in_int [5]),
    .Y(_0278_)
  );
  NAND _0881_ (
    .A(_0272_),
    .B(\MainFifo.memoria.Ram[0] [5]),
    .Y(_0279_)
  );
  NAND _0882_ (
    .A(_0279_),
    .B(_0278_),
    .Y(_0066_)
  );
  NOR _0883_ (
    .A(_0269_),
    .B(_0256_),
    .Y(_0280_)
  );
  NAND _0884_ (
    .A(_0280_),
    .B(\MainFifo.memoria.iWriteAddress [1]),
    .Y(_0281_)
  );
  NOT _0885_ (
    .A(_0281_),
    .Y(_0282_)
  );
  NAND _0886_ (
    .A(_0282_),
    .B(\MainFifo.Fifo_Data_in_int [0]),
    .Y(_0283_)
  );
  NAND _0887_ (
    .A(_0281_),
    .B(\MainFifo.memoria.Ram[3] [0]),
    .Y(_0284_)
  );
  NAND _0888_ (
    .A(_0284_),
    .B(_0283_),
    .Y(_0082_)
  );
  NAND _0889_ (
    .A(_0282_),
    .B(\MainFifo.Fifo_Data_in_int [5]),
    .Y(_0286_)
  );
  NAND _0890_ (
    .A(_0281_),
    .B(\MainFifo.memoria.Ram[3] [5]),
    .Y(_0287_)
  );
  NAND _0891_ (
    .A(_0287_),
    .B(_0286_),
    .Y(_0083_)
  );
  NAND _0892_ (
    .A(_0270_),
    .B(\MainFifo.memoria.iWriteAddress [1]),
    .Y(_0289_)
  );
  NOT _0893_ (
    .A(_0289_),
    .Y(_0290_)
  );
  NAND _0894_ (
    .A(_0290_),
    .B(\MainFifo.Fifo_Data_in_int [0]),
    .Y(_0291_)
  );
  NAND _0895_ (
    .A(_0289_),
    .B(\MainFifo.memoria.Ram[2] [0]),
    .Y(_0293_)
  );
  NAND _0896_ (
    .A(_0293_),
    .B(_0291_),
    .Y(_0086_)
  );
  NAND _0897_ (
    .A(_0290_),
    .B(\MainFifo.Fifo_Data_in_int [5]),
    .Y(_0294_)
  );
  NAND _0898_ (
    .A(_0289_),
    .B(\MainFifo.memoria.Ram[2] [5]),
    .Y(_0295_)
  );
  NAND _0899_ (
    .A(_0295_),
    .B(_0294_),
    .Y(_0087_)
  );
  NAND _0900_ (
    .A(_0280_),
    .B(_0260_),
    .Y(_0297_)
  );
  NOT _0901_ (
    .A(_0297_),
    .Y(_0298_)
  );
  NAND _0902_ (
    .A(_0298_),
    .B(\MainFifo.Fifo_Data_in_int [0]),
    .Y(_0299_)
  );
  NAND _0903_ (
    .A(_0297_),
    .B(\MainFifo.memoria.Ram[1] [0]),
    .Y(_0300_)
  );
  NAND _0904_ (
    .A(_0300_),
    .B(_0299_),
    .Y(_0090_)
  );
  NAND _0905_ (
    .A(_0298_),
    .B(\MainFifo.Fifo_Data_in_int [5]),
    .Y(_0301_)
  );
  NAND _0906_ (
    .A(_0297_),
    .B(\MainFifo.memoria.Ram[1] [5]),
    .Y(_0302_)
  );
  NAND _0907_ (
    .A(_0302_),
    .B(_0301_),
    .Y(_0092_)
  );
  NOT _0908_ (
    .A(\VC0Fifo.num_mem [0]),
    .Y(_0303_)
  );
  NOR _0909_ (
    .A(\VC0Fifo.pop ),
    .B(\VC0Fifo.push ),
    .Y(_0304_)
  );
  NAND _0910_ (
    .A(_0304_),
    .B(_0303_),
    .Y(_0305_)
  );
  NOT _0911_ (
    .A(_0304_),
    .Y(_0306_)
  );
  NAND _0912_ (
    .A(_0306_),
    .B(\VC0Fifo.num_mem [0]),
    .Y(_0307_)
  );
  NAND _0913_ (
    .A(_0307_),
    .B(_0305_),
    .Y(_0308_)
  );
  NOR _0914_ (
    .A(_0308_),
    .B(_0031_),
    .Y(_0126_)
  );
  NAND _0915_ (
    .A(\VC0Fifo.push ),
    .B(\VC0Fifo.num_mem [0]),
    .Y(_0309_)
  );
  NOT _0916_ (
    .A(\VC0Fifo.pop ),
    .Y(_0310_)
  );
  NOR _0917_ (
    .A(_0310_),
    .B(\VC0Fifo.push ),
    .Y(_0311_)
  );
  NAND _0918_ (
    .A(_0311_),
    .B(_0303_),
    .Y(_0312_)
  );
  NAND _0919_ (
    .A(_0312_),
    .B(_0309_),
    .Y(_0313_)
  );
  NOR _0920_ (
    .A(_0313_),
    .B(\VC0Fifo.num_mem [1]),
    .Y(_0314_)
  );
  NAND _0921_ (
    .A(_0313_),
    .B(\VC0Fifo.num_mem [1]),
    .Y(_0315_)
  );
  NAND _0922_ (
    .A(_0315_),
    .B(reset_L),
    .Y(_0316_)
  );
  NOR _0923_ (
    .A(_0316_),
    .B(_0314_),
    .Y(_0128_)
  );
  NOT _0924_ (
    .A(\VC0Fifo.num_mem [2]),
    .Y(_0317_)
  );
  NOR _0925_ (
    .A(_0312_),
    .B(\VC0Fifo.num_mem [1]),
    .Y(_0318_)
  );
  NOT _0926_ (
    .A(\VC0Fifo.num_mem [1]),
    .Y(_0319_)
  );
  NOR _0927_ (
    .A(_0309_),
    .B(_0319_),
    .Y(_0320_)
  );
  NOR _0928_ (
    .A(_0320_),
    .B(_0318_),
    .Y(_0321_)
  );
  NOR _0929_ (
    .A(_0321_),
    .B(_0317_),
    .Y(_0322_)
  );
  NAND _0930_ (
    .A(_0321_),
    .B(_0317_),
    .Y(_0323_)
  );
  NAND _0931_ (
    .A(_0323_),
    .B(reset_L),
    .Y(_0324_)
  );
  NOR _0932_ (
    .A(_0324_),
    .B(_0322_),
    .Y(_0129_)
  );
  NOT _0933_ (
    .A(\VC0Fifo.memoria.iReadAddress [0]),
    .Y(_0325_)
  );
  NOT _0934_ (
    .A(_0311_),
    .Y(_0326_)
  );
  NOR _0935_ (
    .A(_0326_),
    .B(_0325_),
    .Y(_0327_)
  );
  NAND _0936_ (
    .A(_0326_),
    .B(_0325_),
    .Y(_0329_)
  );
  NAND _0937_ (
    .A(_0329_),
    .B(reset_L),
    .Y(_0330_)
  );
  NOR _0938_ (
    .A(_0330_),
    .B(_0327_),
    .Y(_0141_)
  );
  NAND _0939_ (
    .A(_0327_),
    .B(\VC0Fifo.memoria.iReadAddress [1]),
    .Y(_0331_)
  );
  NOT _0940_ (
    .A(\VC0Fifo.memoria.iReadAddress [1]),
    .Y(_0332_)
  );
  NOT _0941_ (
    .A(_0327_),
    .Y(_0333_)
  );
  NAND _0942_ (
    .A(_0333_),
    .B(_0332_),
    .Y(_0334_)
  );
  NAND _0943_ (
    .A(_0334_),
    .B(_0331_),
    .Y(_0335_)
  );
  NOR _0944_ (
    .A(_0335_),
    .B(_0031_),
    .Y(_0143_)
  );
  NOT _0945_ (
    .A(\VC0Fifo.push ),
    .Y(_0336_)
  );
  NOT _0946_ (
    .A(\VC0Fifo.memoria.iWriteAddress [0]),
    .Y(_0337_)
  );
  NOR _0947_ (
    .A(_0337_),
    .B(_0336_),
    .Y(_0338_)
  );
  NAND _0948_ (
    .A(_0337_),
    .B(_0336_),
    .Y(_0339_)
  );
  NAND _0949_ (
    .A(_0339_),
    .B(reset_L),
    .Y(_0340_)
  );
  NOR _0950_ (
    .A(_0340_),
    .B(_0338_),
    .Y(_0154_)
  );
  NOT _0951_ (
    .A(\VC0Fifo.memoria.iWriteAddress [1]),
    .Y(_0341_)
  );
  NOT _0952_ (
    .A(_0338_),
    .Y(_0342_)
  );
  NOR _0953_ (
    .A(_0342_),
    .B(_0341_),
    .Y(_0343_)
  );
  NAND _0954_ (
    .A(_0342_),
    .B(_0341_),
    .Y(_0344_)
  );
  NAND _0955_ (
    .A(_0344_),
    .B(reset_L),
    .Y(_0345_)
  );
  NOR _0956_ (
    .A(_0345_),
    .B(_0343_),
    .Y(_0156_)
  );
  NAND _0957_ (
    .A(_0303_),
    .B(Fifo_Empty_VC0),
    .Y(_0347_)
  );
  NOR _0958_ (
    .A(_0347_),
    .B(\VC0Fifo.push ),
    .Y(_0348_)
  );
  NOR _0959_ (
    .A(_0348_),
    .B(_0318_),
    .Y(_0349_)
  );
  NOR _0960_ (
    .A(_0349_),
    .B(\VC0Fifo.num_mem [2]),
    .Y(_0350_)
  );
  NOT _0961_ (
    .A(Fifo_Empty_VC0),
    .Y(_0351_)
  );
  NOR _0962_ (
    .A(\VC0Fifo.num_mem [1]),
    .B(\VC0Fifo.num_mem [0]),
    .Y(_0352_)
  );
  NOR _0963_ (
    .A(_0352_),
    .B(_0317_),
    .Y(_0353_)
  );
  NOR _0964_ (
    .A(_0353_),
    .B(_0304_),
    .Y(_0354_)
  );
  NOR _0965_ (
    .A(_0354_),
    .B(_0351_),
    .Y(_0355_)
  );
  NOR _0966_ (
    .A(_0355_),
    .B(_0350_),
    .Y(_0356_)
  );
  NOR _0967_ (
    .A(_0356_),
    .B(_0031_),
    .Y(_0166_)
  );
  NOT _0968_ (
    .A(\VC0Fifo.Fifo_Data_in [0]),
    .Y(_0357_)
  );
  NOR _0969_ (
    .A(_0357_),
    .B(_0031_),
    .Y(_0169_)
  );
  NOR _0970_ (
    .A(_0310_),
    .B(_0031_),
    .Y(_0171_)
  );
  NOR _0971_ (
    .A(_0336_),
    .B(_0031_),
    .Y(_0173_)
  );
  NOT _0972_ (
    .A(\VC0Fifo.memoria.iWriteEnable ),
    .Y(_0358_)
  );
  NOR _0973_ (
    .A(_0358_),
    .B(\VC0Fifo.memoria.iWriteAddress [0]),
    .Y(_0359_)
  );
  NAND _0974_ (
    .A(_0359_),
    .B(_0341_),
    .Y(_0360_)
  );
  NOT _0975_ (
    .A(_0360_),
    .Y(_0361_)
  );
  NAND _0976_ (
    .A(_0361_),
    .B(\VC0Fifo.Fifo_Data_in_int [0]),
    .Y(_0363_)
  );
  NAND _0977_ (
    .A(_0360_),
    .B(\VC0Fifo.memoria.Ram[0] [0]),
    .Y(_0364_)
  );
  NAND _0978_ (
    .A(_0364_),
    .B(_0363_),
    .Y(_0180_)
  );
  NOR _0979_ (
    .A(_0358_),
    .B(_0337_),
    .Y(_0365_)
  );
  NAND _0980_ (
    .A(_0365_),
    .B(\VC0Fifo.memoria.iWriteAddress [1]),
    .Y(_0366_)
  );
  NOT _0981_ (
    .A(_0366_),
    .Y(_0367_)
  );
  NAND _0982_ (
    .A(_0367_),
    .B(\VC0Fifo.Fifo_Data_in_int [0]),
    .Y(_0368_)
  );
  NAND _0983_ (
    .A(_0366_),
    .B(\VC0Fifo.memoria.Ram[3] [0]),
    .Y(_0369_)
  );
  NAND _0984_ (
    .A(_0369_),
    .B(_0368_),
    .Y(_0192_)
  );
  NAND _0985_ (
    .A(_0359_),
    .B(\VC0Fifo.memoria.iWriteAddress [1]),
    .Y(_0370_)
  );
  NOT _0986_ (
    .A(_0370_),
    .Y(_0371_)
  );
  NAND _0987_ (
    .A(_0371_),
    .B(\VC0Fifo.Fifo_Data_in_int [0]),
    .Y(_0372_)
  );
  NAND _0988_ (
    .A(_0370_),
    .B(\VC0Fifo.memoria.Ram[2] [0]),
    .Y(_0373_)
  );
  NAND _0989_ (
    .A(_0373_),
    .B(_0372_),
    .Y(_0194_)
  );
  NAND _0990_ (
    .A(_0365_),
    .B(_0341_),
    .Y(_0374_)
  );
  NOT _0991_ (
    .A(_0374_),
    .Y(_0375_)
  );
  NAND _0992_ (
    .A(_0375_),
    .B(\VC0Fifo.Fifo_Data_in_int [0]),
    .Y(_0376_)
  );
  NAND _0993_ (
    .A(_0374_),
    .B(\VC0Fifo.memoria.Ram[1] [0]),
    .Y(_0377_)
  );
  NAND _0994_ (
    .A(_0377_),
    .B(_0376_),
    .Y(_0197_)
  );
  NOT _0995_ (
    .A(\VC1Fifo.num_mem [0]),
    .Y(_0378_)
  );
  NOR _0996_ (
    .A(\VC1Fifo.push ),
    .B(\VC1Fifo.pop ),
    .Y(_0380_)
  );
  NAND _0997_ (
    .A(_0380_),
    .B(_0378_),
    .Y(_0381_)
  );
  NOT _0998_ (
    .A(_0380_),
    .Y(_0382_)
  );
  NAND _0999_ (
    .A(_0382_),
    .B(\VC1Fifo.num_mem [0]),
    .Y(_0383_)
  );
  NAND _1000_ (
    .A(_0383_),
    .B(_0381_),
    .Y(_0384_)
  );
  NOR _1001_ (
    .A(_0384_),
    .B(_0031_),
    .Y(_0222_)
  );
  NOR _1002_ (
    .A(\VC1Fifo.push ),
    .B(_0037_),
    .Y(_0385_)
  );
  NOR _1003_ (
    .A(_0385_),
    .B(\VC1Fifo.num_mem [0]),
    .Y(_0386_)
  );
  NOR _1004_ (
    .A(\VC1Fifo.push ),
    .B(_0378_),
    .Y(_0387_)
  );
  NOR _1005_ (
    .A(_0387_),
    .B(_0386_),
    .Y(_0388_)
  );
  NOR _1006_ (
    .A(_0388_),
    .B(\VC1Fifo.num_mem [1]),
    .Y(_0389_)
  );
  NAND _1007_ (
    .A(_0388_),
    .B(\VC1Fifo.num_mem [1]),
    .Y(_0390_)
  );
  NAND _1008_ (
    .A(_0390_),
    .B(reset_L),
    .Y(_0391_)
  );
  NOR _1009_ (
    .A(_0391_),
    .B(_0389_),
    .Y(_0224_)
  );
  NOT _1010_ (
    .A(\VC1Fifo.num_mem [2]),
    .Y(_0394_)
  );
  NOT _1011_ (
    .A(\VC1Fifo.num_mem [1]),
    .Y(_0396_)
  );
  NAND _1012_ (
    .A(_0396_),
    .B(_0378_),
    .Y(_0398_)
  );
  NAND _1013_ (
    .A(\VC1Fifo.num_mem [1]),
    .B(\VC1Fifo.num_mem [0]),
    .Y(_0399_)
  );
  NAND _1014_ (
    .A(_0399_),
    .B(_0398_),
    .Y(_0401_)
  );
  NAND _1015_ (
    .A(_0401_),
    .B(_0388_),
    .Y(_0402_)
  );
  NOR _1016_ (
    .A(_0402_),
    .B(_0394_),
    .Y(_0404_)
  );
  NAND _1017_ (
    .A(_0402_),
    .B(_0394_),
    .Y(_0405_)
  );
  NAND _1018_ (
    .A(_0405_),
    .B(reset_L),
    .Y(_0406_)
  );
  NOR _1019_ (
    .A(_0406_),
    .B(_0404_),
    .Y(_0227_)
  );
  NOT _1020_ (
    .A(\VC1Fifo.memoria.iReadAddress [0]),
    .Y(_0407_)
  );
  NOT _1021_ (
    .A(_0385_),
    .Y(_0408_)
  );
  NOR _1022_ (
    .A(_0408_),
    .B(_0407_),
    .Y(_0409_)
  );
  NAND _1023_ (
    .A(_0408_),
    .B(_0407_),
    .Y(_0410_)
  );
  NAND _1024_ (
    .A(_0410_),
    .B(reset_L),
    .Y(_0411_)
  );
  NOR _1025_ (
    .A(_0411_),
    .B(_0409_),
    .Y(_0230_)
  );
  NOT _1026_ (
    .A(\VC1Fifo.memoria.iReadAddress [1]),
    .Y(_0413_)
  );
  NOR _1027_ (
    .A(_0409_),
    .B(_0413_),
    .Y(_0415_)
  );
  NOT _1028_ (
    .A(_0409_),
    .Y(_0417_)
  );
  NOR _1029_ (
    .A(_0417_),
    .B(\VC1Fifo.memoria.iReadAddress [1]),
    .Y(_0419_)
  );
  NOR _1030_ (
    .A(_0419_),
    .B(_0415_),
    .Y(_0421_)
  );
  NOR _1031_ (
    .A(_0421_),
    .B(_0031_),
    .Y(_0231_)
  );
  NOT _1032_ (
    .A(\VC1Fifo.push ),
    .Y(_0423_)
  );
  NOT _1033_ (
    .A(\VC1Fifo.memoria.iWriteAddress [0]),
    .Y(_0425_)
  );
  NOR _1034_ (
    .A(_0425_),
    .B(_0423_),
    .Y(_0426_)
  );
  NAND _1035_ (
    .A(_0425_),
    .B(_0423_),
    .Y(_0428_)
  );
  NAND _1036_ (
    .A(_0428_),
    .B(reset_L),
    .Y(_0430_)
  );
  NOR _1037_ (
    .A(_0430_),
    .B(_0426_),
    .Y(_0237_)
  );
  NOT _1038_ (
    .A(\VC1Fifo.memoria.iWriteAddress [1]),
    .Y(_0431_)
  );
  NOT _1039_ (
    .A(_0426_),
    .Y(_0432_)
  );
  NOR _1040_ (
    .A(_0432_),
    .B(_0431_),
    .Y(_0433_)
  );
  NAND _1041_ (
    .A(_0432_),
    .B(_0431_),
    .Y(_0434_)
  );
  NAND _1042_ (
    .A(_0434_),
    .B(reset_L),
    .Y(_0435_)
  );
  NOR _1043_ (
    .A(_0435_),
    .B(_0433_),
    .Y(_0238_)
  );
  NAND _1044_ (
    .A(_0394_),
    .B(_0378_),
    .Y(_0436_)
  );
  NOR _1045_ (
    .A(_0436_),
    .B(\VC1Fifo.push ),
    .Y(_0438_)
  );
  NOR _1046_ (
    .A(_0037_),
    .B(_0031_),
    .Y(_0253_)
  );
  NAND _1047_ (
    .A(_0253_),
    .B(_0396_),
    .Y(_0440_)
  );
  NAND _1048_ (
    .A(_0440_),
    .B(_0036_),
    .Y(_0442_)
  );
  NAND _1049_ (
    .A(_0442_),
    .B(_0438_),
    .Y(_0443_)
  );
  NOT _1050_ (
    .A(_0036_),
    .Y(_0444_)
  );
  NAND _1051_ (
    .A(_0398_),
    .B(\VC1Fifo.num_mem [2]),
    .Y(_0445_)
  );
  NAND _1052_ (
    .A(_0445_),
    .B(_0382_),
    .Y(_0446_)
  );
  NAND _1053_ (
    .A(_0446_),
    .B(_0444_),
    .Y(_0447_)
  );
  NAND _1054_ (
    .A(_0447_),
    .B(_0443_),
    .Y(_0248_)
  );
  NAND _1055_ (
    .A(\VC1Fifo.Fifo_Data_in [0]),
    .B(reset_L),
    .Y(_0448_)
  );
  NOT _1056_ (
    .A(_0448_),
    .Y(_0251_)
  );
  NOR _1057_ (
    .A(_0423_),
    .B(_0031_),
    .Y(_0254_)
  );
  NOT _1058_ (
    .A(\VC1Fifo.memoria.iWriteEnable ),
    .Y(_0449_)
  );
  NOR _1059_ (
    .A(_0449_),
    .B(\VC1Fifo.memoria.iWriteAddress [0]),
    .Y(_0450_)
  );
  NAND _1060_ (
    .A(_0450_),
    .B(_0431_),
    .Y(_0451_)
  );
  NOT _1061_ (
    .A(_0451_),
    .Y(_0452_)
  );
  NAND _1062_ (
    .A(_0452_),
    .B(\VC1Fifo.Fifo_Data_in_int [0]),
    .Y(_0453_)
  );
  NAND _1063_ (
    .A(_0451_),
    .B(\VC1Fifo.memoria.Ram[0] [0]),
    .Y(_0454_)
  );
  NAND _1064_ (
    .A(_0454_),
    .B(_0453_),
    .Y(_0261_)
  );
  NOR _1065_ (
    .A(_0449_),
    .B(_0425_),
    .Y(_0455_)
  );
  NAND _1066_ (
    .A(_0455_),
    .B(\VC1Fifo.memoria.iWriteAddress [1]),
    .Y(_0456_)
  );
  NOT _1067_ (
    .A(_0456_),
    .Y(_0457_)
  );
  NAND _1068_ (
    .A(_0457_),
    .B(\VC1Fifo.Fifo_Data_in_int [0]),
    .Y(_0458_)
  );
  NAND _1069_ (
    .A(_0456_),
    .B(\VC1Fifo.memoria.Ram[3] [0]),
    .Y(_0459_)
  );
  NAND _1070_ (
    .A(_0459_),
    .B(_0458_),
    .Y(_0271_)
  );
  NAND _1071_ (
    .A(_0450_),
    .B(\VC1Fifo.memoria.iWriteAddress [1]),
    .Y(_0460_)
  );
  NOT _1072_ (
    .A(_0460_),
    .Y(_0461_)
  );
  NAND _1073_ (
    .A(_0461_),
    .B(\VC1Fifo.Fifo_Data_in_int [0]),
    .Y(_0462_)
  );
  NAND _1074_ (
    .A(_0460_),
    .B(\VC1Fifo.memoria.Ram[2] [0]),
    .Y(_0463_)
  );
  NAND _1075_ (
    .A(_0463_),
    .B(_0462_),
    .Y(_0274_)
  );
  NAND _1076_ (
    .A(_0455_),
    .B(_0431_),
    .Y(_0464_)
  );
  NOT _1077_ (
    .A(_0464_),
    .Y(_0465_)
  );
  NAND _1078_ (
    .A(_0465_),
    .B(\VC1Fifo.Fifo_Data_in_int [0]),
    .Y(_0466_)
  );
  NAND _1079_ (
    .A(_0464_),
    .B(\VC1Fifo.memoria.Ram[1] [0]),
    .Y(_0467_)
  );
  NAND _1080_ (
    .A(_0467_),
    .B(_0466_),
    .Y(_0277_)
  );
  NOT _1081_ (
    .A(\MainFifo.memoria.iReadEnable ),
    .Y(_0468_)
  );
  NOR _1082_ (
    .A(\MainFifo.memoria.Ram[2] [5]),
    .B(\MainFifo.memoria.iReadAddress [0]),
    .Y(_0469_)
  );
  NOT _1083_ (
    .A(\MainFifo.memoria.Ram[3] [5]),
    .Y(_0470_)
  );
  NAND _1084_ (
    .A(_0470_),
    .B(\MainFifo.memoria.iReadAddress [0]),
    .Y(_0471_)
  );
  NAND _1085_ (
    .A(_0471_),
    .B(\MainFifo.memoria.iReadAddress [1]),
    .Y(_0472_)
  );
  NOR _1086_ (
    .A(_0472_),
    .B(_0469_),
    .Y(_0474_)
  );
  NOT _1087_ (
    .A(\MainFifo.memoria.Ram[0] [5]),
    .Y(_0475_)
  );
  NAND _1088_ (
    .A(_0475_),
    .B(_0239_),
    .Y(_0476_)
  );
  NOT _1089_ (
    .A(\MainFifo.memoria.Ram[1] [5]),
    .Y(_0477_)
  );
  NAND _1090_ (
    .A(_0477_),
    .B(\MainFifo.memoria.iReadAddress [0]),
    .Y(_0478_)
  );
  NAND _1091_ (
    .A(_0478_),
    .B(_0476_),
    .Y(_0479_)
  );
  NOR _1092_ (
    .A(_0479_),
    .B(\MainFifo.memoria.iReadAddress [1]),
    .Y(_0480_)
  );
  NOR _1093_ (
    .A(_0480_),
    .B(_0474_),
    .Y(_0481_)
  );
  NOR _1094_ (
    .A(_0481_),
    .B(_0468_),
    .Y(_0482_)
  );
  NAND _1095_ (
    .A(_0482_),
    .B(_0059_),
    .Y(_0483_)
  );
  NOT _1096_ (
    .A(_0483_),
    .Y(_0285_)
  );
  NOR _1097_ (
    .A(_0482_),
    .B(_0268_),
    .Y(_0288_)
  );
  NAND _1098_ (
    .A(\MainFifo.memoria.Ram[3] [0]),
    .B(\MainFifo.memoria.iReadAddress [0]),
    .Y(_0484_)
  );
  NAND _1099_ (
    .A(\MainFifo.memoria.Ram[2] [0]),
    .B(_0239_),
    .Y(_0485_)
  );
  NAND _1100_ (
    .A(_0485_),
    .B(_0484_),
    .Y(_0486_)
  );
  NAND _1101_ (
    .A(_0486_),
    .B(\MainFifo.memoria.iReadAddress [1]),
    .Y(_0487_)
  );
  NAND _1102_ (
    .A(\MainFifo.memoria.Ram[1] [0]),
    .B(\MainFifo.memoria.iReadAddress [0]),
    .Y(_0488_)
  );
  NAND _1103_ (
    .A(\MainFifo.memoria.Ram[0] [0]),
    .B(_0239_),
    .Y(_0489_)
  );
  NAND _1104_ (
    .A(_0489_),
    .B(_0488_),
    .Y(_0490_)
  );
  NAND _1105_ (
    .A(_0490_),
    .B(_0247_),
    .Y(_0491_)
  );
  NAND _1106_ (
    .A(_0491_),
    .B(_0487_),
    .Y(_0492_)
  );
  NOR _1107_ (
    .A(_0492_),
    .B(_0483_),
    .Y(_0493_)
  );
  NAND _1108_ (
    .A(_0483_),
    .B(_0448_),
    .Y(_0494_)
  );
  NAND _1109_ (
    .A(_0423_),
    .B(_0240_),
    .Y(_0495_)
  );
  NAND _1110_ (
    .A(_0495_),
    .B(_0494_),
    .Y(_0496_)
  );
  NOR _1111_ (
    .A(_0496_),
    .B(_0493_),
    .Y(_0292_)
  );
  NOR _1112_ (
    .A(_0336_),
    .B(pop),
    .Y(_0497_)
  );
  NAND _1113_ (
    .A(_0497_),
    .B(_0169_),
    .Y(_0498_)
  );
  NAND _1114_ (
    .A(_0482_),
    .B(_0357_),
    .Y(_0499_)
  );
  NOR _1115_ (
    .A(_0481_),
    .B(_0031_),
    .Y(_0500_)
  );
  NOR _1116_ (
    .A(_0500_),
    .B(_0492_),
    .Y(_0502_)
  );
  NAND _1117_ (
    .A(_0059_),
    .B(\MainFifo.memoria.iReadEnable ),
    .Y(_0503_)
  );
  NOR _1118_ (
    .A(_0503_),
    .B(_0502_),
    .Y(_0504_)
  );
  NAND _1119_ (
    .A(_0504_),
    .B(_0499_),
    .Y(_0505_)
  );
  NAND _1120_ (
    .A(_0505_),
    .B(_0498_),
    .Y(_0296_)
  );
  NOT _1121_ (
    .A(init),
    .Y(_0506_)
  );
  NAND _1122_ (
    .A(_0506_),
    .B(\fsm_Control1.nxt_state [0]),
    .Y(_0507_)
  );
  NAND _1123_ (
    .A(_0507_),
    .B(reset_L),
    .Y(_0392_)
  );
  NOR _1124_ (
    .A(\fsm_Control1.nxt_state [1]),
    .B(init),
    .Y(_0508_)
  );
  NOR _1125_ (
    .A(_0508_),
    .B(_0031_),
    .Y(_0393_)
  );
  NOT _1126_ (
    .A(\fsm_Control1.nxt_state [2]),
    .Y(_0509_)
  );
  NAND _1127_ (
    .A(_0506_),
    .B(reset_L),
    .Y(_0510_)
  );
  NOR _1128_ (
    .A(_0510_),
    .B(_0509_),
    .Y(_0395_)
  );
  NOT _1129_ (
    .A(\fsm_Control1.nxt_state [3]),
    .Y(_0511_)
  );
  NOR _1130_ (
    .A(_0510_),
    .B(_0511_),
    .Y(_0397_)
  );
  NOT _1131_ (
    .A(\fsm_Control1.nxt_state [4]),
    .Y(_0512_)
  );
  NOR _1132_ (
    .A(_0510_),
    .B(_0512_),
    .Y(_0400_)
  );
  NOR _1133_ (
    .A(\fsm_Control1.state [1]),
    .B(\fsm_Control1.state [0]),
    .Y(_0513_)
  );
  NOT _1134_ (
    .A(_0513_),
    .Y(_0514_)
  );
  NOR _1135_ (
    .A(_0514_),
    .B(\fsm_Control1.state [4]),
    .Y(_0515_)
  );
  NOT _1136_ (
    .A(\fsm_Control1.state [3]),
    .Y(_0516_)
  );
  NOR _1137_ (
    .A(_0516_),
    .B(\fsm_Control1.state [2]),
    .Y(_0517_)
  );
  NAND _1138_ (
    .A(_0517_),
    .B(_0515_),
    .Y(_0518_)
  );
  NOT _1139_ (
    .A(_0518_),
    .Y(_0519_)
  );
  NOT _1140_ (
    .A(FIFO_empty),
    .Y(_0520_)
  );
  NOR _1141_ (
    .A(FIFO_error),
    .B(_0520_),
    .Y(_0521_)
  );
  NAND _1142_ (
    .A(_0521_),
    .B(_0519_),
    .Y(_0522_)
  );
  NOT _1143_ (
    .A(\fsm_Control1.state [2]),
    .Y(_0523_)
  );
  NOR _1144_ (
    .A(\fsm_Control1.state [3]),
    .B(_0523_),
    .Y(_0524_)
  );
  NAND _1145_ (
    .A(_0524_),
    .B(_0515_),
    .Y(_0525_)
  );
  NAND _1146_ (
    .A(_0525_),
    .B(_0518_),
    .Y(_0527_)
  );
  NOT _1147_ (
    .A(\fsm_Control1.state [4]),
    .Y(_0528_)
  );
  NOR _1148_ (
    .A(\fsm_Control1.state [3]),
    .B(\fsm_Control1.state [2]),
    .Y(_0529_)
  );
  NAND _1149_ (
    .A(_0529_),
    .B(_0528_),
    .Y(_0530_)
  );
  NOT _1150_ (
    .A(_0530_),
    .Y(_0531_)
  );
  NOT _1151_ (
    .A(\fsm_Control1.state [0]),
    .Y(_0532_)
  );
  NOR _1152_ (
    .A(\fsm_Control1.state [1]),
    .B(_0532_),
    .Y(_0533_)
  );
  NAND _1153_ (
    .A(_0533_),
    .B(_0531_),
    .Y(_0534_)
  );
  NOT _1154_ (
    .A(_0529_),
    .Y(_0535_)
  );
  NAND _1155_ (
    .A(_0513_),
    .B(\fsm_Control1.state [4]),
    .Y(_0536_)
  );
  NOR _1156_ (
    .A(_0536_),
    .B(_0535_),
    .Y(_0537_)
  );
  NAND _1157_ (
    .A(\fsm_Control1.state [1]),
    .B(_0532_),
    .Y(_0538_)
  );
  NOR _1158_ (
    .A(_0538_),
    .B(_0530_),
    .Y(_0539_)
  );
  NOR _1159_ (
    .A(_0539_),
    .B(_0537_),
    .Y(_0540_)
  );
  NAND _1160_ (
    .A(_0540_),
    .B(_0534_),
    .Y(_0541_)
  );
  NOR _1161_ (
    .A(_0541_),
    .B(_0527_),
    .Y(_0542_)
  );
  NOT _1162_ (
    .A(active_out),
    .Y(_0543_)
  );
  NOR _1163_ (
    .A(_0543_),
    .B(_0031_),
    .Y(_0544_)
  );
  NAND _1164_ (
    .A(_0544_),
    .B(_0542_),
    .Y(_0545_)
  );
  NAND _1165_ (
    .A(_0545_),
    .B(_0522_),
    .Y(_0412_)
  );
  NOR _1166_ (
    .A(FIFO_error),
    .B(reset_L),
    .Y(_0546_)
  );
  NAND _1167_ (
    .A(_0546_),
    .B(_0537_),
    .Y(_0547_)
  );
  NAND _1168_ (
    .A(init),
    .B(reset_L),
    .Y(_0548_)
  );
  NAND _1169_ (
    .A(_0548_),
    .B(\fsm_Control1.nxt_state [0]),
    .Y(_0549_)
  );
  NOR _1170_ (
    .A(_0549_),
    .B(_0522_),
    .Y(_0550_)
  );
  NOR _1171_ (
    .A(_0550_),
    .B(_0542_),
    .Y(_0551_)
  );
  NAND _1172_ (
    .A(_0551_),
    .B(_0547_),
    .Y(_0414_)
  );
  NOT _1173_ (
    .A(_0522_),
    .Y(_0552_)
  );
  NOT _1174_ (
    .A(\fsm_Control1.nxt_state [1]),
    .Y(_0553_)
  );
  NOT _1175_ (
    .A(_0548_),
    .Y(_0554_)
  );
  NOR _1176_ (
    .A(_0554_),
    .B(_0553_),
    .Y(_0556_)
  );
  NAND _1177_ (
    .A(_0556_),
    .B(_0552_),
    .Y(_0557_)
  );
  NAND _1178_ (
    .A(_0557_),
    .B(_0534_),
    .Y(_0416_)
  );
  NOT _1179_ (
    .A(_0527_),
    .Y(_0558_)
  );
  NOR _1180_ (
    .A(_0558_),
    .B(FIFO_empty),
    .Y(_0559_)
  );
  NOT _1181_ (
    .A(_0539_),
    .Y(_0560_)
  );
  NAND _1182_ (
    .A(_0548_),
    .B(_0509_),
    .Y(_0561_)
  );
  NAND _1183_ (
    .A(_0561_),
    .B(_0519_),
    .Y(_0562_)
  );
  NAND _1184_ (
    .A(_0562_),
    .B(_0560_),
    .Y(_0563_)
  );
  NOR _1185_ (
    .A(_0563_),
    .B(_0559_),
    .Y(_0564_)
  );
  NOR _1186_ (
    .A(_0564_),
    .B(FIFO_error),
    .Y(_0418_)
  );
  NOT _1187_ (
    .A(_0525_),
    .Y(_0565_)
  );
  NAND _1188_ (
    .A(_0565_),
    .B(_0521_),
    .Y(_0566_)
  );
  NOR _1189_ (
    .A(_0554_),
    .B(_0511_),
    .Y(_0567_)
  );
  NAND _1190_ (
    .A(_0567_),
    .B(_0552_),
    .Y(_0568_)
  );
  NAND _1191_ (
    .A(_0568_),
    .B(_0566_),
    .Y(_0420_)
  );
  NAND _1192_ (
    .A(_0560_),
    .B(_0558_),
    .Y(_0569_)
  );
  NAND _1193_ (
    .A(_0569_),
    .B(FIFO_error),
    .Y(_0570_)
  );
  NOR _1194_ (
    .A(_0512_),
    .B(_0520_),
    .Y(_0571_)
  );
  NAND _1195_ (
    .A(_0571_),
    .B(_0548_),
    .Y(_0572_)
  );
  NOR _1196_ (
    .A(_0572_),
    .B(_0518_),
    .Y(_0573_)
  );
  NOT _1197_ (
    .A(_0537_),
    .Y(_0574_)
  );
  NOR _1198_ (
    .A(_0546_),
    .B(_0574_),
    .Y(_0575_)
  );
  NOR _1199_ (
    .A(_0575_),
    .B(_0573_),
    .Y(_0576_)
  );
  NAND _1200_ (
    .A(_0576_),
    .B(_0570_),
    .Y(_0422_)
  );
  NOT _1201_ (
    .A(idle_out),
    .Y(_0577_)
  );
  NOR _1202_ (
    .A(_0577_),
    .B(_0031_),
    .Y(_0578_)
  );
  NAND _1203_ (
    .A(_0578_),
    .B(_0542_),
    .Y(_0579_)
  );
  NOR _1204_ (
    .A(_0578_),
    .B(_0520_),
    .Y(_0580_)
  );
  NOR _1205_ (
    .A(_0580_),
    .B(FIFO_error),
    .Y(_0581_)
  );
  NAND _1206_ (
    .A(_0581_),
    .B(_0565_),
    .Y(_0583_)
  );
  NAND _1207_ (
    .A(_0583_),
    .B(_0579_),
    .Y(_0424_)
  );
  NAND _1208_ (
    .A(_0560_),
    .B(_0534_),
    .Y(_0584_)
  );
  NOT _1209_ (
    .A(error_out),
    .Y(_0585_)
  );
  NOR _1210_ (
    .A(_0585_),
    .B(_0031_),
    .Y(_0586_)
  );
  NOT _1211_ (
    .A(FIFO_error),
    .Y(_0587_)
  );
  NOR _1212_ (
    .A(_0574_),
    .B(_0587_),
    .Y(_0588_)
  );
  NOR _1213_ (
    .A(_0588_),
    .B(_0586_),
    .Y(_0589_)
  );
  NOR _1214_ (
    .A(_0589_),
    .B(_0584_),
    .Y(_0427_)
  );
  NOT _1215_ (
    .A(_0171_),
    .Y(_0590_)
  );
  NOT _1216_ (
    .A(_0253_),
    .Y(_0591_)
  );
  NAND _1217_ (
    .A(_0591_),
    .B(_0590_),
    .Y(_0437_)
  );
  NOR _1218_ (
    .A(\VC0Fifo.memoria.Ram[1] [0]),
    .B(_0325_),
    .Y(_0592_)
  );
  NOR _1219_ (
    .A(\VC0Fifo.memoria.Ram[0] [0]),
    .B(\VC0Fifo.memoria.iReadAddress [0]),
    .Y(_0593_)
  );
  NOR _1220_ (
    .A(_0593_),
    .B(_0592_),
    .Y(_0594_)
  );
  NOR _1221_ (
    .A(_0594_),
    .B(\VC0Fifo.memoria.iReadAddress [1]),
    .Y(_0595_)
  );
  NOT _1222_ (
    .A(\VC0Fifo.memoria.iReadEnable ),
    .Y(_0596_)
  );
  NOR _1223_ (
    .A(_0596_),
    .B(_0310_),
    .Y(_0597_)
  );
  NAND _1224_ (
    .A(\VC0Fifo.memoria.Ram[2] [0]),
    .B(_0325_),
    .Y(_0598_)
  );
  NOT _1225_ (
    .A(\VC0Fifo.memoria.Ram[3] [0]),
    .Y(_0599_)
  );
  NOR _1226_ (
    .A(_0599_),
    .B(_0325_),
    .Y(_0600_)
  );
  NOR _1227_ (
    .A(_0600_),
    .B(_0332_),
    .Y(_0601_)
  );
  NAND _1228_ (
    .A(_0601_),
    .B(_0598_),
    .Y(_0602_)
  );
  NAND _1229_ (
    .A(_0602_),
    .B(_0597_),
    .Y(_0603_)
  );
  NOR _1230_ (
    .A(_0603_),
    .B(_0595_),
    .Y(_0604_)
  );
  NOR _1231_ (
    .A(\VC1Fifo.memoria.Ram[0] [0]),
    .B(\VC1Fifo.memoria.iReadAddress [0]),
    .Y(_0605_)
  );
  NOR _1232_ (
    .A(\VC1Fifo.memoria.Ram[1] [0]),
    .B(_0407_),
    .Y(_0606_)
  );
  NOR _1233_ (
    .A(_0606_),
    .B(_0605_),
    .Y(_0607_)
  );
  NOR _1234_ (
    .A(_0607_),
    .B(\VC1Fifo.memoria.iReadAddress [1]),
    .Y(_0608_)
  );
  NAND _1235_ (
    .A(\VC1Fifo.memoria.Ram[3] [0]),
    .B(\VC1Fifo.memoria.iReadAddress [0]),
    .Y(_0609_)
  );
  NOT _1236_ (
    .A(\VC1Fifo.memoria.Ram[2] [0]),
    .Y(_0611_)
  );
  NOR _1237_ (
    .A(_0611_),
    .B(\VC1Fifo.memoria.iReadAddress [0]),
    .Y(_0612_)
  );
  NOR _1238_ (
    .A(_0612_),
    .B(_0413_),
    .Y(_0613_)
  );
  NAND _1239_ (
    .A(_0613_),
    .B(_0609_),
    .Y(_0614_)
  );
  NAND _1240_ (
    .A(\VC1Fifo.memoria.iReadEnable ),
    .B(_0310_),
    .Y(_0615_)
  );
  NOR _1241_ (
    .A(_0615_),
    .B(_0037_),
    .Y(_0616_)
  );
  NAND _1242_ (
    .A(_0616_),
    .B(_0614_),
    .Y(_0617_)
  );
  NOR _1243_ (
    .A(_0617_),
    .B(_0608_),
    .Y(_0618_)
  );
  NOR _1244_ (
    .A(_0618_),
    .B(_0604_),
    .Y(_0619_)
  );
  NOR _1245_ (
    .A(_0619_),
    .B(_0031_),
    .Y(_0441_)
  );
  DFF _1246_ (
    .C(clk),
    .D(_0001_),
    .Q(FIFO_error)
  );
  DFF _1247_ (
    .C(clk),
    .D(_0000_),
    .Q(FIFO_empty)
  );
  DFF _1248_ (
    .C(clk),
    .D(_0002_),
    .Q(\VC0Fifo.pop )
  );
  DFF _1249_ (
    .C(clk),
    .D(_0003_),
    .Q(\VC1Fifo.pop )
  );
  DFF _1250_ (
    .C(clk),
    .D(_0209_),
    .Q(\D0Fifo.memoria.iReadAddress [0])
  );
  DFF _1251_ (
    .C(clk),
    .D(_0226_),
    .Q(\D0Fifo.memoria.iReadAddress [1])
  );
  DFF _1252_ (
    .C(clk),
    .D(_0174_),
    .Q(\D0Fifo.memoria.iWriteAddress [0])
  );
  DFF _1253_ (
    .C(clk),
    .D(_0191_),
    .Q(\D0Fifo.memoria.iWriteAddress [1])
  );
  DFF _1254_ (
    .C(clk),
    .D(_0439_),
    .Q(\D0Fifo.memoria.iWriteEnable )
  );
  DFF _1255_ (
    .C(clk),
    .D(_0328_),
    .Q(\D0Fifo.Fifo_Data_in_int [0])
  );
  DFF _1256_ (
    .C(clk),
    .D(_0346_),
    .Q(\D0Fifo.Fifo_Data_in_int [1])
  );
  DFF _1257_ (
    .C(clk),
    .D(_0362_),
    .Q(\D0Fifo.Fifo_Data_in_int [2])
  );
  DFF _1258_ (
    .C(clk),
    .D(_0379_),
    .Q(\D0Fifo.Fifo_Data_in_int [3])
  );
  DFF _1259_ (
    .C(clk),
    .D(_0403_),
    .Q(\D0Fifo.Fifo_Data_in_int [4])
  );
  DFF _1260_ (
    .C(clk),
    .D(_0429_),
    .Q(\D0Fifo.Fifo_Data_in_int [5])
  );
  DFF _1261_ (
    .C(clk),
    .D(_0473_),
    .Q(\D0Fifo.memoria.Ram[0] [0])
  );
  DFF _1262_ (
    .C(clk),
    .D(_0501_),
    .Q(\D0Fifo.memoria.Ram[0] [1])
  );
  DFF _1263_ (
    .C(clk),
    .D(_0526_),
    .Q(\D0Fifo.memoria.Ram[0] [2])
  );
  DFF _1264_ (
    .C(clk),
    .D(_0555_),
    .Q(\D0Fifo.memoria.Ram[0] [3])
  );
  DFF _1265_ (
    .C(clk),
    .D(_0582_),
    .Q(\D0Fifo.memoria.Ram[0] [4])
  );
  DFF _1266_ (
    .C(clk),
    .D(_0610_),
    .Q(\D0Fifo.memoria.Ram[0] [5])
  );
  DFF _1267_ (
    .C(clk),
    .D(_0016_),
    .Q(\D0Fifo.memoria.Ram[1] [0])
  );
  DFF _1268_ (
    .C(clk),
    .D(_0017_),
    .Q(\D0Fifo.memoria.Ram[1] [1])
  );
  DFF _1269_ (
    .C(clk),
    .D(_0018_),
    .Q(\D0Fifo.memoria.Ram[1] [2])
  );
  DFF _1270_ (
    .C(clk),
    .D(_0019_),
    .Q(\D0Fifo.memoria.Ram[1] [3])
  );
  DFF _1271_ (
    .C(clk),
    .D(_0020_),
    .Q(\D0Fifo.memoria.Ram[1] [4])
  );
  DFF _1272_ (
    .C(clk),
    .D(_0021_),
    .Q(\D0Fifo.memoria.Ram[1] [5])
  );
  DFF _1273_ (
    .C(clk),
    .D(_0004_),
    .Q(\D0Fifo.memoria.Ram[3] [0])
  );
  DFF _1274_ (
    .C(clk),
    .D(_0005_),
    .Q(\D0Fifo.memoria.Ram[3] [1])
  );
  DFF _1275_ (
    .C(clk),
    .D(_0006_),
    .Q(\D0Fifo.memoria.Ram[3] [2])
  );
  DFF _1276_ (
    .C(clk),
    .D(_0007_),
    .Q(\D0Fifo.memoria.Ram[3] [3])
  );
  DFF _1277_ (
    .C(clk),
    .D(_0008_),
    .Q(\D0Fifo.memoria.Ram[3] [4])
  );
  DFF _1278_ (
    .C(clk),
    .D(_0009_),
    .Q(\D0Fifo.memoria.Ram[3] [5])
  );
  DFF _1279_ (
    .C(clk),
    .D(_0010_),
    .Q(\D0Fifo.memoria.Ram[2] [0])
  );
  DFF _1280_ (
    .C(clk),
    .D(_0011_),
    .Q(\D0Fifo.memoria.Ram[2] [1])
  );
  DFF _1281_ (
    .C(clk),
    .D(_0012_),
    .Q(\D0Fifo.memoria.Ram[2] [2])
  );
  DFF _1282_ (
    .C(clk),
    .D(_0013_),
    .Q(\D0Fifo.memoria.Ram[2] [3])
  );
  DFF _1283_ (
    .C(clk),
    .D(_0014_),
    .Q(\D0Fifo.memoria.Ram[2] [4])
  );
  DFF _1284_ (
    .C(clk),
    .D(_0015_),
    .Q(\D0Fifo.memoria.Ram[2] [5])
  );
  DFF _1285_ (
    .C(clk),
    .D(_0022_),
    .Q(\D1Fifo.memoria.iReadAddress [0])
  );
  DFF _1286_ (
    .C(clk),
    .D(_0023_),
    .Q(\D1Fifo.memoria.iReadAddress [1])
  );
  DFF _1287_ (
    .C(clk),
    .D(1'b0),
    .Q(\D0Fifo.memoria.iReadEnable )
  );
  DFF _1288_ (
    .C(clk),
    .D(_0025_),
    .Q(\D0Fifo.Fifo_Data_in [0])
  );
  DFF _1289_ (
    .C(clk),
    .D(_0026_),
    .Q(\D0Fifo.Fifo_Data_in [1])
  );
  DFF _1290_ (
    .C(clk),
    .D(_0027_),
    .Q(\D0Fifo.Fifo_Data_in [2])
  );
  DFF _1291_ (
    .C(clk),
    .D(_0028_),
    .Q(\D0Fifo.Fifo_Data_in [3])
  );
  DFF _1292_ (
    .C(clk),
    .D(_0029_),
    .Q(\D0Fifo.Fifo_Data_in [4])
  );
  DFF _1293_ (
    .C(clk),
    .D(_0030_),
    .Q(\D0Fifo.Fifo_Data_in [5])
  );
  DFF _1294_ (
    .C(clk),
    .D(_0024_),
    .Q(\D0Fifo.push )
  );
  DFF _1295_ (
    .C(clk),
    .D(_0052_),
    .Q(\MainFifo.memoria.iWriteAddress [0])
  );
  DFF _1296_ (
    .C(clk),
    .D(_0053_),
    .Q(\MainFifo.memoria.iWriteAddress [1])
  );
  DFF _1297_ (
    .C(clk),
    .D(_0040_),
    .Q(\MainFifo.memoria.iReadAddress [0])
  );
  DFF _1298_ (
    .C(clk),
    .D(_0041_),
    .Q(\MainFifo.memoria.iReadAddress [1])
  );
  DFF _1299_ (
    .C(clk),
    .D(_0060_),
    .Q(\MainFifo.memoria.iWriteEnable )
  );
  DFF _1300_ (
    .C(clk),
    .D(_0059_),
    .Q(\MainFifo.memoria.iReadEnable )
  );
  DFF _1301_ (
    .C(clk),
    .D(_0055_),
    .Q(\MainFifo.Fifo_Data_in_int [0])
  );
  DFF _1302_ (
    .C(clk),
    .D(_0057_),
    .Q(\MainFifo.Fifo_Data_in_int [5])
  );
  DFF _1303_ (
    .C(clk),
    .D(_0063_),
    .Q(\MainFifo.memoria.Ram[0] [0])
  );
  DFF _1304_ (
    .C(clk),
    .D(_0066_),
    .Q(\MainFifo.memoria.Ram[0] [5])
  );
  DFF _1305_ (
    .C(clk),
    .D(_0090_),
    .Q(\MainFifo.memoria.Ram[1] [0])
  );
  DFF _1306_ (
    .C(clk),
    .D(_0092_),
    .Q(\MainFifo.memoria.Ram[1] [5])
  );
  DFF _1307_ (
    .C(clk),
    .D(_0082_),
    .Q(\MainFifo.memoria.Ram[3] [0])
  );
  DFF _1308_ (
    .C(clk),
    .D(_0083_),
    .Q(\MainFifo.memoria.Ram[3] [5])
  );
  DFF _1309_ (
    .C(clk),
    .D(_0086_),
    .Q(\MainFifo.memoria.Ram[2] [0])
  );
  DFF _1310_ (
    .C(clk),
    .D(_0087_),
    .Q(\MainFifo.memoria.Ram[2] [5])
  );
  DFF _1311_ (
    .C(clk),
    .D(_0154_),
    .Q(\VC0Fifo.memoria.iWriteAddress [0])
  );
  DFF _1312_ (
    .C(clk),
    .D(_0156_),
    .Q(\VC0Fifo.memoria.iWriteAddress [1])
  );
  DFF _1313_ (
    .C(clk),
    .D(_0141_),
    .Q(\VC0Fifo.memoria.iReadAddress [0])
  );
  DFF _1314_ (
    .C(clk),
    .D(_0143_),
    .Q(\VC0Fifo.memoria.iReadAddress [1])
  );
  DFF _1315_ (
    .C(clk),
    .D(_0126_),
    .Q(\VC0Fifo.num_mem [0])
  );
  DFF _1316_ (
    .C(clk),
    .D(_0128_),
    .Q(\VC0Fifo.num_mem [1])
  );
  DFF _1317_ (
    .C(clk),
    .D(_0129_),
    .Q(\VC0Fifo.num_mem [2])
  );
  DFF _1318_ (
    .C(clk),
    .D(_0166_),
    .Q(Fifo_Empty_VC0)
  );
  DFF _1319_ (
    .C(clk),
    .D(_0173_),
    .Q(\VC0Fifo.memoria.iWriteEnable )
  );
  DFF _1320_ (
    .C(clk),
    .D(_0171_),
    .Q(\VC0Fifo.memoria.iReadEnable )
  );
  DFF _1321_ (
    .C(clk),
    .D(_0169_),
    .Q(\VC0Fifo.Fifo_Data_in_int [0])
  );
  DFF _1322_ (
    .C(clk),
    .D(_0180_),
    .Q(\VC0Fifo.memoria.Ram[0] [0])
  );
  DFF _1323_ (
    .C(clk),
    .D(_0197_),
    .Q(\VC0Fifo.memoria.Ram[1] [0])
  );
  DFF _1324_ (
    .C(clk),
    .D(_0192_),
    .Q(\VC0Fifo.memoria.Ram[3] [0])
  );
  DFF _1325_ (
    .C(clk),
    .D(_0194_),
    .Q(\VC0Fifo.memoria.Ram[2] [0])
  );
  DFF _1326_ (
    .C(clk),
    .D(_0237_),
    .Q(\VC1Fifo.memoria.iWriteAddress [0])
  );
  DFF _1327_ (
    .C(clk),
    .D(_0238_),
    .Q(\VC1Fifo.memoria.iWriteAddress [1])
  );
  DFF _1328_ (
    .C(clk),
    .D(_0230_),
    .Q(\VC1Fifo.memoria.iReadAddress [0])
  );
  DFF _1329_ (
    .C(clk),
    .D(_0231_),
    .Q(\VC1Fifo.memoria.iReadAddress [1])
  );
  DFF _1330_ (
    .C(clk),
    .D(_0222_),
    .Q(\VC1Fifo.num_mem [0])
  );
  DFF _1331_ (
    .C(clk),
    .D(_0224_),
    .Q(\VC1Fifo.num_mem [1])
  );
  DFF _1332_ (
    .C(clk),
    .D(_0227_),
    .Q(\VC1Fifo.num_mem [2])
  );
  DFF _1333_ (
    .C(clk),
    .D(_0248_),
    .Q(Fifo_Empty_VC1)
  );
  DFF _1334_ (
    .C(clk),
    .D(_0254_),
    .Q(\VC1Fifo.memoria.iWriteEnable )
  );
  DFF _1335_ (
    .C(clk),
    .D(_0253_),
    .Q(\VC1Fifo.memoria.iReadEnable )
  );
  DFF _1336_ (
    .C(clk),
    .D(_0251_),
    .Q(\VC1Fifo.Fifo_Data_in_int [0])
  );
  DFF _1337_ (
    .C(clk),
    .D(_0261_),
    .Q(\VC1Fifo.memoria.Ram[0] [0])
  );
  DFF _1338_ (
    .C(clk),
    .D(_0277_),
    .Q(\VC1Fifo.memoria.Ram[1] [0])
  );
  DFF _1339_ (
    .C(clk),
    .D(_0271_),
    .Q(\VC1Fifo.memoria.Ram[3] [0])
  );
  DFF _1340_ (
    .C(clk),
    .D(_0274_),
    .Q(\VC1Fifo.memoria.Ram[2] [0])
  );
  DFF _1341_ (
    .C(clk),
    .D(_0296_),
    .Q(\VC0Fifo.Fifo_Data_in [0])
  );
  DFF _1342_ (
    .C(clk),
    .D(_0292_),
    .Q(\VC1Fifo.Fifo_Data_in [0])
  );
  DFF _1343_ (
    .C(clk),
    .D(_0288_),
    .Q(\VC0Fifo.push )
  );
  DFF _1344_ (
    .C(clk),
    .D(_0285_),
    .Q(\VC1Fifo.push )
  );
  DFF _1345_ (
    .C(clk),
    .D(_0412_),
    .Q(active_out)
  );
  DFF _1346_ (
    .C(clk),
    .D(_0424_),
    .Q(idle_out)
  );
  DFF _1347_ (
    .C(clk),
    .D(_0427_),
    .Q(error_out)
  );
  DFF _1348_ (
    .C(clk),
    .D(_0392_),
    .Q(\fsm_Control1.state [0])
  );
  DFF _1349_ (
    .C(clk),
    .D(_0393_),
    .Q(\fsm_Control1.state [1])
  );
  DFF _1350_ (
    .C(clk),
    .D(_0395_),
    .Q(\fsm_Control1.state [2])
  );
  DFF _1351_ (
    .C(clk),
    .D(_0397_),
    .Q(\fsm_Control1.state [3])
  );
  DFF _1352_ (
    .C(clk),
    .D(_0400_),
    .Q(\fsm_Control1.state [4])
  );
  DFF _1353_ (
    .C(clk),
    .D(_0414_),
    .Q(\fsm_Control1.nxt_state [0])
  );
  DFF _1354_ (
    .C(clk),
    .D(_0416_),
    .Q(\fsm_Control1.nxt_state [1])
  );
  DFF _1355_ (
    .C(clk),
    .D(_0418_),
    .Q(\fsm_Control1.nxt_state [2])
  );
  DFF _1356_ (
    .C(clk),
    .D(_0420_),
    .Q(\fsm_Control1.nxt_state [3])
  );
  DFF _1357_ (
    .C(clk),
    .D(_0422_),
    .Q(\fsm_Control1.nxt_state [4])
  );
  DFF _1358_ (
    .C(clk),
    .D(_0441_),
    .Q(\Demux_D0_D1.data_in [0])
  );
  DFF _1359_ (
    .C(clk),
    .D(_0437_),
    .Q(\Demux_D0_D1.valid_in )
  );
  assign Pausa_MF = 1'b0;
  assign data_out1 = 6'b000000;
endmodule
