/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module demuxEstructural(clk, reset_L, valid_in, data_in, dataout0, dataout1, valid_0, valid_1);
  wire [5:0] _000_;
  wire [5:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  input clk;
  input [5:0] data_in;
  output [5:0] dataout0;
  output [5:0] dataout1;
  input reset_L;
  output valid_0;
  output valid_1;
  input valid_in;
  NOT _054_ (
    .A(data_in[5]),
    .Y(_004_)
  );
  NAND _055_ (
    .A(valid_in),
    .B(reset_L),
    .Y(_005_)
  );
  NOR _056_ (
    .A(_005_),
    .B(_004_),
    .Y(_003_)
  );
  NOR _057_ (
    .A(_005_),
    .B(data_in[5]),
    .Y(_002_)
  );
  NOR _058_ (
    .A(valid_1),
    .B(valid_in),
    .Y(_006_)
  );
  NOR _059_ (
    .A(_006_),
    .B(_003_),
    .Y(_007_)
  );
  NOT _060_ (
    .A(reset_L),
    .Y(_008_)
  );
  NOT _061_ (
    .A(dataout1[0]),
    .Y(_009_)
  );
  NOR _062_ (
    .A(_009_),
    .B(_008_),
    .Y(_010_)
  );
  NAND _063_ (
    .A(_010_),
    .B(_007_),
    .Y(_011_)
  );
  NAND _064_ (
    .A(_003_),
    .B(data_in[0]),
    .Y(_012_)
  );
  NAND _065_ (
    .A(_012_),
    .B(_011_),
    .Y(_001_[0])
  );
  NOT _066_ (
    .A(dataout1[1]),
    .Y(_013_)
  );
  NOR _067_ (
    .A(_013_),
    .B(_008_),
    .Y(_014_)
  );
  NAND _068_ (
    .A(_014_),
    .B(_007_),
    .Y(_015_)
  );
  NAND _069_ (
    .A(_003_),
    .B(data_in[1]),
    .Y(_016_)
  );
  NAND _070_ (
    .A(_016_),
    .B(_015_),
    .Y(_001_[1])
  );
  NOT _071_ (
    .A(dataout1[2]),
    .Y(_017_)
  );
  NOR _072_ (
    .A(_017_),
    .B(_008_),
    .Y(_018_)
  );
  NAND _073_ (
    .A(_018_),
    .B(_007_),
    .Y(_019_)
  );
  NAND _074_ (
    .A(_003_),
    .B(data_in[2]),
    .Y(_020_)
  );
  NAND _075_ (
    .A(_020_),
    .B(_019_),
    .Y(_001_[2])
  );
  NOT _076_ (
    .A(dataout1[3]),
    .Y(_021_)
  );
  NOR _077_ (
    .A(_021_),
    .B(_008_),
    .Y(_022_)
  );
  NAND _078_ (
    .A(_022_),
    .B(_007_),
    .Y(_023_)
  );
  NAND _079_ (
    .A(_003_),
    .B(data_in[3]),
    .Y(_024_)
  );
  NAND _080_ (
    .A(_024_),
    .B(_023_),
    .Y(_001_[3])
  );
  NOT _081_ (
    .A(dataout1[4]),
    .Y(_025_)
  );
  NOR _082_ (
    .A(_025_),
    .B(_008_),
    .Y(_026_)
  );
  NAND _083_ (
    .A(_026_),
    .B(_007_),
    .Y(_027_)
  );
  NAND _084_ (
    .A(_003_),
    .B(data_in[4]),
    .Y(_028_)
  );
  NAND _085_ (
    .A(_028_),
    .B(_027_),
    .Y(_001_[4])
  );
  NOT _086_ (
    .A(valid_in),
    .Y(_029_)
  );
  NOR _087_ (
    .A(_029_),
    .B(_008_),
    .Y(_030_)
  );
  NAND _088_ (
    .A(_030_),
    .B(data_in[5]),
    .Y(_031_)
  );
  NOT _089_ (
    .A(_006_),
    .Y(_032_)
  );
  NOT _090_ (
    .A(dataout1[5]),
    .Y(_033_)
  );
  NOR _091_ (
    .A(_033_),
    .B(_008_),
    .Y(_034_)
  );
  NAND _092_ (
    .A(_034_),
    .B(_032_),
    .Y(_035_)
  );
  NAND _093_ (
    .A(_035_),
    .B(_031_),
    .Y(_001_[5])
  );
  NAND _094_ (
    .A(_002_),
    .B(data_in[0]),
    .Y(_036_)
  );
  NOR _095_ (
    .A(valid_in),
    .B(_008_),
    .Y(_037_)
  );
  NAND _096_ (
    .A(_037_),
    .B(valid_0),
    .Y(_038_)
  );
  NAND _097_ (
    .A(_038_),
    .B(_031_),
    .Y(_039_)
  );
  NAND _098_ (
    .A(_039_),
    .B(dataout0[0]),
    .Y(_040_)
  );
  NAND _099_ (
    .A(_040_),
    .B(_036_),
    .Y(_000_[0])
  );
  NAND _100_ (
    .A(_002_),
    .B(data_in[1]),
    .Y(_041_)
  );
  NAND _101_ (
    .A(_039_),
    .B(dataout0[1]),
    .Y(_042_)
  );
  NAND _102_ (
    .A(_042_),
    .B(_041_),
    .Y(_000_[1])
  );
  NAND _103_ (
    .A(_002_),
    .B(data_in[2]),
    .Y(_043_)
  );
  NAND _104_ (
    .A(_039_),
    .B(dataout0[2]),
    .Y(_044_)
  );
  NAND _105_ (
    .A(_044_),
    .B(_043_),
    .Y(_000_[2])
  );
  NAND _106_ (
    .A(_002_),
    .B(data_in[3]),
    .Y(_045_)
  );
  NAND _107_ (
    .A(_039_),
    .B(dataout0[3]),
    .Y(_046_)
  );
  NAND _108_ (
    .A(_046_),
    .B(_045_),
    .Y(_000_[3])
  );
  NAND _109_ (
    .A(_002_),
    .B(data_in[4]),
    .Y(_047_)
  );
  NAND _110_ (
    .A(_039_),
    .B(dataout0[4]),
    .Y(_048_)
  );
  NAND _111_ (
    .A(_048_),
    .B(_047_),
    .Y(_000_[4])
  );
  NOT _112_ (
    .A(dataout0[5]),
    .Y(_049_)
  );
  NOT _113_ (
    .A(valid_0),
    .Y(_050_)
  );
  NAND _114_ (
    .A(_029_),
    .B(reset_L),
    .Y(_051_)
  );
  NOR _115_ (
    .A(_051_),
    .B(_050_),
    .Y(_052_)
  );
  NOR _116_ (
    .A(_052_),
    .B(_003_),
    .Y(_053_)
  );
  NOR _117_ (
    .A(_053_),
    .B(_049_),
    .Y(_000_[5])
  );
  DFF _118_ (
    .C(clk),
    .D(_000_[0]),
    .Q(dataout0[0])
  );
  DFF _119_ (
    .C(clk),
    .D(_000_[1]),
    .Q(dataout0[1])
  );
  DFF _120_ (
    .C(clk),
    .D(_000_[2]),
    .Q(dataout0[2])
  );
  DFF _121_ (
    .C(clk),
    .D(_000_[3]),
    .Q(dataout0[3])
  );
  DFF _122_ (
    .C(clk),
    .D(_000_[4]),
    .Q(dataout0[4])
  );
  DFF _123_ (
    .C(clk),
    .D(_000_[5]),
    .Q(dataout0[5])
  );
  DFF _124_ (
    .C(clk),
    .D(_001_[0]),
    .Q(dataout1[0])
  );
  DFF _125_ (
    .C(clk),
    .D(_001_[1]),
    .Q(dataout1[1])
  );
  DFF _126_ (
    .C(clk),
    .D(_001_[2]),
    .Q(dataout1[2])
  );
  DFF _127_ (
    .C(clk),
    .D(_001_[3]),
    .Q(dataout1[3])
  );
  DFF _128_ (
    .C(clk),
    .D(_001_[4]),
    .Q(dataout1[4])
  );
  DFF _129_ (
    .C(clk),
    .D(_001_[5]),
    .Q(dataout1[5])
  );
  DFF _130_ (
    .C(clk),
    .D(_002_),
    .Q(valid_0)
  );
  DFF _131_ (
    .C(clk),
    .D(_003_),
    .Q(valid_1)
  );
endmodule
