/* Generated by Yosys 0.8 (git sha1 5706e90) */

module \$paramod\dual_port_memory_Synth\DATA_WIDTH=6\ADDR_WIDTH=2\MEM_SIZE=3 (Clock, iWriteEnable, iReadEnable, iReadAddress, iWriteAddress, iDataIn, oDataOut);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  input Clock;
  wire [5:0] \Ram[0] ;
  wire [5:0] \Ram[1] ;
  wire [5:0] \Ram[2] ;
  wire [5:0] \Ram[3] ;
  input [5:0] iDataIn;
  input [1:0] iReadAddress;
  input iReadEnable;
  input [1:0] iWriteAddress;
  input iWriteEnable;
  output [5:0] oDataOut;
  NOT _159_ (
    .A(\Ram[3] [0]),
    .Y(_129_)
  );
  NOT _160_ (
    .A(\Ram[3] [1]),
    .Y(_130_)
  );
  NOT _161_ (
    .A(\Ram[3] [2]),
    .Y(_131_)
  );
  NOT _162_ (
    .A(\Ram[3] [3]),
    .Y(_132_)
  );
  NOT _163_ (
    .A(\Ram[3] [4]),
    .Y(_133_)
  );
  NOT _164_ (
    .A(\Ram[3] [5]),
    .Y(_134_)
  );
  NOT _165_ (
    .A(\Ram[0] [0]),
    .Y(_135_)
  );
  NOT _166_ (
    .A(\Ram[0] [1]),
    .Y(_136_)
  );
  NOT _167_ (
    .A(\Ram[0] [2]),
    .Y(_137_)
  );
  NOT _168_ (
    .A(\Ram[0] [3]),
    .Y(_138_)
  );
  NOT _169_ (
    .A(\Ram[0] [4]),
    .Y(_139_)
  );
  NOT _170_ (
    .A(\Ram[0] [5]),
    .Y(_140_)
  );
  NOT _171_ (
    .A(iReadEnable),
    .Y(_141_)
  );
  NOT _172_ (
    .A(iWriteEnable),
    .Y(_142_)
  );
  NOT _173_ (
    .A(iWriteAddress[1]),
    .Y(_143_)
  );
  NAND _174_ (
    .A(iWriteEnable),
    .B(iWriteAddress[0]),
    .Y(_144_)
  );
  NOT _175_ (
    .A(_144_),
    .Y(_145_)
  );
  NOR _176_ (
    .A(_143_),
    .B(_144_),
    .Y(_146_)
  );
  NAND _177_ (
    .A(iWriteAddress[1]),
    .B(_145_),
    .Y(_147_)
  );
  NAND _178_ (
    .A(iDataIn[0]),
    .B(_146_),
    .Y(_148_)
  );
  NAND _179_ (
    .A(\Ram[3] [0]),
    .B(_147_),
    .Y(_149_)
  );
  NAND _180_ (
    .A(_148_),
    .B(_149_),
    .Y(_114_)
  );
  NAND _181_ (
    .A(iDataIn[1]),
    .B(_146_),
    .Y(_150_)
  );
  NAND _182_ (
    .A(\Ram[3] [1]),
    .B(_147_),
    .Y(_152_)
  );
  NAND _183_ (
    .A(_150_),
    .B(_152_),
    .Y(_128_)
  );
  NAND _184_ (
    .A(iDataIn[2]),
    .B(_146_),
    .Y(_153_)
  );
  NAND _185_ (
    .A(\Ram[3] [2]),
    .B(_147_),
    .Y(_154_)
  );
  NAND _186_ (
    .A(_153_),
    .B(_154_),
    .Y(_151_)
  );
  NAND _187_ (
    .A(iDataIn[3]),
    .B(_146_),
    .Y(_155_)
  );
  NAND _188_ (
    .A(\Ram[3] [3]),
    .B(_147_),
    .Y(_156_)
  );
  NAND _189_ (
    .A(_155_),
    .B(_156_),
    .Y(_014_)
  );
  NAND _190_ (
    .A(iDataIn[4]),
    .B(_146_),
    .Y(_157_)
  );
  NAND _191_ (
    .A(\Ram[3] [4]),
    .B(_147_),
    .Y(_158_)
  );
  NAND _192_ (
    .A(_157_),
    .B(_158_),
    .Y(_037_)
  );
  NAND _193_ (
    .A(iDataIn[5]),
    .B(_146_),
    .Y(_000_)
  );
  NAND _194_ (
    .A(\Ram[3] [5]),
    .B(_147_),
    .Y(_001_)
  );
  NAND _195_ (
    .A(_000_),
    .B(_001_),
    .Y(_061_)
  );
  NOR _196_ (
    .A(_142_),
    .B(iWriteAddress[0]),
    .Y(_002_)
  );
  NOT _197_ (
    .A(_002_),
    .Y(_003_)
  );
  NOR _198_ (
    .A(_143_),
    .B(_003_),
    .Y(_004_)
  );
  NAND _199_ (
    .A(iWriteAddress[1]),
    .B(_002_),
    .Y(_005_)
  );
  NAND _200_ (
    .A(iDataIn[0]),
    .B(_004_),
    .Y(_006_)
  );
  NAND _201_ (
    .A(\Ram[2] [0]),
    .B(_005_),
    .Y(_007_)
  );
  NAND _202_ (
    .A(_006_),
    .B(_007_),
    .Y(_089_)
  );
  NAND _203_ (
    .A(iDataIn[1]),
    .B(_004_),
    .Y(_008_)
  );
  NAND _204_ (
    .A(\Ram[2] [1]),
    .B(_005_),
    .Y(_009_)
  );
  NAND _205_ (
    .A(_008_),
    .B(_009_),
    .Y(_109_)
  );
  NAND _206_ (
    .A(iDataIn[2]),
    .B(_004_),
    .Y(_010_)
  );
  NAND _207_ (
    .A(\Ram[2] [2]),
    .B(_005_),
    .Y(_011_)
  );
  NAND _208_ (
    .A(_010_),
    .B(_011_),
    .Y(_111_)
  );
  NAND _209_ (
    .A(iDataIn[3]),
    .B(_004_),
    .Y(_012_)
  );
  NAND _210_ (
    .A(\Ram[2] [3]),
    .B(_005_),
    .Y(_013_)
  );
  NAND _211_ (
    .A(_012_),
    .B(_013_),
    .Y(_112_)
  );
  NAND _212_ (
    .A(iDataIn[4]),
    .B(_004_),
    .Y(_015_)
  );
  NAND _213_ (
    .A(\Ram[2] [4]),
    .B(_005_),
    .Y(_016_)
  );
  NAND _214_ (
    .A(_015_),
    .B(_016_),
    .Y(_113_)
  );
  NAND _215_ (
    .A(iDataIn[5]),
    .B(_004_),
    .Y(_017_)
  );
  NAND _216_ (
    .A(\Ram[2] [5]),
    .B(_005_),
    .Y(_018_)
  );
  NAND _217_ (
    .A(_017_),
    .B(_018_),
    .Y(_115_)
  );
  NOR _218_ (
    .A(iWriteAddress[1]),
    .B(_144_),
    .Y(_019_)
  );
  NAND _219_ (
    .A(_143_),
    .B(_145_),
    .Y(_020_)
  );
  NAND _220_ (
    .A(iDataIn[0]),
    .B(_019_),
    .Y(_021_)
  );
  NAND _221_ (
    .A(\Ram[1] [0]),
    .B(_020_),
    .Y(_022_)
  );
  NAND _222_ (
    .A(_021_),
    .B(_022_),
    .Y(_116_)
  );
  NAND _223_ (
    .A(iDataIn[1]),
    .B(_019_),
    .Y(_023_)
  );
  NAND _224_ (
    .A(\Ram[1] [1]),
    .B(_020_),
    .Y(_024_)
  );
  NAND _225_ (
    .A(_023_),
    .B(_024_),
    .Y(_117_)
  );
  NAND _226_ (
    .A(iDataIn[2]),
    .B(_019_),
    .Y(_025_)
  );
  NAND _227_ (
    .A(\Ram[1] [2]),
    .B(_020_),
    .Y(_026_)
  );
  NAND _228_ (
    .A(_025_),
    .B(_026_),
    .Y(_118_)
  );
  NAND _229_ (
    .A(iDataIn[3]),
    .B(_019_),
    .Y(_027_)
  );
  NAND _230_ (
    .A(\Ram[1] [3]),
    .B(_020_),
    .Y(_028_)
  );
  NAND _231_ (
    .A(_027_),
    .B(_028_),
    .Y(_119_)
  );
  NAND _232_ (
    .A(iDataIn[4]),
    .B(_019_),
    .Y(_029_)
  );
  NAND _233_ (
    .A(\Ram[1] [4]),
    .B(_020_),
    .Y(_030_)
  );
  NAND _234_ (
    .A(_029_),
    .B(_030_),
    .Y(_120_)
  );
  NAND _235_ (
    .A(iDataIn[5]),
    .B(_019_),
    .Y(_031_)
  );
  NAND _236_ (
    .A(\Ram[1] [5]),
    .B(_020_),
    .Y(_032_)
  );
  NAND _237_ (
    .A(_031_),
    .B(_032_),
    .Y(_121_)
  );
  NOR _238_ (
    .A(iWriteAddress[1]),
    .B(_003_),
    .Y(_033_)
  );
  NAND _239_ (
    .A(_143_),
    .B(_002_),
    .Y(_034_)
  );
  NAND _240_ (
    .A(iDataIn[0]),
    .B(_033_),
    .Y(_035_)
  );
  NAND _241_ (
    .A(\Ram[0] [0]),
    .B(_034_),
    .Y(_036_)
  );
  NAND _242_ (
    .A(_035_),
    .B(_036_),
    .Y(_122_)
  );
  NAND _243_ (
    .A(iDataIn[1]),
    .B(_033_),
    .Y(_038_)
  );
  NAND _244_ (
    .A(\Ram[0] [1]),
    .B(_034_),
    .Y(_039_)
  );
  NAND _245_ (
    .A(_038_),
    .B(_039_),
    .Y(_123_)
  );
  NAND _246_ (
    .A(iDataIn[2]),
    .B(_033_),
    .Y(_040_)
  );
  NAND _247_ (
    .A(\Ram[0] [2]),
    .B(_034_),
    .Y(_041_)
  );
  NAND _248_ (
    .A(_040_),
    .B(_041_),
    .Y(_124_)
  );
  NAND _249_ (
    .A(iDataIn[3]),
    .B(_033_),
    .Y(_042_)
  );
  NAND _250_ (
    .A(\Ram[0] [3]),
    .B(_034_),
    .Y(_043_)
  );
  NAND _251_ (
    .A(_042_),
    .B(_043_),
    .Y(_125_)
  );
  NAND _252_ (
    .A(iDataIn[4]),
    .B(_033_),
    .Y(_044_)
  );
  NAND _253_ (
    .A(\Ram[0] [4]),
    .B(_034_),
    .Y(_045_)
  );
  NAND _254_ (
    .A(_044_),
    .B(_045_),
    .Y(_126_)
  );
  NAND _255_ (
    .A(iDataIn[5]),
    .B(_033_),
    .Y(_046_)
  );
  NAND _256_ (
    .A(\Ram[0] [5]),
    .B(_034_),
    .Y(_047_)
  );
  NAND _257_ (
    .A(_046_),
    .B(_047_),
    .Y(_127_)
  );
  NOR _258_ (
    .A(\Ram[2] [0]),
    .B(iReadAddress[0]),
    .Y(_048_)
  );
  NAND _259_ (
    .A(_129_),
    .B(iReadAddress[0]),
    .Y(_049_)
  );
  NAND _260_ (
    .A(iReadAddress[1]),
    .B(_049_),
    .Y(_050_)
  );
  NOR _261_ (
    .A(_048_),
    .B(_050_),
    .Y(_051_)
  );
  NAND _262_ (
    .A(\Ram[1] [0]),
    .B(iReadAddress[0]),
    .Y(_052_)
  );
  NOT _263_ (
    .A(_052_),
    .Y(_053_)
  );
  NOR _264_ (
    .A(_135_),
    .B(iReadAddress[0]),
    .Y(_054_)
  );
  NOR _265_ (
    .A(_053_),
    .B(_054_),
    .Y(_055_)
  );
  NOR _266_ (
    .A(iReadAddress[1]),
    .B(_055_),
    .Y(_056_)
  );
  NOR _267_ (
    .A(_051_),
    .B(_056_),
    .Y(_057_)
  );
  NOR _268_ (
    .A(_141_),
    .B(_057_),
    .Y(oDataOut[0])
  );
  NOR _269_ (
    .A(\Ram[2] [1]),
    .B(iReadAddress[0]),
    .Y(_058_)
  );
  NAND _270_ (
    .A(_130_),
    .B(iReadAddress[0]),
    .Y(_059_)
  );
  NAND _271_ (
    .A(iReadAddress[1]),
    .B(_059_),
    .Y(_060_)
  );
  NOR _272_ (
    .A(_058_),
    .B(_060_),
    .Y(_062_)
  );
  NAND _273_ (
    .A(\Ram[1] [1]),
    .B(iReadAddress[0]),
    .Y(_063_)
  );
  NOT _274_ (
    .A(_063_),
    .Y(_064_)
  );
  NOR _275_ (
    .A(_136_),
    .B(iReadAddress[0]),
    .Y(_065_)
  );
  NOR _276_ (
    .A(_064_),
    .B(_065_),
    .Y(_066_)
  );
  NOR _277_ (
    .A(iReadAddress[1]),
    .B(_066_),
    .Y(_067_)
  );
  NOR _278_ (
    .A(_062_),
    .B(_067_),
    .Y(_068_)
  );
  NOR _279_ (
    .A(_141_),
    .B(_068_),
    .Y(oDataOut[1])
  );
  NOR _280_ (
    .A(\Ram[2] [2]),
    .B(iReadAddress[0]),
    .Y(_069_)
  );
  NAND _281_ (
    .A(_131_),
    .B(iReadAddress[0]),
    .Y(_070_)
  );
  NAND _282_ (
    .A(iReadAddress[1]),
    .B(_070_),
    .Y(_071_)
  );
  NOR _283_ (
    .A(_069_),
    .B(_071_),
    .Y(_072_)
  );
  NAND _284_ (
    .A(\Ram[1] [2]),
    .B(iReadAddress[0]),
    .Y(_073_)
  );
  NOT _285_ (
    .A(_073_),
    .Y(_074_)
  );
  NOR _286_ (
    .A(_137_),
    .B(iReadAddress[0]),
    .Y(_075_)
  );
  NOR _287_ (
    .A(_074_),
    .B(_075_),
    .Y(_076_)
  );
  NOR _288_ (
    .A(iReadAddress[1]),
    .B(_076_),
    .Y(_077_)
  );
  NOR _289_ (
    .A(_072_),
    .B(_077_),
    .Y(_078_)
  );
  NOR _290_ (
    .A(_141_),
    .B(_078_),
    .Y(oDataOut[2])
  );
  NOR _291_ (
    .A(\Ram[2] [3]),
    .B(iReadAddress[0]),
    .Y(_079_)
  );
  NAND _292_ (
    .A(_132_),
    .B(iReadAddress[0]),
    .Y(_080_)
  );
  NAND _293_ (
    .A(iReadAddress[1]),
    .B(_080_),
    .Y(_081_)
  );
  NOR _294_ (
    .A(_079_),
    .B(_081_),
    .Y(_082_)
  );
  NAND _295_ (
    .A(\Ram[1] [3]),
    .B(iReadAddress[0]),
    .Y(_083_)
  );
  NOT _296_ (
    .A(_083_),
    .Y(_084_)
  );
  NOR _297_ (
    .A(_138_),
    .B(iReadAddress[0]),
    .Y(_085_)
  );
  NOR _298_ (
    .A(_084_),
    .B(_085_),
    .Y(_086_)
  );
  NOR _299_ (
    .A(iReadAddress[1]),
    .B(_086_),
    .Y(_087_)
  );
  NOR _300_ (
    .A(_082_),
    .B(_087_),
    .Y(_088_)
  );
  NOR _301_ (
    .A(_141_),
    .B(_088_),
    .Y(oDataOut[3])
  );
  NOR _302_ (
    .A(\Ram[2] [4]),
    .B(iReadAddress[0]),
    .Y(_090_)
  );
  NAND _303_ (
    .A(_133_),
    .B(iReadAddress[0]),
    .Y(_091_)
  );
  NAND _304_ (
    .A(iReadAddress[1]),
    .B(_091_),
    .Y(_092_)
  );
  NOR _305_ (
    .A(_090_),
    .B(_092_),
    .Y(_093_)
  );
  NAND _306_ (
    .A(\Ram[1] [4]),
    .B(iReadAddress[0]),
    .Y(_094_)
  );
  NOT _307_ (
    .A(_094_),
    .Y(_095_)
  );
  NOR _308_ (
    .A(_139_),
    .B(iReadAddress[0]),
    .Y(_096_)
  );
  NOR _309_ (
    .A(_095_),
    .B(_096_),
    .Y(_097_)
  );
  NOR _310_ (
    .A(iReadAddress[1]),
    .B(_097_),
    .Y(_098_)
  );
  NOR _311_ (
    .A(_093_),
    .B(_098_),
    .Y(_099_)
  );
  NOR _312_ (
    .A(_141_),
    .B(_099_),
    .Y(oDataOut[4])
  );
  NOR _313_ (
    .A(\Ram[2] [5]),
    .B(iReadAddress[0]),
    .Y(_100_)
  );
  NAND _314_ (
    .A(_134_),
    .B(iReadAddress[0]),
    .Y(_101_)
  );
  NAND _315_ (
    .A(iReadAddress[1]),
    .B(_101_),
    .Y(_102_)
  );
  NOR _316_ (
    .A(_100_),
    .B(_102_),
    .Y(_103_)
  );
  NAND _317_ (
    .A(\Ram[1] [5]),
    .B(iReadAddress[0]),
    .Y(_104_)
  );
  NOT _318_ (
    .A(_104_),
    .Y(_105_)
  );
  NOR _319_ (
    .A(_140_),
    .B(iReadAddress[0]),
    .Y(_106_)
  );
  NOR _320_ (
    .A(_105_),
    .B(_106_),
    .Y(_107_)
  );
  NOR _321_ (
    .A(iReadAddress[1]),
    .B(_107_),
    .Y(_108_)
  );
  NOR _322_ (
    .A(_103_),
    .B(_108_),
    .Y(_110_)
  );
  NOR _323_ (
    .A(_141_),
    .B(_110_),
    .Y(oDataOut[5])
  );
  DFF _324_ (
    .C(Clock),
    .D(_114_),
    .Q(\Ram[3] [0])
  );
  DFF _325_ (
    .C(Clock),
    .D(_128_),
    .Q(\Ram[3] [1])
  );
  DFF _326_ (
    .C(Clock),
    .D(_151_),
    .Q(\Ram[3] [2])
  );
  DFF _327_ (
    .C(Clock),
    .D(_014_),
    .Q(\Ram[3] [3])
  );
  DFF _328_ (
    .C(Clock),
    .D(_037_),
    .Q(\Ram[3] [4])
  );
  DFF _329_ (
    .C(Clock),
    .D(_061_),
    .Q(\Ram[3] [5])
  );
  DFF _330_ (
    .C(Clock),
    .D(_122_),
    .Q(\Ram[0] [0])
  );
  DFF _331_ (
    .C(Clock),
    .D(_123_),
    .Q(\Ram[0] [1])
  );
  DFF _332_ (
    .C(Clock),
    .D(_124_),
    .Q(\Ram[0] [2])
  );
  DFF _333_ (
    .C(Clock),
    .D(_125_),
    .Q(\Ram[0] [3])
  );
  DFF _334_ (
    .C(Clock),
    .D(_126_),
    .Q(\Ram[0] [4])
  );
  DFF _335_ (
    .C(Clock),
    .D(_127_),
    .Q(\Ram[0] [5])
  );
  DFF _336_ (
    .C(Clock),
    .D(_116_),
    .Q(\Ram[1] [0])
  );
  DFF _337_ (
    .C(Clock),
    .D(_117_),
    .Q(\Ram[1] [1])
  );
  DFF _338_ (
    .C(Clock),
    .D(_118_),
    .Q(\Ram[1] [2])
  );
  DFF _339_ (
    .C(Clock),
    .D(_119_),
    .Q(\Ram[1] [3])
  );
  DFF _340_ (
    .C(Clock),
    .D(_120_),
    .Q(\Ram[1] [4])
  );
  DFF _341_ (
    .C(Clock),
    .D(_121_),
    .Q(\Ram[1] [5])
  );
  DFF _342_ (
    .C(Clock),
    .D(_089_),
    .Q(\Ram[2] [0])
  );
  DFF _343_ (
    .C(Clock),
    .D(_109_),
    .Q(\Ram[2] [1])
  );
  DFF _344_ (
    .C(Clock),
    .D(_111_),
    .Q(\Ram[2] [2])
  );
  DFF _345_ (
    .C(Clock),
    .D(_112_),
    .Q(\Ram[2] [3])
  );
  DFF _346_ (
    .C(Clock),
    .D(_113_),
    .Q(\Ram[2] [4])
  );
  DFF _347_ (
    .C(Clock),
    .D(_115_),
    .Q(\Ram[2] [5])
  );
endmodule

module fifoSynth(clk, reset_L, push, pop, Fifo_Data_in, Fifo_Data_out, Almost_Empty, Almost_Full, umbralA, umbralB, Pausa, Fifo_Empty, Fifo_Full, Error_Fifo);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire [2:0] _006_;
  wire [1:0] _007_;
  wire [2:0] _008_;
  wire [2:0] _009_;
  wire [1:0] _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  output Almost_Empty;
  output Almost_Full;
  output Error_Fifo;
  input [5:0] Fifo_Data_in;
  output [5:0] Fifo_Data_out;
  output Fifo_Empty;
  output Fifo_Full;
  output Pausa;
  input clk;
  wire [2:0] num_mem;
  input pop;
  input push;
  wire [1:0] rd_ptr;
  input reset_L;
  output [2:0] umbralA;
  output [2:0] umbralB;
  wire [1:0] wr_ptr;
  NOT _096_ (
    .A(num_mem[2]),
    .Y(_037_)
  );
  NOT _097_ (
    .A(num_mem[1]),
    .Y(_038_)
  );
  NOT _098_ (
    .A(push),
    .Y(_039_)
  );
  NOT _099_ (
    .A(pop),
    .Y(_040_)
  );
  NOT _100_ (
    .A(reset_L),
    .Y(_041_)
  );
  NOT _101_ (
    .A(rd_ptr[1]),
    .Y(_042_)
  );
  NOT _102_ (
    .A(wr_ptr[0]),
    .Y(_043_)
  );
  NOT _103_ (
    .A(wr_ptr[1]),
    .Y(_044_)
  );
  NOT _104_ (
    .A(umbralA[1]),
    .Y(_045_)
  );
  NOT _105_ (
    .A(umbralA[2]),
    .Y(_046_)
  );
  NAND _106_ (
    .A(_038_),
    .B(num_mem[0]),
    .Y(_047_)
  );
  NOT _107_ (
    .A(_047_),
    .Y(_048_)
  );
  NAND _108_ (
    .A(num_mem[2]),
    .B(reset_L),
    .Y(_049_)
  );
  NOR _109_ (
    .A(_047_),
    .B(_049_),
    .Y(_050_)
  );
  NOR _110_ (
    .A(push),
    .B(_040_),
    .Y(_051_)
  );
  NAND _111_ (
    .A(Almost_Empty),
    .B(_051_),
    .Y(_052_)
  );
  NOR _112_ (
    .A(_041_),
    .B(_052_),
    .Y(_053_)
  );
  NOR _113_ (
    .A(_050_),
    .B(_053_),
    .Y(_054_)
  );
  NOT _114_ (
    .A(_054_),
    .Y(_002_)
  );
  NOR _115_ (
    .A(num_mem[1]),
    .B(num_mem[0]),
    .Y(_055_)
  );
  NAND _116_ (
    .A(_037_),
    .B(_055_),
    .Y(_056_)
  );
  NAND _117_ (
    .A(_051_),
    .B(_056_),
    .Y(_057_)
  );
  NOR _118_ (
    .A(_039_),
    .B(pop),
    .Y(_058_)
  );
  NOR _119_ (
    .A(num_mem[0]),
    .B(_058_),
    .Y(_059_)
  );
  NAND _120_ (
    .A(_057_),
    .B(_059_),
    .Y(_060_)
  );
  NOR _121_ (
    .A(_039_),
    .B(_040_),
    .Y(_061_)
  );
  NAND _122_ (
    .A(push),
    .B(pop),
    .Y(_062_)
  );
  NOR _123_ (
    .A(reset_L),
    .B(_061_),
    .Y(_063_)
  );
  NAND _124_ (
    .A(_041_),
    .B(_062_),
    .Y(_064_)
  );
  NOR _125_ (
    .A(push),
    .B(pop),
    .Y(_065_)
  );
  NOT _126_ (
    .A(_065_),
    .Y(_066_)
  );
  NAND _127_ (
    .A(num_mem[0]),
    .B(_062_),
    .Y(_067_)
  );
  NOR _128_ (
    .A(_065_),
    .B(_067_),
    .Y(_068_)
  );
  NOR _129_ (
    .A(_063_),
    .B(_068_),
    .Y(_069_)
  );
  NAND _130_ (
    .A(_060_),
    .B(_069_),
    .Y(_070_)
  );
  NOT _131_ (
    .A(_070_),
    .Y(_006_[0])
  );
  NOR _132_ (
    .A(_041_),
    .B(_061_),
    .Y(_071_)
  );
  NAND _133_ (
    .A(num_mem[1]),
    .B(num_mem[0]),
    .Y(_072_)
  );
  NOT _134_ (
    .A(_072_),
    .Y(_073_)
  );
  NOR _135_ (
    .A(_055_),
    .B(_073_),
    .Y(_074_)
  );
  NOR _136_ (
    .A(_057_),
    .B(_074_),
    .Y(_075_)
  );
  NOR _137_ (
    .A(_038_),
    .B(_066_),
    .Y(_076_)
  );
  NAND _138_ (
    .A(push),
    .B(_074_),
    .Y(_077_)
  );
  NOR _139_ (
    .A(_075_),
    .B(_076_),
    .Y(_078_)
  );
  NAND _140_ (
    .A(_077_),
    .B(_078_),
    .Y(_079_)
  );
  NAND _141_ (
    .A(_071_),
    .B(_079_),
    .Y(_080_)
  );
  NAND _142_ (
    .A(num_mem[1]),
    .B(_061_),
    .Y(_081_)
  );
  NAND _143_ (
    .A(_080_),
    .B(_081_),
    .Y(_006_[1])
  );
  NAND _144_ (
    .A(num_mem[2]),
    .B(_061_),
    .Y(_082_)
  );
  NOR _145_ (
    .A(num_mem[2]),
    .B(_072_),
    .Y(_083_)
  );
  NOT _146_ (
    .A(_083_),
    .Y(_084_)
  );
  NAND _147_ (
    .A(num_mem[2]),
    .B(_072_),
    .Y(_085_)
  );
  NAND _148_ (
    .A(_084_),
    .B(_085_),
    .Y(_086_)
  );
  NAND _149_ (
    .A(push),
    .B(_086_),
    .Y(_087_)
  );
  NAND _150_ (
    .A(pop),
    .B(_055_),
    .Y(_088_)
  );
  NOR _151_ (
    .A(_037_),
    .B(push),
    .Y(_089_)
  );
  NAND _152_ (
    .A(_088_),
    .B(_089_),
    .Y(_090_)
  );
  NAND _153_ (
    .A(_087_),
    .B(_090_),
    .Y(_091_)
  );
  NAND _154_ (
    .A(_071_),
    .B(_091_),
    .Y(_092_)
  );
  NAND _155_ (
    .A(_082_),
    .B(_092_),
    .Y(_006_[2])
  );
  NAND _156_ (
    .A(_057_),
    .B(_062_),
    .Y(_093_)
  );
  NOR _157_ (
    .A(rd_ptr[0]),
    .B(_093_),
    .Y(_094_)
  );
  NAND _158_ (
    .A(rd_ptr[0]),
    .B(_093_),
    .Y(_095_)
  );
  NAND _159_ (
    .A(_064_),
    .B(_095_),
    .Y(_011_)
  );
  NOR _160_ (
    .A(_094_),
    .B(_011_),
    .Y(_007_[0])
  );
  NOR _161_ (
    .A(_042_),
    .B(_095_),
    .Y(_012_)
  );
  NAND _162_ (
    .A(_042_),
    .B(_095_),
    .Y(_013_)
  );
  NAND _163_ (
    .A(_064_),
    .B(_013_),
    .Y(_014_)
  );
  NOR _164_ (
    .A(_012_),
    .B(_014_),
    .Y(_007_[1])
  );
  NOR _165_ (
    .A(_037_),
    .B(pop),
    .Y(_015_)
  );
  NAND _166_ (
    .A(num_mem[2]),
    .B(_055_),
    .Y(_016_)
  );
  NOR _167_ (
    .A(pop),
    .B(_016_),
    .Y(_017_)
  );
  NAND _168_ (
    .A(_055_),
    .B(_015_),
    .Y(_018_)
  );
  NOR _169_ (
    .A(_039_),
    .B(_017_),
    .Y(_019_)
  );
  NAND _170_ (
    .A(push),
    .B(_018_),
    .Y(_020_)
  );
  NOR _171_ (
    .A(_043_),
    .B(_020_),
    .Y(_021_)
  );
  NAND _172_ (
    .A(wr_ptr[0]),
    .B(_019_),
    .Y(_022_)
  );
  NAND _173_ (
    .A(_043_),
    .B(_020_),
    .Y(_023_)
  );
  NAND _174_ (
    .A(_022_),
    .B(_023_),
    .Y(_024_)
  );
  NOR _175_ (
    .A(_063_),
    .B(_024_),
    .Y(_010_[0])
  );
  NOR _176_ (
    .A(_044_),
    .B(_021_),
    .Y(_025_)
  );
  NOR _177_ (
    .A(wr_ptr[1]),
    .B(_022_),
    .Y(_026_)
  );
  NOR _178_ (
    .A(_025_),
    .B(_026_),
    .Y(_027_)
  );
  NOR _179_ (
    .A(_063_),
    .B(_027_),
    .Y(_010_[1])
  );
  NOR _180_ (
    .A(num_mem[1]),
    .B(_049_),
    .Y(_004_)
  );
  NOT _181_ (
    .A(_004_),
    .Y(_028_)
  );
  NAND _182_ (
    .A(reset_L),
    .B(_056_),
    .Y(_003_)
  );
  NAND _183_ (
    .A(reset_L),
    .B(_083_),
    .Y(_029_)
  );
  NOT _184_ (
    .A(_029_),
    .Y(_001_)
  );
  NAND _185_ (
    .A(_028_),
    .B(_029_),
    .Y(_005_)
  );
  NOR _186_ (
    .A(umbralB[0]),
    .B(_083_),
    .Y(_030_)
  );
  NOR _187_ (
    .A(_041_),
    .B(_030_),
    .Y(_009_[0])
  );
  NOR _188_ (
    .A(umbralB[1]),
    .B(_083_),
    .Y(_031_)
  );
  NOR _189_ (
    .A(_041_),
    .B(_031_),
    .Y(_009_[1])
  );
  NAND _190_ (
    .A(reset_L),
    .B(umbralB[2]),
    .Y(_032_)
  );
  NOR _191_ (
    .A(_083_),
    .B(_032_),
    .Y(_009_[2])
  );
  NOR _192_ (
    .A(num_mem[2]),
    .B(_047_),
    .Y(_033_)
  );
  NAND _193_ (
    .A(_037_),
    .B(_048_),
    .Y(_034_)
  );
  NOR _194_ (
    .A(umbralA[0]),
    .B(_033_),
    .Y(_035_)
  );
  NOR _195_ (
    .A(_041_),
    .B(_034_),
    .Y(_000_)
  );
  NOR _196_ (
    .A(_041_),
    .B(_035_),
    .Y(_008_[0])
  );
  NAND _197_ (
    .A(reset_L),
    .B(_034_),
    .Y(_036_)
  );
  NOR _198_ (
    .A(_045_),
    .B(_036_),
    .Y(_008_[1])
  );
  NOR _199_ (
    .A(_046_),
    .B(_036_),
    .Y(_008_[2])
  );
  DFF _200_ (
    .C(clk),
    .D(_010_[0]),
    .Q(wr_ptr[0])
  );
  DFF _201_ (
    .C(clk),
    .D(_010_[1]),
    .Q(wr_ptr[1])
  );
  DFF _202_ (
    .C(clk),
    .D(_002_),
    .Q(Error_Fifo)
  );
  DFF _203_ (
    .C(clk),
    .D(_007_[0]),
    .Q(rd_ptr[0])
  );
  DFF _204_ (
    .C(clk),
    .D(_007_[1]),
    .Q(rd_ptr[1])
  );
  DFF _205_ (
    .C(clk),
    .D(_006_[0]),
    .Q(num_mem[0])
  );
  DFF _206_ (
    .C(clk),
    .D(_006_[1]),
    .Q(num_mem[1])
  );
  DFF _207_ (
    .C(clk),
    .D(_006_[2]),
    .Q(num_mem[2])
  );
  DFF _208_ (
    .C(clk),
    .D(_000_),
    .Q(Almost_Empty)
  );
  DFF _209_ (
    .C(clk),
    .D(_001_),
    .Q(Almost_Full)
  );
  DFF _210_ (
    .C(clk),
    .D(_008_[0]),
    .Q(umbralA[0])
  );
  DFF _211_ (
    .C(clk),
    .D(_008_[1]),
    .Q(umbralA[1])
  );
  DFF _212_ (
    .C(clk),
    .D(_008_[2]),
    .Q(umbralA[2])
  );
  DFF _213_ (
    .C(clk),
    .D(_009_[0]),
    .Q(umbralB[0])
  );
  DFF _214_ (
    .C(clk),
    .D(_009_[1]),
    .Q(umbralB[1])
  );
  DFF _215_ (
    .C(clk),
    .D(_009_[2]),
    .Q(umbralB[2])
  );
  DFF _216_ (
    .C(clk),
    .D(_005_),
    .Q(Pausa)
  );
  DFF _217_ (
    .C(clk),
    .D(_003_),
    .Q(Fifo_Empty)
  );
  DFF _218_ (
    .C(clk),
    .D(_004_),
    .Q(Fifo_Full)
  );
  \$paramod\dual_port_memory_Synth\DATA_WIDTH=6\ADDR_WIDTH=2\MEM_SIZE=3  memoria (
    .Clock(clk),
    .iDataIn(Fifo_Data_in),
    .iReadAddress(rd_ptr),
    .iReadEnable(pop),
    .iWriteAddress(wr_ptr),
    .iWriteEnable(push),
    .oDataOut(Fifo_Data_out)
  );
endmodule
