/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-zWLHjG/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module \$paramod\dual_port_memory_Synth\DATA_WIDTH=6\ADDR_WIDTH=2\MEM_SIZE=3 (Clock, iWriteEnable, iReadEnable, iReadAddress, iWriteAddress, iDataIn, oDataOut);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  input Clock;
  wire [5:0] \Ram[0] ;
  wire [5:0] \Ram[1] ;
  wire [5:0] \Ram[2] ;
  wire [5:0] \Ram[3] ;
  input [5:0] iDataIn;
  input [1:0] iReadAddress;
  input iReadEnable;
  input [1:0] iWriteAddress;
  input iWriteEnable;
  output [5:0] oDataOut;
  NOT _160_ (
    .A(iWriteAddress[1]),
    .Y(_126_)
  );
  NAND _161_ (
    .A(iWriteAddress[0]),
    .B(iWriteEnable),
    .Y(_128_)
  );
  NOR _162_ (
    .A(_128_),
    .B(_126_),
    .Y(_129_)
  );
  NAND _163_ (
    .A(_129_),
    .B(iDataIn[0]),
    .Y(_131_)
  );
  NOT _164_ (
    .A(_129_),
    .Y(_132_)
  );
  NAND _165_ (
    .A(_132_),
    .B(\Ram[3] [0]),
    .Y(_134_)
  );
  NAND _166_ (
    .A(_134_),
    .B(_131_),
    .Y(_110_)
  );
  NAND _167_ (
    .A(_129_),
    .B(iDataIn[1]),
    .Y(_137_)
  );
  NAND _168_ (
    .A(_132_),
    .B(\Ram[3] [1]),
    .Y(_139_)
  );
  NAND _169_ (
    .A(_139_),
    .B(_137_),
    .Y(_111_)
  );
  NAND _170_ (
    .A(_129_),
    .B(iDataIn[2]),
    .Y(_142_)
  );
  NAND _171_ (
    .A(_132_),
    .B(\Ram[3] [2]),
    .Y(_143_)
  );
  NAND _172_ (
    .A(_143_),
    .B(_142_),
    .Y(_112_)
  );
  NAND _173_ (
    .A(_129_),
    .B(iDataIn[3]),
    .Y(_144_)
  );
  NAND _174_ (
    .A(_132_),
    .B(\Ram[3] [3]),
    .Y(_145_)
  );
  NAND _175_ (
    .A(_145_),
    .B(_144_),
    .Y(_113_)
  );
  NAND _176_ (
    .A(_129_),
    .B(iDataIn[4]),
    .Y(_146_)
  );
  NAND _177_ (
    .A(_132_),
    .B(\Ram[3] [4]),
    .Y(_147_)
  );
  NAND _178_ (
    .A(_147_),
    .B(_146_),
    .Y(_114_)
  );
  NAND _179_ (
    .A(_129_),
    .B(iDataIn[5]),
    .Y(_148_)
  );
  NAND _180_ (
    .A(_132_),
    .B(\Ram[3] [5]),
    .Y(_149_)
  );
  NAND _181_ (
    .A(_149_),
    .B(_148_),
    .Y(_115_)
  );
  NOT _182_ (
    .A(iWriteAddress[0]),
    .Y(_150_)
  );
  NAND _183_ (
    .A(_150_),
    .B(iWriteEnable),
    .Y(_151_)
  );
  NOR _184_ (
    .A(_151_),
    .B(iWriteAddress[1]),
    .Y(_152_)
  );
  NAND _185_ (
    .A(_152_),
    .B(iDataIn[0]),
    .Y(_153_)
  );
  NOT _186_ (
    .A(iWriteEnable),
    .Y(_154_)
  );
  NOR _187_ (
    .A(iWriteAddress[0]),
    .B(_154_),
    .Y(_155_)
  );
  NAND _188_ (
    .A(_155_),
    .B(_126_),
    .Y(_156_)
  );
  NAND _189_ (
    .A(_156_),
    .B(\Ram[0] [0]),
    .Y(_157_)
  );
  NAND _190_ (
    .A(_157_),
    .B(_153_),
    .Y(_116_)
  );
  NAND _191_ (
    .A(_152_),
    .B(iDataIn[1]),
    .Y(_158_)
  );
  NAND _192_ (
    .A(_156_),
    .B(\Ram[0] [1]),
    .Y(_159_)
  );
  NAND _193_ (
    .A(_159_),
    .B(_158_),
    .Y(_117_)
  );
  NAND _194_ (
    .A(_152_),
    .B(iDataIn[2]),
    .Y(_000_)
  );
  NAND _195_ (
    .A(_156_),
    .B(\Ram[0] [2]),
    .Y(_001_)
  );
  NAND _196_ (
    .A(_001_),
    .B(_000_),
    .Y(_118_)
  );
  NAND _197_ (
    .A(_152_),
    .B(iDataIn[3]),
    .Y(_002_)
  );
  NAND _198_ (
    .A(_156_),
    .B(\Ram[0] [3]),
    .Y(_003_)
  );
  NAND _199_ (
    .A(_003_),
    .B(_002_),
    .Y(_119_)
  );
  NAND _200_ (
    .A(_152_),
    .B(iDataIn[4]),
    .Y(_004_)
  );
  NAND _201_ (
    .A(_156_),
    .B(\Ram[0] [4]),
    .Y(_005_)
  );
  NAND _202_ (
    .A(_005_),
    .B(_004_),
    .Y(_120_)
  );
  NAND _203_ (
    .A(_152_),
    .B(iDataIn[5]),
    .Y(_006_)
  );
  NAND _204_ (
    .A(_156_),
    .B(\Ram[0] [5]),
    .Y(_007_)
  );
  NAND _205_ (
    .A(_007_),
    .B(_006_),
    .Y(_121_)
  );
  NOR _206_ (
    .A(_151_),
    .B(_126_),
    .Y(_008_)
  );
  NAND _207_ (
    .A(_008_),
    .B(iDataIn[0]),
    .Y(_009_)
  );
  NAND _208_ (
    .A(_155_),
    .B(iWriteAddress[1]),
    .Y(_010_)
  );
  NAND _209_ (
    .A(_010_),
    .B(\Ram[2] [0]),
    .Y(_011_)
  );
  NAND _210_ (
    .A(_011_),
    .B(_009_),
    .Y(_122_)
  );
  NAND _211_ (
    .A(_008_),
    .B(iDataIn[1]),
    .Y(_012_)
  );
  NAND _212_ (
    .A(_010_),
    .B(\Ram[2] [1]),
    .Y(_013_)
  );
  NAND _213_ (
    .A(_013_),
    .B(_012_),
    .Y(_123_)
  );
  NAND _214_ (
    .A(_008_),
    .B(iDataIn[2]),
    .Y(_014_)
  );
  NAND _215_ (
    .A(_010_),
    .B(\Ram[2] [2]),
    .Y(_015_)
  );
  NAND _216_ (
    .A(_015_),
    .B(_014_),
    .Y(_124_)
  );
  NAND _217_ (
    .A(_008_),
    .B(iDataIn[3]),
    .Y(_016_)
  );
  NAND _218_ (
    .A(_010_),
    .B(\Ram[2] [3]),
    .Y(_017_)
  );
  NAND _219_ (
    .A(_017_),
    .B(_016_),
    .Y(_125_)
  );
  NAND _220_ (
    .A(_008_),
    .B(iDataIn[4]),
    .Y(_018_)
  );
  NAND _221_ (
    .A(_010_),
    .B(\Ram[2] [4]),
    .Y(_019_)
  );
  NAND _222_ (
    .A(_019_),
    .B(_018_),
    .Y(_127_)
  );
  NAND _223_ (
    .A(_008_),
    .B(iDataIn[5]),
    .Y(_020_)
  );
  NAND _224_ (
    .A(_010_),
    .B(\Ram[2] [5]),
    .Y(_021_)
  );
  NAND _225_ (
    .A(_021_),
    .B(_020_),
    .Y(_130_)
  );
  NOR _226_ (
    .A(_128_),
    .B(iWriteAddress[1]),
    .Y(_022_)
  );
  NAND _227_ (
    .A(_022_),
    .B(iDataIn[0]),
    .Y(_023_)
  );
  NOT _228_ (
    .A(_022_),
    .Y(_024_)
  );
  NAND _229_ (
    .A(_024_),
    .B(\Ram[1] [0]),
    .Y(_025_)
  );
  NAND _230_ (
    .A(_025_),
    .B(_023_),
    .Y(_133_)
  );
  NAND _231_ (
    .A(_022_),
    .B(iDataIn[1]),
    .Y(_026_)
  );
  NAND _232_ (
    .A(_024_),
    .B(\Ram[1] [1]),
    .Y(_027_)
  );
  NAND _233_ (
    .A(_027_),
    .B(_026_),
    .Y(_135_)
  );
  NAND _234_ (
    .A(_022_),
    .B(iDataIn[2]),
    .Y(_028_)
  );
  NAND _235_ (
    .A(_024_),
    .B(\Ram[1] [2]),
    .Y(_029_)
  );
  NAND _236_ (
    .A(_029_),
    .B(_028_),
    .Y(_136_)
  );
  NAND _237_ (
    .A(_022_),
    .B(iDataIn[3]),
    .Y(_030_)
  );
  NAND _238_ (
    .A(_024_),
    .B(\Ram[1] [3]),
    .Y(_031_)
  );
  NAND _239_ (
    .A(_031_),
    .B(_030_),
    .Y(_138_)
  );
  NAND _240_ (
    .A(_022_),
    .B(iDataIn[4]),
    .Y(_032_)
  );
  NAND _241_ (
    .A(_024_),
    .B(\Ram[1] [4]),
    .Y(_033_)
  );
  NAND _242_ (
    .A(_033_),
    .B(_032_),
    .Y(_140_)
  );
  NAND _243_ (
    .A(_022_),
    .B(iDataIn[5]),
    .Y(_034_)
  );
  NAND _244_ (
    .A(_024_),
    .B(\Ram[1] [5]),
    .Y(_035_)
  );
  NAND _245_ (
    .A(_035_),
    .B(_034_),
    .Y(_141_)
  );
  NOT _246_ (
    .A(iReadEnable),
    .Y(_036_)
  );
  NOR _247_ (
    .A(\Ram[2] [0]),
    .B(iReadAddress[0]),
    .Y(_037_)
  );
  NOT _248_ (
    .A(\Ram[3] [0]),
    .Y(_038_)
  );
  NAND _249_ (
    .A(_038_),
    .B(iReadAddress[0]),
    .Y(_039_)
  );
  NAND _250_ (
    .A(_039_),
    .B(iReadAddress[1]),
    .Y(_040_)
  );
  NOR _251_ (
    .A(_040_),
    .B(_037_),
    .Y(_041_)
  );
  NOT _252_ (
    .A(\Ram[1] [0]),
    .Y(_042_)
  );
  NOT _253_ (
    .A(iReadAddress[0]),
    .Y(_043_)
  );
  NOR _254_ (
    .A(_043_),
    .B(_042_),
    .Y(_044_)
  );
  NOT _255_ (
    .A(\Ram[0] [0]),
    .Y(_045_)
  );
  NOR _256_ (
    .A(iReadAddress[0]),
    .B(_045_),
    .Y(_046_)
  );
  NOR _257_ (
    .A(_046_),
    .B(_044_),
    .Y(_047_)
  );
  NOR _258_ (
    .A(_047_),
    .B(iReadAddress[1]),
    .Y(_048_)
  );
  NOR _259_ (
    .A(_048_),
    .B(_041_),
    .Y(_049_)
  );
  NOR _260_ (
    .A(_049_),
    .B(_036_),
    .Y(oDataOut[0])
  );
  NOR _261_ (
    .A(\Ram[2] [1]),
    .B(iReadAddress[0]),
    .Y(_050_)
  );
  NOT _262_ (
    .A(\Ram[3] [1]),
    .Y(_051_)
  );
  NAND _263_ (
    .A(_051_),
    .B(iReadAddress[0]),
    .Y(_052_)
  );
  NAND _264_ (
    .A(_052_),
    .B(iReadAddress[1]),
    .Y(_053_)
  );
  NOR _265_ (
    .A(_053_),
    .B(_050_),
    .Y(_054_)
  );
  NOT _266_ (
    .A(\Ram[1] [1]),
    .Y(_055_)
  );
  NOR _267_ (
    .A(_055_),
    .B(_043_),
    .Y(_056_)
  );
  NOT _268_ (
    .A(\Ram[0] [1]),
    .Y(_057_)
  );
  NOR _269_ (
    .A(_057_),
    .B(iReadAddress[0]),
    .Y(_058_)
  );
  NOR _270_ (
    .A(_058_),
    .B(_056_),
    .Y(_059_)
  );
  NOR _271_ (
    .A(_059_),
    .B(iReadAddress[1]),
    .Y(_060_)
  );
  NOR _272_ (
    .A(_060_),
    .B(_054_),
    .Y(_061_)
  );
  NOR _273_ (
    .A(_061_),
    .B(_036_),
    .Y(oDataOut[1])
  );
  NOR _274_ (
    .A(\Ram[2] [2]),
    .B(iReadAddress[0]),
    .Y(_062_)
  );
  NOT _275_ (
    .A(\Ram[3] [2]),
    .Y(_063_)
  );
  NAND _276_ (
    .A(_063_),
    .B(iReadAddress[0]),
    .Y(_064_)
  );
  NAND _277_ (
    .A(_064_),
    .B(iReadAddress[1]),
    .Y(_065_)
  );
  NOR _278_ (
    .A(_065_),
    .B(_062_),
    .Y(_066_)
  );
  NOT _279_ (
    .A(\Ram[1] [2]),
    .Y(_067_)
  );
  NOR _280_ (
    .A(_067_),
    .B(_043_),
    .Y(_068_)
  );
  NOT _281_ (
    .A(\Ram[0] [2]),
    .Y(_069_)
  );
  NOR _282_ (
    .A(_069_),
    .B(iReadAddress[0]),
    .Y(_070_)
  );
  NOR _283_ (
    .A(_070_),
    .B(_068_),
    .Y(_071_)
  );
  NOR _284_ (
    .A(_071_),
    .B(iReadAddress[1]),
    .Y(_072_)
  );
  NOR _285_ (
    .A(_072_),
    .B(_066_),
    .Y(_073_)
  );
  NOR _286_ (
    .A(_073_),
    .B(_036_),
    .Y(oDataOut[2])
  );
  NOR _287_ (
    .A(\Ram[2] [3]),
    .B(iReadAddress[0]),
    .Y(_074_)
  );
  NOT _288_ (
    .A(\Ram[3] [3]),
    .Y(_075_)
  );
  NAND _289_ (
    .A(_075_),
    .B(iReadAddress[0]),
    .Y(_076_)
  );
  NAND _290_ (
    .A(_076_),
    .B(iReadAddress[1]),
    .Y(_077_)
  );
  NOR _291_ (
    .A(_077_),
    .B(_074_),
    .Y(_078_)
  );
  NOT _292_ (
    .A(\Ram[1] [3]),
    .Y(_079_)
  );
  NOR _293_ (
    .A(_079_),
    .B(_043_),
    .Y(_080_)
  );
  NOT _294_ (
    .A(\Ram[0] [3]),
    .Y(_081_)
  );
  NOR _295_ (
    .A(_081_),
    .B(iReadAddress[0]),
    .Y(_082_)
  );
  NOR _296_ (
    .A(_082_),
    .B(_080_),
    .Y(_083_)
  );
  NOR _297_ (
    .A(_083_),
    .B(iReadAddress[1]),
    .Y(_084_)
  );
  NOR _298_ (
    .A(_084_),
    .B(_078_),
    .Y(_085_)
  );
  NOR _299_ (
    .A(_085_),
    .B(_036_),
    .Y(oDataOut[3])
  );
  NOR _300_ (
    .A(\Ram[2] [4]),
    .B(iReadAddress[0]),
    .Y(_086_)
  );
  NOT _301_ (
    .A(\Ram[3] [4]),
    .Y(_087_)
  );
  NAND _302_ (
    .A(_087_),
    .B(iReadAddress[0]),
    .Y(_088_)
  );
  NAND _303_ (
    .A(_088_),
    .B(iReadAddress[1]),
    .Y(_089_)
  );
  NOR _304_ (
    .A(_089_),
    .B(_086_),
    .Y(_090_)
  );
  NOT _305_ (
    .A(\Ram[1] [4]),
    .Y(_091_)
  );
  NOR _306_ (
    .A(_091_),
    .B(_043_),
    .Y(_092_)
  );
  NOT _307_ (
    .A(\Ram[0] [4]),
    .Y(_093_)
  );
  NOR _308_ (
    .A(_093_),
    .B(iReadAddress[0]),
    .Y(_094_)
  );
  NOR _309_ (
    .A(_094_),
    .B(_092_),
    .Y(_095_)
  );
  NOR _310_ (
    .A(_095_),
    .B(iReadAddress[1]),
    .Y(_096_)
  );
  NOR _311_ (
    .A(_096_),
    .B(_090_),
    .Y(_097_)
  );
  NOR _312_ (
    .A(_097_),
    .B(_036_),
    .Y(oDataOut[4])
  );
  NOR _313_ (
    .A(\Ram[2] [5]),
    .B(iReadAddress[0]),
    .Y(_098_)
  );
  NOT _314_ (
    .A(\Ram[3] [5]),
    .Y(_099_)
  );
  NAND _315_ (
    .A(_099_),
    .B(iReadAddress[0]),
    .Y(_100_)
  );
  NAND _316_ (
    .A(_100_),
    .B(iReadAddress[1]),
    .Y(_101_)
  );
  NOR _317_ (
    .A(_101_),
    .B(_098_),
    .Y(_102_)
  );
  NOT _318_ (
    .A(\Ram[1] [5]),
    .Y(_103_)
  );
  NOR _319_ (
    .A(_103_),
    .B(_043_),
    .Y(_104_)
  );
  NOT _320_ (
    .A(\Ram[0] [5]),
    .Y(_105_)
  );
  NOR _321_ (
    .A(_105_),
    .B(iReadAddress[0]),
    .Y(_106_)
  );
  NOR _322_ (
    .A(_106_),
    .B(_104_),
    .Y(_107_)
  );
  NOR _323_ (
    .A(_107_),
    .B(iReadAddress[1]),
    .Y(_108_)
  );
  NOR _324_ (
    .A(_108_),
    .B(_102_),
    .Y(_109_)
  );
  NOR _325_ (
    .A(_109_),
    .B(_036_),
    .Y(oDataOut[5])
  );
  DFF _326_ (
    .C(Clock),
    .D(_116_),
    .Q(\Ram[0] [0])
  );
  DFF _327_ (
    .C(Clock),
    .D(_117_),
    .Q(\Ram[0] [1])
  );
  DFF _328_ (
    .C(Clock),
    .D(_118_),
    .Q(\Ram[0] [2])
  );
  DFF _329_ (
    .C(Clock),
    .D(_119_),
    .Q(\Ram[0] [3])
  );
  DFF _330_ (
    .C(Clock),
    .D(_120_),
    .Q(\Ram[0] [4])
  );
  DFF _331_ (
    .C(Clock),
    .D(_121_),
    .Q(\Ram[0] [5])
  );
  DFF _332_ (
    .C(Clock),
    .D(_133_),
    .Q(\Ram[1] [0])
  );
  DFF _333_ (
    .C(Clock),
    .D(_135_),
    .Q(\Ram[1] [1])
  );
  DFF _334_ (
    .C(Clock),
    .D(_136_),
    .Q(\Ram[1] [2])
  );
  DFF _335_ (
    .C(Clock),
    .D(_138_),
    .Q(\Ram[1] [3])
  );
  DFF _336_ (
    .C(Clock),
    .D(_140_),
    .Q(\Ram[1] [4])
  );
  DFF _337_ (
    .C(Clock),
    .D(_141_),
    .Q(\Ram[1] [5])
  );
  DFF _338_ (
    .C(Clock),
    .D(_110_),
    .Q(\Ram[3] [0])
  );
  DFF _339_ (
    .C(Clock),
    .D(_111_),
    .Q(\Ram[3] [1])
  );
  DFF _340_ (
    .C(Clock),
    .D(_112_),
    .Q(\Ram[3] [2])
  );
  DFF _341_ (
    .C(Clock),
    .D(_113_),
    .Q(\Ram[3] [3])
  );
  DFF _342_ (
    .C(Clock),
    .D(_114_),
    .Q(\Ram[3] [4])
  );
  DFF _343_ (
    .C(Clock),
    .D(_115_),
    .Q(\Ram[3] [5])
  );
  DFF _344_ (
    .C(Clock),
    .D(_122_),
    .Q(\Ram[2] [0])
  );
  DFF _345_ (
    .C(Clock),
    .D(_123_),
    .Q(\Ram[2] [1])
  );
  DFF _346_ (
    .C(Clock),
    .D(_124_),
    .Q(\Ram[2] [2])
  );
  DFF _347_ (
    .C(Clock),
    .D(_125_),
    .Q(\Ram[2] [3])
  );
  DFF _348_ (
    .C(Clock),
    .D(_127_),
    .Q(\Ram[2] [4])
  );
  DFF _349_ (
    .C(Clock),
    .D(_130_),
    .Q(\Ram[2] [5])
  );
endmodule

module fifoSynth(clk, reset_L, push, pop, Fifo_Data_in, Fifo_Data_out, Almost_Empty, Almost_Full, Pausa, Fifo_Empty, Fifo_Full, Error_Fifo);
  wire [1:0] _00_;
  wire [1:0] _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  output Almost_Empty;
  output Almost_Full;
  output Error_Fifo;
  input [5:0] Fifo_Data_in;
  output [5:0] Fifo_Data_out;
  output Fifo_Empty;
  output Fifo_Full;
  output Pausa;
  input clk;
  input pop;
  input push;
  wire [1:0] rd_ptr;
  input reset_L;
  wire [1:0] wr_ptr;
  NOT _20_ (
    .A(pop),
    .Y(_02_)
  );
  NOT _21_ (
    .A(rd_ptr[0]),
    .Y(_03_)
  );
  NOR _22_ (
    .A(_03_),
    .B(_02_),
    .Y(_04_)
  );
  NOT _23_ (
    .A(reset_L),
    .Y(_05_)
  );
  NAND _24_ (
    .A(pop),
    .B(push),
    .Y(_06_)
  );
  NAND _25_ (
    .A(_06_),
    .B(_05_),
    .Y(_07_)
  );
  NAND _26_ (
    .A(_03_),
    .B(_02_),
    .Y(_08_)
  );
  NAND _27_ (
    .A(_08_),
    .B(_07_),
    .Y(_09_)
  );
  NOR _28_ (
    .A(_09_),
    .B(_04_),
    .Y(_00_[0])
  );
  NOR _29_ (
    .A(_04_),
    .B(rd_ptr[1]),
    .Y(_10_)
  );
  NAND _30_ (
    .A(_04_),
    .B(rd_ptr[1]),
    .Y(_11_)
  );
  NAND _31_ (
    .A(_11_),
    .B(_07_),
    .Y(_12_)
  );
  NOR _32_ (
    .A(_12_),
    .B(_10_),
    .Y(_00_[1])
  );
  NOR _33_ (
    .A(wr_ptr[0]),
    .B(push),
    .Y(_13_)
  );
  NAND _34_ (
    .A(wr_ptr[0]),
    .B(push),
    .Y(_14_)
  );
  NAND _35_ (
    .A(_14_),
    .B(_07_),
    .Y(_15_)
  );
  NOR _36_ (
    .A(_15_),
    .B(_13_),
    .Y(_01_[0])
  );
  NOT _37_ (
    .A(wr_ptr[1]),
    .Y(_16_)
  );
  NOR _38_ (
    .A(_14_),
    .B(_16_),
    .Y(_17_)
  );
  NAND _39_ (
    .A(_14_),
    .B(_16_),
    .Y(_18_)
  );
  NAND _40_ (
    .A(_18_),
    .B(_07_),
    .Y(_19_)
  );
  NOR _41_ (
    .A(_19_),
    .B(_17_),
    .Y(_01_[1])
  );
  DFF _42_ (
    .C(clk),
    .D(_01_[0]),
    .Q(wr_ptr[0])
  );
  DFF _43_ (
    .C(clk),
    .D(_01_[1]),
    .Q(wr_ptr[1])
  );
  DFF _44_ (
    .C(clk),
    .D(_00_[0]),
    .Q(rd_ptr[0])
  );
  DFF _45_ (
    .C(clk),
    .D(_00_[1]),
    .Q(rd_ptr[1])
  );
  \$paramod\dual_port_memory_Synth\DATA_WIDTH=6\ADDR_WIDTH=2\MEM_SIZE=3  memoria (
    .Clock(clk),
    .iDataIn(Fifo_Data_in),
    .iReadAddress(rd_ptr),
    .iReadEnable(pop),
    .iWriteAddress(wr_ptr),
    .iWriteEnable(push),
    .oDataOut(Fifo_Data_out)
  );
  assign Almost_Empty = 1'b0;
  assign Almost_Full = 1'b0;
  assign Error_Fifo = 1'b0;
  assign Fifo_Empty = 1'b1;
  assign Fifo_Full = 1'b0;
  assign Pausa = 1'b0;
endmodule
