/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-zWLHjG/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module PCIE_Synth(clk, reset_L, init, data_in_principal, push, pop_D0, pop_D1, data_out0, data_out1, active_out, idle_out, error_out);
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire _0560_;
  wire _0561_;
  wire _0562_;
  wire _0563_;
  wire _0564_;
  wire _0565_;
  wire _0566_;
  wire _0567_;
  wire _0568_;
  wire _0569_;
  wire _0570_;
  wire _0571_;
  wire _0572_;
  wire _0573_;
  wire _0574_;
  wire _0575_;
  wire _0576_;
  wire _0577_;
  wire _0578_;
  wire _0579_;
  wire _0580_;
  wire _0581_;
  wire _0582_;
  wire _0583_;
  wire _0584_;
  wire _0585_;
  wire _0586_;
  wire _0587_;
  wire _0588_;
  wire _0589_;
  wire _0590_;
  wire _0591_;
  wire _0592_;
  wire _0593_;
  wire _0594_;
  wire _0595_;
  wire _0596_;
  wire _0597_;
  wire _0598_;
  wire _0599_;
  wire _0600_;
  wire _0601_;
  wire _0602_;
  wire _0603_;
  wire _0604_;
  wire _0605_;
  wire _0606_;
  wire _0607_;
  wire _0608_;
  wire _0609_;
  wire _0610_;
  wire _0611_;
  wire _0612_;
  wire _0613_;
  wire _0614_;
  wire _0615_;
  wire _0616_;
  wire _0617_;
  wire _0618_;
  wire _0619_;
  wire _0620_;
  wire _0621_;
  wire _0622_;
  wire _0623_;
  wire _0624_;
  wire _0625_;
  wire _0626_;
  wire _0627_;
  wire _0628_;
  wire _0629_;
  wire _0630_;
  wire _0631_;
  wire _0632_;
  wire _0633_;
  wire _0634_;
  wire _0635_;
  wire _0636_;
  wire _0637_;
  wire _0638_;
  wire _0639_;
  wire _0640_;
  wire _0641_;
  wire _0642_;
  wire _0643_;
  wire _0644_;
  wire _0645_;
  wire _0646_;
  wire _0647_;
  wire _0648_;
  wire _0649_;
  wire _0650_;
  wire _0651_;
  wire _0652_;
  wire _0653_;
  wire _0654_;
  wire _0655_;
  wire _0656_;
  wire _0657_;
  wire _0658_;
  wire _0659_;
  wire _0660_;
  wire _0661_;
  wire _0662_;
  wire _0663_;
  wire _0664_;
  wire _0665_;
  wire _0666_;
  wire _0667_;
  wire _0668_;
  wire _0669_;
  wire _0670_;
  wire _0671_;
  wire _0672_;
  wire _0673_;
  wire _0674_;
  wire _0675_;
  wire _0676_;
  wire _0677_;
  wire _0678_;
  wire _0679_;
  wire _0680_;
  wire _0681_;
  wire _0682_;
  wire _0683_;
  wire _0684_;
  wire _0685_;
  wire _0686_;
  wire _0687_;
  wire _0688_;
  wire _0689_;
  wire _0690_;
  wire _0691_;
  wire _0692_;
  wire _0693_;
  wire _0694_;
  wire _0695_;
  wire _0696_;
  wire _0697_;
  wire _0698_;
  wire _0699_;
  wire _0700_;
  wire _0701_;
  wire _0702_;
  wire _0703_;
  wire _0704_;
  wire _0705_;
  wire _0706_;
  wire _0707_;
  wire _0708_;
  wire _0709_;
  wire _0710_;
  wire _0711_;
  wire _0712_;
  wire _0713_;
  wire _0714_;
  wire _0715_;
  wire _0716_;
  wire _0717_;
  wire _0718_;
  wire _0719_;
  wire _0720_;
  wire _0721_;
  wire _0722_;
  wire _0723_;
  wire _0724_;
  wire _0725_;
  wire _0726_;
  wire _0727_;
  wire _0728_;
  wire _0729_;
  wire _0730_;
  wire _0731_;
  wire _0732_;
  wire _0733_;
  wire _0734_;
  wire _0735_;
  wire _0736_;
  wire _0737_;
  wire _0738_;
  wire _0739_;
  wire _0740_;
  wire _0741_;
  wire _0742_;
  wire _0743_;
  wire _0744_;
  wire _0745_;
  wire _0746_;
  wire _0747_;
  wire _0748_;
  wire _0749_;
  wire _0750_;
  wire _0751_;
  wire _0752_;
  wire _0753_;
  wire _0754_;
  wire _0755_;
  wire _0756_;
  wire _0757_;
  wire _0758_;
  wire _0759_;
  wire _0760_;
  wire _0761_;
  wire _0762_;
  wire _0763_;
  wire _0764_;
  wire _0765_;
  wire _0766_;
  wire _0767_;
  wire _0768_;
  wire _0769_;
  wire _0770_;
  wire _0771_;
  wire [5:0] \D0Fifo.Fifo_Data_in ;
  wire \D0Fifo.Pausa ;
  wire [5:0] \D0Fifo.memoria.Ram[0] ;
  wire [5:0] \D0Fifo.memoria.Ram[1] ;
  wire [5:0] \D0Fifo.memoria.Ram[2] ;
  wire [5:0] \D0Fifo.memoria.Ram[3] ;
  wire [1:0] \D0Fifo.memoria.iReadAddress ;
  wire [1:0] \D0Fifo.memoria.iWriteAddress ;
  wire \D0Fifo.memoria.iWriteEnable ;
  wire [2:0] \D0Fifo.num_mem ;
  wire \D1Fifo.Pausa ;
  wire [1:0] \D1Fifo.memoria.iReadAddress ;
  wire [2:0] \D1Fifo.num_mem ;
  wire [5:0] \Demux_D0_D1.data_in ;
  wire \Demux_D0_D1.valid_in ;
  wire Fifo_Empty_VC0;
  wire Fifo_Empty_VC1;
  wire [5:0] \MainFifo.memoria.Ram[0] ;
  wire [5:0] \MainFifo.memoria.Ram[1] ;
  wire [5:0] \MainFifo.memoria.Ram[2] ;
  wire [5:0] \MainFifo.memoria.Ram[3] ;
  wire [1:0] \MainFifo.memoria.iReadAddress ;
  wire [1:0] \MainFifo.memoria.iWriteAddress ;
  wire [2:0] \MainFifo.num_mem ;
  wire [5:0] \VC0Fifo.Fifo_Data_in ;
  wire [5:0] \VC0Fifo.memoria.Ram[0] ;
  wire [5:0] \VC0Fifo.memoria.Ram[1] ;
  wire [5:0] \VC0Fifo.memoria.Ram[2] ;
  wire [5:0] \VC0Fifo.memoria.Ram[3] ;
  wire [1:0] \VC0Fifo.memoria.iReadAddress ;
  wire \VC0Fifo.memoria.iReadEnable ;
  wire [1:0] \VC0Fifo.memoria.iWriteAddress ;
  wire \VC0Fifo.memoria.iWriteEnable ;
  wire [4:0] \VC0Fifo.num_mem ;
  wire [5:0] \VC1Fifo.Fifo_Data_in ;
  wire [5:0] \VC1Fifo.memoria.Ram[0] ;
  wire [5:0] \VC1Fifo.memoria.Ram[1] ;
  wire [5:0] \VC1Fifo.memoria.Ram[2] ;
  wire [5:0] \VC1Fifo.memoria.Ram[3] ;
  wire [1:0] \VC1Fifo.memoria.iReadAddress ;
  wire \VC1Fifo.memoria.iReadEnable ;
  wire [1:0] \VC1Fifo.memoria.iWriteAddress ;
  wire \VC1Fifo.memoria.iWriteEnable ;
  wire [4:0] \VC1Fifo.num_mem ;
  output active_out;
  input clk;
  input [5:0] data_in_principal;
  output [5:0] data_out0;
  output [5:0] data_out1;
  output error_out;
  wire [4:0] \fsm_Control1.nxt_state ;
  wire [4:0] \fsm_Control1.state ;
  output idle_out;
  input init;
  wire pausaD0D1;
  input pop_D0;
  input pop_D1;
  input push;
  input reset_L;
  NOT _0772_ (
    .A(reset_L),
    .Y(_0057_)
  );
  NOT _0773_ (
    .A(\D0Fifo.Pausa ),
    .Y(_0058_)
  );
  NOR _0774_ (
    .A(\D1Fifo.Pausa ),
    .B(_0058_),
    .Y(_0059_)
  );
  NOT _0775_ (
    .A(\D1Fifo.Pausa ),
    .Y(_0060_)
  );
  NOR _0776_ (
    .A(_0060_),
    .B(\D0Fifo.Pausa ),
    .Y(_0061_)
  );
  NOR _0777_ (
    .A(_0061_),
    .B(_0059_),
    .Y(_0062_)
  );
  NOR _0778_ (
    .A(_0062_),
    .B(_0057_),
    .Y(_0000_)
  );
  NAND _0779_ (
    .A(pausaD0D1),
    .B(reset_L),
    .Y(_0063_)
  );
  NOR _0780_ (
    .A(_0063_),
    .B(Fifo_Empty_VC0),
    .Y(_0001_)
  );
  NAND _0781_ (
    .A(\VC1Fifo.memoria.iReadEnable ),
    .B(_0057_),
    .Y(_0064_)
  );
  NOT _0782_ (
    .A(_0063_),
    .Y(_0065_)
  );
  NOT _0783_ (
    .A(Fifo_Empty_VC0),
    .Y(_0066_)
  );
  NOR _0784_ (
    .A(Fifo_Empty_VC1),
    .B(_0066_),
    .Y(_0067_)
  );
  NAND _0785_ (
    .A(_0067_),
    .B(_0065_),
    .Y(_0068_)
  );
  NAND _0786_ (
    .A(_0068_),
    .B(_0064_),
    .Y(_0002_)
  );
  NOR _0787_ (
    .A(\D0Fifo.num_mem [0]),
    .B(\D0Fifo.num_mem [1]),
    .Y(_0069_)
  );
  NAND _0788_ (
    .A(_0069_),
    .B(\D0Fifo.num_mem [2]),
    .Y(_0070_)
  );
  NAND _0789_ (
    .A(_0070_),
    .B(\D0Fifo.memoria.iWriteEnable ),
    .Y(_0071_)
  );
  NOT _0790_ (
    .A(_0071_),
    .Y(_0072_)
  );
  NOT _0791_ (
    .A(\D0Fifo.num_mem [2]),
    .Y(_0073_)
  );
  NAND _0792_ (
    .A(_0069_),
    .B(_0073_),
    .Y(_0074_)
  );
  NAND _0793_ (
    .A(_0074_),
    .B(pop_D0),
    .Y(_0075_)
  );
  NOR _0794_ (
    .A(_0075_),
    .B(\D0Fifo.memoria.iWriteEnable ),
    .Y(_0076_)
  );
  NOR _0795_ (
    .A(_0076_),
    .B(_0072_),
    .Y(_0077_)
  );
  NOR _0796_ (
    .A(_0077_),
    .B(\D0Fifo.num_mem [0]),
    .Y(_0078_)
  );
  NOT _0797_ (
    .A(pop_D0),
    .Y(_0079_)
  );
  NAND _0798_ (
    .A(\D0Fifo.num_mem [0]),
    .B(_0079_),
    .Y(_0080_)
  );
  NOR _0799_ (
    .A(_0080_),
    .B(\D0Fifo.memoria.iWriteEnable ),
    .Y(_0081_)
  );
  NOR _0800_ (
    .A(_0081_),
    .B(_0078_),
    .Y(_0082_)
  );
  NOR _0801_ (
    .A(_0082_),
    .B(_0057_),
    .Y(_0334_)
  );
  NAND _0802_ (
    .A(\D0Fifo.num_mem [0]),
    .B(\D0Fifo.num_mem [1]),
    .Y(_0083_)
  );
  NOT _0803_ (
    .A(_0083_),
    .Y(_0084_)
  );
  NOR _0804_ (
    .A(_0084_),
    .B(_0069_),
    .Y(_0085_)
  );
  NOR _0805_ (
    .A(_0085_),
    .B(_0075_),
    .Y(_0086_)
  );
  NOT _0806_ (
    .A(\D0Fifo.memoria.iWriteEnable ),
    .Y(_0087_)
  );
  NAND _0807_ (
    .A(\D0Fifo.num_mem [1]),
    .B(_0079_),
    .Y(_0088_)
  );
  NAND _0808_ (
    .A(_0088_),
    .B(_0087_),
    .Y(_0089_)
  );
  NOR _0809_ (
    .A(_0089_),
    .B(_0086_),
    .Y(_0090_)
  );
  NOT _0810_ (
    .A(_0085_),
    .Y(_0091_)
  );
  NAND _0811_ (
    .A(_0091_),
    .B(\D0Fifo.memoria.iWriteEnable ),
    .Y(_0092_)
  );
  NAND _0812_ (
    .A(_0092_),
    .B(reset_L),
    .Y(_0093_)
  );
  NOR _0813_ (
    .A(_0093_),
    .B(_0090_),
    .Y(_0344_)
  );
  NOR _0814_ (
    .A(_0083_),
    .B(\D0Fifo.num_mem [2]),
    .Y(_0095_)
  );
  NOR _0815_ (
    .A(_0084_),
    .B(_0073_),
    .Y(_0096_)
  );
  NOR _0816_ (
    .A(_0096_),
    .B(_0095_),
    .Y(_0097_)
  );
  NOR _0817_ (
    .A(_0097_),
    .B(_0087_),
    .Y(_0098_)
  );
  NAND _0818_ (
    .A(_0069_),
    .B(pop_D0),
    .Y(_0099_)
  );
  NAND _0819_ (
    .A(_0099_),
    .B(\D0Fifo.num_mem [2]),
    .Y(_0100_)
  );
  NOR _0820_ (
    .A(_0100_),
    .B(\D0Fifo.memoria.iWriteEnable ),
    .Y(_0101_)
  );
  NOR _0821_ (
    .A(_0101_),
    .B(_0098_),
    .Y(_0102_)
  );
  NOR _0822_ (
    .A(_0102_),
    .B(_0057_),
    .Y(_0354_)
  );
  NAND _0823_ (
    .A(\D0Fifo.memoria.iWriteEnable ),
    .B(pop_D0),
    .Y(_0103_)
  );
  NAND _0824_ (
    .A(_0103_),
    .B(_0075_),
    .Y(_0104_)
  );
  NOR _0825_ (
    .A(_0104_),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0105_)
  );
  NAND _0826_ (
    .A(_0103_),
    .B(_0057_),
    .Y(_0106_)
  );
  NAND _0827_ (
    .A(_0104_),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0108_)
  );
  NAND _0828_ (
    .A(_0108_),
    .B(_0106_),
    .Y(_0110_)
  );
  NOR _0829_ (
    .A(_0110_),
    .B(_0105_),
    .Y(_0486_)
  );
  NOT _0830_ (
    .A(\D0Fifo.memoria.iReadAddress [1]),
    .Y(_0113_)
  );
  NOR _0831_ (
    .A(_0108_),
    .B(_0113_),
    .Y(_0115_)
  );
  NAND _0832_ (
    .A(_0108_),
    .B(_0113_),
    .Y(_0117_)
  );
  NAND _0833_ (
    .A(_0117_),
    .B(_0106_),
    .Y(_0118_)
  );
  NOR _0834_ (
    .A(_0118_),
    .B(_0115_),
    .Y(_0496_)
  );
  NAND _0835_ (
    .A(_0103_),
    .B(_0071_),
    .Y(_0119_)
  );
  NOR _0836_ (
    .A(_0119_),
    .B(\D0Fifo.memoria.iWriteAddress [0]),
    .Y(_0120_)
  );
  NAND _0837_ (
    .A(_0119_),
    .B(\D0Fifo.memoria.iWriteAddress [0]),
    .Y(_0121_)
  );
  NAND _0838_ (
    .A(_0121_),
    .B(_0106_),
    .Y(_0122_)
  );
  NOR _0839_ (
    .A(_0122_),
    .B(_0120_),
    .Y(_0608_)
  );
  NOT _0840_ (
    .A(\D0Fifo.memoria.iWriteAddress [1]),
    .Y(_0123_)
  );
  NOR _0841_ (
    .A(_0121_),
    .B(_0123_),
    .Y(_0124_)
  );
  NAND _0842_ (
    .A(_0121_),
    .B(_0123_),
    .Y(_0125_)
  );
  NAND _0843_ (
    .A(_0125_),
    .B(_0106_),
    .Y(_0126_)
  );
  NOR _0844_ (
    .A(_0126_),
    .B(_0124_),
    .Y(_0619_)
  );
  NOR _0845_ (
    .A(\D0Fifo.num_mem [1]),
    .B(_0073_),
    .Y(_0127_)
  );
  NOR _0846_ (
    .A(_0127_),
    .B(_0095_),
    .Y(_0128_)
  );
  NOR _0847_ (
    .A(_0128_),
    .B(_0057_),
    .Y(_0669_)
  );
  NOR _0848_ (
    .A(\D0Fifo.memoria.Ram[2] [0]),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0129_)
  );
  NOT _0849_ (
    .A(\D0Fifo.memoria.Ram[3] [0]),
    .Y(_0130_)
  );
  NAND _0850_ (
    .A(_0130_),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0131_)
  );
  NAND _0851_ (
    .A(_0131_),
    .B(\D0Fifo.memoria.iReadAddress [1]),
    .Y(_0132_)
  );
  NOR _0852_ (
    .A(_0132_),
    .B(_0129_),
    .Y(_0133_)
  );
  NOT _0853_ (
    .A(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0134_)
  );
  NOT _0854_ (
    .A(\D0Fifo.memoria.Ram[1] [0]),
    .Y(_0135_)
  );
  NOR _0855_ (
    .A(_0135_),
    .B(_0134_),
    .Y(_0136_)
  );
  NOT _0856_ (
    .A(\D0Fifo.memoria.Ram[0] [0]),
    .Y(_0137_)
  );
  NOR _0857_ (
    .A(_0137_),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0138_)
  );
  NOR _0858_ (
    .A(_0138_),
    .B(_0136_),
    .Y(_0139_)
  );
  NOR _0859_ (
    .A(_0139_),
    .B(\D0Fifo.memoria.iReadAddress [1]),
    .Y(_0141_)
  );
  NOR _0860_ (
    .A(_0141_),
    .B(_0133_),
    .Y(_0143_)
  );
  NOR _0861_ (
    .A(_0143_),
    .B(_0079_),
    .Y(data_out0[0])
  );
  NOR _0862_ (
    .A(\D0Fifo.memoria.Ram[2] [1]),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0145_)
  );
  NOT _0863_ (
    .A(\D0Fifo.memoria.Ram[3] [1]),
    .Y(_0146_)
  );
  NAND _0864_ (
    .A(_0146_),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0147_)
  );
  NAND _0865_ (
    .A(_0147_),
    .B(\D0Fifo.memoria.iReadAddress [1]),
    .Y(_0148_)
  );
  NOR _0866_ (
    .A(_0148_),
    .B(_0145_),
    .Y(_0149_)
  );
  NOT _0867_ (
    .A(\D0Fifo.memoria.Ram[1] [1]),
    .Y(_0150_)
  );
  NOR _0868_ (
    .A(_0150_),
    .B(_0134_),
    .Y(_0151_)
  );
  NOT _0869_ (
    .A(\D0Fifo.memoria.Ram[0] [1]),
    .Y(_0152_)
  );
  NOR _0870_ (
    .A(_0152_),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0153_)
  );
  NOR _0871_ (
    .A(_0153_),
    .B(_0151_),
    .Y(_0154_)
  );
  NOR _0872_ (
    .A(_0154_),
    .B(\D0Fifo.memoria.iReadAddress [1]),
    .Y(_0155_)
  );
  NOR _0873_ (
    .A(_0155_),
    .B(_0149_),
    .Y(_0156_)
  );
  NOR _0874_ (
    .A(_0156_),
    .B(_0079_),
    .Y(data_out0[1])
  );
  NOR _0875_ (
    .A(\D0Fifo.memoria.Ram[2] [2]),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0159_)
  );
  NOT _0876_ (
    .A(\D0Fifo.memoria.Ram[3] [2]),
    .Y(_0160_)
  );
  NAND _0877_ (
    .A(_0160_),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0161_)
  );
  NAND _0878_ (
    .A(_0161_),
    .B(\D0Fifo.memoria.iReadAddress [1]),
    .Y(_0162_)
  );
  NOR _0879_ (
    .A(_0162_),
    .B(_0159_),
    .Y(_0163_)
  );
  NOT _0880_ (
    .A(\D0Fifo.memoria.Ram[1] [2]),
    .Y(_0164_)
  );
  NOR _0881_ (
    .A(_0164_),
    .B(_0134_),
    .Y(_0165_)
  );
  NOT _0882_ (
    .A(\D0Fifo.memoria.Ram[0] [2]),
    .Y(_0166_)
  );
  NOR _0883_ (
    .A(_0166_),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0167_)
  );
  NOR _0884_ (
    .A(_0167_),
    .B(_0165_),
    .Y(_0168_)
  );
  NOR _0885_ (
    .A(_0168_),
    .B(\D0Fifo.memoria.iReadAddress [1]),
    .Y(_0169_)
  );
  NOR _0886_ (
    .A(_0169_),
    .B(_0163_),
    .Y(_0171_)
  );
  NOR _0887_ (
    .A(_0171_),
    .B(_0079_),
    .Y(data_out0[2])
  );
  NOR _0888_ (
    .A(\D0Fifo.memoria.Ram[2] [3]),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0173_)
  );
  NOT _0889_ (
    .A(\D0Fifo.memoria.Ram[3] [3]),
    .Y(_0174_)
  );
  NAND _0890_ (
    .A(_0174_),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0175_)
  );
  NAND _0891_ (
    .A(_0175_),
    .B(\D0Fifo.memoria.iReadAddress [1]),
    .Y(_0176_)
  );
  NOR _0892_ (
    .A(_0176_),
    .B(_0173_),
    .Y(_0177_)
  );
  NOT _0893_ (
    .A(\D0Fifo.memoria.Ram[1] [3]),
    .Y(_0178_)
  );
  NOR _0894_ (
    .A(_0178_),
    .B(_0134_),
    .Y(_0179_)
  );
  NOT _0895_ (
    .A(\D0Fifo.memoria.Ram[0] [3]),
    .Y(_0180_)
  );
  NOR _0896_ (
    .A(_0180_),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0181_)
  );
  NOR _0897_ (
    .A(_0181_),
    .B(_0179_),
    .Y(_0182_)
  );
  NOR _0898_ (
    .A(_0182_),
    .B(\D0Fifo.memoria.iReadAddress [1]),
    .Y(_0183_)
  );
  NOR _0899_ (
    .A(_0183_),
    .B(_0177_),
    .Y(_0184_)
  );
  NOR _0900_ (
    .A(_0184_),
    .B(_0079_),
    .Y(data_out0[3])
  );
  NOR _0901_ (
    .A(\D0Fifo.memoria.Ram[2] [4]),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0185_)
  );
  NOT _0902_ (
    .A(\D0Fifo.memoria.Ram[3] [4]),
    .Y(_0186_)
  );
  NAND _0903_ (
    .A(_0186_),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0187_)
  );
  NAND _0904_ (
    .A(_0187_),
    .B(\D0Fifo.memoria.iReadAddress [1]),
    .Y(_0189_)
  );
  NOR _0905_ (
    .A(_0189_),
    .B(_0185_),
    .Y(_0190_)
  );
  NOT _0906_ (
    .A(\D0Fifo.memoria.Ram[1] [4]),
    .Y(_0192_)
  );
  NOR _0907_ (
    .A(_0192_),
    .B(_0134_),
    .Y(_0193_)
  );
  NOT _0908_ (
    .A(\D0Fifo.memoria.Ram[0] [4]),
    .Y(_0194_)
  );
  NOR _0909_ (
    .A(_0194_),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0196_)
  );
  NOR _0910_ (
    .A(_0196_),
    .B(_0193_),
    .Y(_0197_)
  );
  NOR _0911_ (
    .A(_0197_),
    .B(\D0Fifo.memoria.iReadAddress [1]),
    .Y(_0199_)
  );
  NOR _0912_ (
    .A(_0199_),
    .B(_0190_),
    .Y(_0200_)
  );
  NOR _0913_ (
    .A(_0200_),
    .B(_0079_),
    .Y(data_out0[4])
  );
  NOR _0914_ (
    .A(\D0Fifo.memoria.Ram[2] [5]),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0202_)
  );
  NOT _0915_ (
    .A(\D0Fifo.memoria.Ram[3] [5]),
    .Y(_0203_)
  );
  NAND _0916_ (
    .A(_0203_),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0205_)
  );
  NAND _0917_ (
    .A(_0205_),
    .B(\D0Fifo.memoria.iReadAddress [1]),
    .Y(_0206_)
  );
  NOR _0918_ (
    .A(_0206_),
    .B(_0202_),
    .Y(_0207_)
  );
  NOT _0919_ (
    .A(\D0Fifo.memoria.Ram[1] [5]),
    .Y(_0209_)
  );
  NOR _0920_ (
    .A(_0209_),
    .B(_0134_),
    .Y(_0210_)
  );
  NOT _0921_ (
    .A(\D0Fifo.memoria.Ram[0] [5]),
    .Y(_0212_)
  );
  NOR _0922_ (
    .A(_0212_),
    .B(\D0Fifo.memoria.iReadAddress [0]),
    .Y(_0213_)
  );
  NOR _0923_ (
    .A(_0213_),
    .B(_0210_),
    .Y(_0214_)
  );
  NOR _0924_ (
    .A(_0214_),
    .B(\D0Fifo.memoria.iReadAddress [1]),
    .Y(_0215_)
  );
  NOR _0925_ (
    .A(_0215_),
    .B(_0207_),
    .Y(_0216_)
  );
  NOR _0926_ (
    .A(_0216_),
    .B(_0079_),
    .Y(data_out0[5])
  );
  NOR _0927_ (
    .A(_0123_),
    .B(_0087_),
    .Y(_0217_)
  );
  NAND _0928_ (
    .A(_0217_),
    .B(\D0Fifo.memoria.iWriteAddress [0]),
    .Y(_0218_)
  );
  NOT _0929_ (
    .A(_0218_),
    .Y(_0219_)
  );
  NAND _0930_ (
    .A(_0219_),
    .B(\D0Fifo.Fifo_Data_in [0]),
    .Y(_0220_)
  );
  NAND _0931_ (
    .A(_0218_),
    .B(\D0Fifo.memoria.Ram[3] [0]),
    .Y(_0221_)
  );
  NAND _0932_ (
    .A(_0221_),
    .B(_0220_),
    .Y(_0027_)
  );
  NAND _0933_ (
    .A(_0219_),
    .B(\D0Fifo.Fifo_Data_in [1]),
    .Y(_0222_)
  );
  NAND _0934_ (
    .A(_0218_),
    .B(\D0Fifo.memoria.Ram[3] [1]),
    .Y(_0223_)
  );
  NAND _0935_ (
    .A(_0223_),
    .B(_0222_),
    .Y(_0028_)
  );
  NAND _0936_ (
    .A(_0219_),
    .B(\D0Fifo.Fifo_Data_in [2]),
    .Y(_0224_)
  );
  NAND _0937_ (
    .A(_0218_),
    .B(\D0Fifo.memoria.Ram[3] [2]),
    .Y(_0225_)
  );
  NAND _0938_ (
    .A(_0225_),
    .B(_0224_),
    .Y(_0029_)
  );
  NAND _0939_ (
    .A(_0219_),
    .B(\D0Fifo.Fifo_Data_in [3]),
    .Y(_0226_)
  );
  NAND _0940_ (
    .A(_0218_),
    .B(\D0Fifo.memoria.Ram[3] [3]),
    .Y(_0227_)
  );
  NAND _0941_ (
    .A(_0227_),
    .B(_0226_),
    .Y(_0030_)
  );
  NAND _0942_ (
    .A(_0219_),
    .B(\D0Fifo.Fifo_Data_in [4]),
    .Y(_0228_)
  );
  NAND _0943_ (
    .A(_0218_),
    .B(\D0Fifo.memoria.Ram[3] [4]),
    .Y(_0229_)
  );
  NAND _0944_ (
    .A(_0229_),
    .B(_0228_),
    .Y(_0031_)
  );
  NAND _0945_ (
    .A(_0219_),
    .B(\D0Fifo.Fifo_Data_in [5]),
    .Y(_0230_)
  );
  NAND _0946_ (
    .A(_0218_),
    .B(\D0Fifo.memoria.Ram[3] [5]),
    .Y(_0231_)
  );
  NAND _0947_ (
    .A(_0231_),
    .B(_0230_),
    .Y(_0032_)
  );
  NOR _0948_ (
    .A(\D0Fifo.memoria.iWriteAddress [0]),
    .B(_0087_),
    .Y(_0232_)
  );
  NAND _0949_ (
    .A(_0232_),
    .B(\D0Fifo.memoria.iWriteAddress [1]),
    .Y(_0233_)
  );
  NOT _0950_ (
    .A(_0233_),
    .Y(_0234_)
  );
  NAND _0951_ (
    .A(_0234_),
    .B(\D0Fifo.Fifo_Data_in [0]),
    .Y(_0235_)
  );
  NAND _0952_ (
    .A(_0233_),
    .B(\D0Fifo.memoria.Ram[2] [0]),
    .Y(_0236_)
  );
  NAND _0953_ (
    .A(_0236_),
    .B(_0235_),
    .Y(_0033_)
  );
  NAND _0954_ (
    .A(_0234_),
    .B(\D0Fifo.Fifo_Data_in [1]),
    .Y(_0237_)
  );
  NAND _0955_ (
    .A(_0233_),
    .B(\D0Fifo.memoria.Ram[2] [1]),
    .Y(_0238_)
  );
  NAND _0956_ (
    .A(_0238_),
    .B(_0237_),
    .Y(_0034_)
  );
  NAND _0957_ (
    .A(_0234_),
    .B(\D0Fifo.Fifo_Data_in [2]),
    .Y(_0239_)
  );
  NAND _0958_ (
    .A(_0233_),
    .B(\D0Fifo.memoria.Ram[2] [2]),
    .Y(_0240_)
  );
  NAND _0959_ (
    .A(_0240_),
    .B(_0239_),
    .Y(_0035_)
  );
  NAND _0960_ (
    .A(_0234_),
    .B(\D0Fifo.Fifo_Data_in [3]),
    .Y(_0241_)
  );
  NAND _0961_ (
    .A(_0233_),
    .B(\D0Fifo.memoria.Ram[2] [3]),
    .Y(_0242_)
  );
  NAND _0962_ (
    .A(_0242_),
    .B(_0241_),
    .Y(_0036_)
  );
  NAND _0963_ (
    .A(_0234_),
    .B(\D0Fifo.Fifo_Data_in [4]),
    .Y(_0243_)
  );
  NAND _0964_ (
    .A(_0233_),
    .B(\D0Fifo.memoria.Ram[2] [4]),
    .Y(_0244_)
  );
  NAND _0965_ (
    .A(_0244_),
    .B(_0243_),
    .Y(_0037_)
  );
  NAND _0966_ (
    .A(_0234_),
    .B(\D0Fifo.Fifo_Data_in [5]),
    .Y(_0245_)
  );
  NAND _0967_ (
    .A(_0233_),
    .B(\D0Fifo.memoria.Ram[2] [5]),
    .Y(_0246_)
  );
  NAND _0968_ (
    .A(_0246_),
    .B(_0245_),
    .Y(_0038_)
  );
  NOT _0969_ (
    .A(\D0Fifo.memoria.iWriteAddress [0]),
    .Y(_0247_)
  );
  NOR _0970_ (
    .A(_0247_),
    .B(_0087_),
    .Y(_0248_)
  );
  NAND _0971_ (
    .A(_0248_),
    .B(_0123_),
    .Y(_0249_)
  );
  NOT _0972_ (
    .A(_0249_),
    .Y(_0250_)
  );
  NAND _0973_ (
    .A(_0250_),
    .B(\D0Fifo.Fifo_Data_in [0]),
    .Y(_0251_)
  );
  NAND _0974_ (
    .A(_0249_),
    .B(\D0Fifo.memoria.Ram[1] [0]),
    .Y(_0252_)
  );
  NAND _0975_ (
    .A(_0252_),
    .B(_0251_),
    .Y(_0039_)
  );
  NAND _0976_ (
    .A(_0250_),
    .B(\D0Fifo.Fifo_Data_in [1]),
    .Y(_0253_)
  );
  NAND _0977_ (
    .A(_0249_),
    .B(\D0Fifo.memoria.Ram[1] [1]),
    .Y(_0254_)
  );
  NAND _0978_ (
    .A(_0254_),
    .B(_0253_),
    .Y(_0040_)
  );
  NAND _0979_ (
    .A(_0250_),
    .B(\D0Fifo.Fifo_Data_in [2]),
    .Y(_0257_)
  );
  NAND _0980_ (
    .A(_0249_),
    .B(\D0Fifo.memoria.Ram[1] [2]),
    .Y(_0259_)
  );
  NAND _0981_ (
    .A(_0259_),
    .B(_0257_),
    .Y(_0041_)
  );
  NAND _0982_ (
    .A(_0250_),
    .B(\D0Fifo.Fifo_Data_in [3]),
    .Y(_0262_)
  );
  NAND _0983_ (
    .A(_0249_),
    .B(\D0Fifo.memoria.Ram[1] [3]),
    .Y(_0263_)
  );
  NAND _0984_ (
    .A(_0263_),
    .B(_0262_),
    .Y(_0042_)
  );
  NAND _0985_ (
    .A(_0250_),
    .B(\D0Fifo.Fifo_Data_in [4]),
    .Y(_0264_)
  );
  NAND _0986_ (
    .A(_0249_),
    .B(\D0Fifo.memoria.Ram[1] [4]),
    .Y(_0265_)
  );
  NAND _0987_ (
    .A(_0265_),
    .B(_0264_),
    .Y(_0043_)
  );
  NAND _0988_ (
    .A(_0250_),
    .B(\D0Fifo.Fifo_Data_in [5]),
    .Y(_0266_)
  );
  NAND _0989_ (
    .A(_0249_),
    .B(\D0Fifo.memoria.Ram[1] [5]),
    .Y(_0267_)
  );
  NAND _0990_ (
    .A(_0267_),
    .B(_0266_),
    .Y(_0044_)
  );
  NAND _0991_ (
    .A(_0232_),
    .B(_0123_),
    .Y(_0268_)
  );
  NOT _0992_ (
    .A(_0268_),
    .Y(_0269_)
  );
  NAND _0993_ (
    .A(_0269_),
    .B(\D0Fifo.Fifo_Data_in [0]),
    .Y(_0270_)
  );
  NAND _0994_ (
    .A(_0268_),
    .B(\D0Fifo.memoria.Ram[0] [0]),
    .Y(_0271_)
  );
  NAND _0995_ (
    .A(_0271_),
    .B(_0270_),
    .Y(_0045_)
  );
  NAND _0996_ (
    .A(_0269_),
    .B(\D0Fifo.Fifo_Data_in [1]),
    .Y(_0274_)
  );
  NAND _0997_ (
    .A(_0268_),
    .B(\D0Fifo.memoria.Ram[0] [1]),
    .Y(_0275_)
  );
  NAND _0998_ (
    .A(_0275_),
    .B(_0274_),
    .Y(_0046_)
  );
  NAND _0999_ (
    .A(_0269_),
    .B(\D0Fifo.Fifo_Data_in [2]),
    .Y(_0276_)
  );
  NAND _1000_ (
    .A(_0268_),
    .B(\D0Fifo.memoria.Ram[0] [2]),
    .Y(_0277_)
  );
  NAND _1001_ (
    .A(_0277_),
    .B(_0276_),
    .Y(_0047_)
  );
  NAND _1002_ (
    .A(_0269_),
    .B(\D0Fifo.Fifo_Data_in [3]),
    .Y(_0278_)
  );
  NAND _1003_ (
    .A(_0268_),
    .B(\D0Fifo.memoria.Ram[0] [3]),
    .Y(_0279_)
  );
  NAND _1004_ (
    .A(_0279_),
    .B(_0278_),
    .Y(_0048_)
  );
  NAND _1005_ (
    .A(_0269_),
    .B(\D0Fifo.Fifo_Data_in [4]),
    .Y(_0280_)
  );
  NAND _1006_ (
    .A(_0268_),
    .B(\D0Fifo.memoria.Ram[0] [4]),
    .Y(_0281_)
  );
  NAND _1007_ (
    .A(_0281_),
    .B(_0280_),
    .Y(_0049_)
  );
  NAND _1008_ (
    .A(_0269_),
    .B(\D0Fifo.Fifo_Data_in [5]),
    .Y(_0284_)
  );
  NAND _1009_ (
    .A(_0268_),
    .B(\D0Fifo.memoria.Ram[0] [5]),
    .Y(_0286_)
  );
  NAND _1010_ (
    .A(_0286_),
    .B(_0284_),
    .Y(_0050_)
  );
  NOT _1011_ (
    .A(\D1Fifo.num_mem [0]),
    .Y(_0287_)
  );
  NOR _1012_ (
    .A(\D1Fifo.num_mem [1]),
    .B(\D1Fifo.num_mem [2]),
    .Y(_0288_)
  );
  NAND _1013_ (
    .A(_0288_),
    .B(_0287_),
    .Y(_0289_)
  );
  NOT _1014_ (
    .A(_0289_),
    .Y(_0290_)
  );
  NOT _1015_ (
    .A(pop_D1),
    .Y(_0291_)
  );
  NAND _1016_ (
    .A(\D1Fifo.num_mem [0]),
    .B(_0291_),
    .Y(_0292_)
  );
  NOR _1017_ (
    .A(\D1Fifo.num_mem [0]),
    .B(_0291_),
    .Y(_0293_)
  );
  NOT _1018_ (
    .A(_0293_),
    .Y(_0294_)
  );
  NAND _1019_ (
    .A(_0294_),
    .B(_0292_),
    .Y(_0295_)
  );
  NAND _1020_ (
    .A(_0295_),
    .B(reset_L),
    .Y(_0296_)
  );
  NOR _1021_ (
    .A(_0296_),
    .B(_0290_),
    .Y(_0051_)
  );
  NOT _1022_ (
    .A(\D1Fifo.num_mem [1]),
    .Y(_0297_)
  );
  NOR _1023_ (
    .A(_0297_),
    .B(_0057_),
    .Y(_0298_)
  );
  NOR _1024_ (
    .A(_0298_),
    .B(_0293_),
    .Y(_0299_)
  );
  NOT _1025_ (
    .A(\D1Fifo.num_mem [2]),
    .Y(_0300_)
  );
  NOR _1026_ (
    .A(_0300_),
    .B(_0057_),
    .Y(_0301_)
  );
  NOT _1027_ (
    .A(_0301_),
    .Y(_0302_)
  );
  NOR _1028_ (
    .A(_0302_),
    .B(\D1Fifo.num_mem [1]),
    .Y(_0303_)
  );
  NOR _1029_ (
    .A(_0303_),
    .B(_0294_),
    .Y(_0304_)
  );
  NOR _1030_ (
    .A(_0304_),
    .B(_0299_),
    .Y(_0052_)
  );
  NOR _1031_ (
    .A(_0294_),
    .B(\D1Fifo.num_mem [1]),
    .Y(_0305_)
  );
  NOR _1032_ (
    .A(_0305_),
    .B(_0302_),
    .Y(_0053_)
  );
  NOR _1033_ (
    .A(_0290_),
    .B(_0291_),
    .Y(_0306_)
  );
  NAND _1034_ (
    .A(_0306_),
    .B(\D1Fifo.memoria.iReadAddress [0]),
    .Y(_0308_)
  );
  NOT _1035_ (
    .A(_0308_),
    .Y(_0309_)
  );
  NOT _1036_ (
    .A(\D1Fifo.memoria.iReadAddress [0]),
    .Y(_0310_)
  );
  NOT _1037_ (
    .A(_0306_),
    .Y(_0312_)
  );
  NAND _1038_ (
    .A(_0312_),
    .B(_0310_),
    .Y(_0313_)
  );
  NAND _1039_ (
    .A(_0313_),
    .B(reset_L),
    .Y(_0314_)
  );
  NOR _1040_ (
    .A(_0314_),
    .B(_0309_),
    .Y(_0054_)
  );
  NOT _1041_ (
    .A(\D1Fifo.memoria.iReadAddress [1]),
    .Y(_0316_)
  );
  NOR _1042_ (
    .A(_0308_),
    .B(_0316_),
    .Y(_0317_)
  );
  NAND _1043_ (
    .A(_0308_),
    .B(_0316_),
    .Y(_0319_)
  );
  NAND _1044_ (
    .A(_0319_),
    .B(reset_L),
    .Y(_0320_)
  );
  NOR _1045_ (
    .A(_0320_),
    .B(_0317_),
    .Y(_0055_)
  );
  NOT _1046_ (
    .A(_0303_),
    .Y(_0321_)
  );
  NOR _1047_ (
    .A(_0287_),
    .B(\D1Fifo.num_mem [2]),
    .Y(_0322_)
  );
  NAND _1048_ (
    .A(_0322_),
    .B(_0298_),
    .Y(_0323_)
  );
  NAND _1049_ (
    .A(_0323_),
    .B(_0321_),
    .Y(_0056_)
  );
  NOT _1050_ (
    .A(\Demux_D0_D1.valid_in ),
    .Y(_0324_)
  );
  NOR _1051_ (
    .A(_0324_),
    .B(_0057_),
    .Y(_0094_)
  );
  NAND _1052_ (
    .A(_0094_),
    .B(\Demux_D0_D1.data_in [0]),
    .Y(_0325_)
  );
  NOR _1053_ (
    .A(_0087_),
    .B(_0057_),
    .Y(_0326_)
  );
  NAND _1054_ (
    .A(_0326_),
    .B(_0324_),
    .Y(_0327_)
  );
  NOT _1055_ (
    .A(_0327_),
    .Y(_0328_)
  );
  NAND _1056_ (
    .A(_0328_),
    .B(\D0Fifo.Fifo_Data_in [0]),
    .Y(_0329_)
  );
  NAND _1057_ (
    .A(_0329_),
    .B(_0325_),
    .Y(_0107_)
  );
  NOT _1058_ (
    .A(\D0Fifo.Fifo_Data_in [1]),
    .Y(_0330_)
  );
  NOR _1059_ (
    .A(_0327_),
    .B(_0330_),
    .Y(_0109_)
  );
  NOT _1060_ (
    .A(\D0Fifo.Fifo_Data_in [2]),
    .Y(_0331_)
  );
  NOR _1061_ (
    .A(_0327_),
    .B(_0331_),
    .Y(_0111_)
  );
  NOT _1062_ (
    .A(\D0Fifo.Fifo_Data_in [3]),
    .Y(_0332_)
  );
  NOR _1063_ (
    .A(_0327_),
    .B(_0332_),
    .Y(_0112_)
  );
  NOT _1064_ (
    .A(\D0Fifo.Fifo_Data_in [4]),
    .Y(_0333_)
  );
  NOR _1065_ (
    .A(_0327_),
    .B(_0333_),
    .Y(_0114_)
  );
  NOT _1066_ (
    .A(\D0Fifo.Fifo_Data_in [5]),
    .Y(_0335_)
  );
  NOR _1067_ (
    .A(_0327_),
    .B(_0335_),
    .Y(_0116_)
  );
  NOR _1068_ (
    .A(\MainFifo.num_mem [1]),
    .B(\MainFifo.num_mem [0]),
    .Y(_0336_)
  );
  NAND _1069_ (
    .A(_0336_),
    .B(\MainFifo.num_mem [2]),
    .Y(_0337_)
  );
  NAND _1070_ (
    .A(_0337_),
    .B(push),
    .Y(_0338_)
  );
  NOT _1071_ (
    .A(\MainFifo.num_mem [2]),
    .Y(_0339_)
  );
  NAND _1072_ (
    .A(_0336_),
    .B(_0339_),
    .Y(_0340_)
  );
  NOR _1073_ (
    .A(pop_D1),
    .B(pop_D0),
    .Y(_0341_)
  );
  NOR _1074_ (
    .A(_0341_),
    .B(push),
    .Y(_0342_)
  );
  NAND _1075_ (
    .A(_0342_),
    .B(_0340_),
    .Y(_0343_)
  );
  NAND _1076_ (
    .A(_0343_),
    .B(_0338_),
    .Y(_0345_)
  );
  NOR _1077_ (
    .A(_0345_),
    .B(\MainFifo.num_mem [0]),
    .Y(_0346_)
  );
  NOT _1078_ (
    .A(_0341_),
    .Y(_0347_)
  );
  NOR _1079_ (
    .A(_0347_),
    .B(push),
    .Y(_0348_)
  );
  NOT _1080_ (
    .A(_0348_),
    .Y(_0349_)
  );
  NAND _1081_ (
    .A(_0349_),
    .B(\MainFifo.num_mem [0]),
    .Y(_0350_)
  );
  NAND _1082_ (
    .A(_0350_),
    .B(reset_L),
    .Y(_0351_)
  );
  NOR _1083_ (
    .A(_0351_),
    .B(_0346_),
    .Y(_0140_)
  );
  NOT _1084_ (
    .A(\MainFifo.num_mem [0]),
    .Y(_0352_)
  );
  NOT _1085_ (
    .A(\MainFifo.num_mem [1]),
    .Y(_0353_)
  );
  NOR _1086_ (
    .A(_0353_),
    .B(_0352_),
    .Y(_0355_)
  );
  NOR _1087_ (
    .A(_0355_),
    .B(_0336_),
    .Y(_0356_)
  );
  NOR _1088_ (
    .A(_0356_),
    .B(_0343_),
    .Y(_0357_)
  );
  NAND _1089_ (
    .A(_0348_),
    .B(\MainFifo.num_mem [1]),
    .Y(_0358_)
  );
  NAND _1090_ (
    .A(_0356_),
    .B(push),
    .Y(_0359_)
  );
  NAND _1091_ (
    .A(_0359_),
    .B(_0358_),
    .Y(_0361_)
  );
  NOR _1092_ (
    .A(_0361_),
    .B(_0357_),
    .Y(_0363_)
  );
  NOR _1093_ (
    .A(_0363_),
    .B(_0057_),
    .Y(_0142_)
  );
  NAND _1094_ (
    .A(_0355_),
    .B(push),
    .Y(_0366_)
  );
  NOR _1095_ (
    .A(_0366_),
    .B(\MainFifo.num_mem [2]),
    .Y(_0368_)
  );
  NOT _1096_ (
    .A(push),
    .Y(_0369_)
  );
  NAND _1097_ (
    .A(_0336_),
    .B(_0369_),
    .Y(_0370_)
  );
  NOR _1098_ (
    .A(_0370_),
    .B(_0341_),
    .Y(_0371_)
  );
  NAND _1099_ (
    .A(_0366_),
    .B(\MainFifo.num_mem [2]),
    .Y(_0372_)
  );
  NOR _1100_ (
    .A(_0372_),
    .B(_0371_),
    .Y(_0373_)
  );
  NOR _1101_ (
    .A(_0373_),
    .B(_0368_),
    .Y(_0374_)
  );
  NOR _1102_ (
    .A(_0374_),
    .B(_0057_),
    .Y(_0144_)
  );
  NAND _1103_ (
    .A(_0347_),
    .B(_0340_),
    .Y(_0375_)
  );
  NAND _1104_ (
    .A(_0347_),
    .B(push),
    .Y(_0376_)
  );
  NAND _1105_ (
    .A(_0376_),
    .B(_0375_),
    .Y(_0377_)
  );
  NOR _1106_ (
    .A(_0377_),
    .B(\MainFifo.memoria.iReadAddress [0]),
    .Y(_0378_)
  );
  NAND _1107_ (
    .A(_0376_),
    .B(_0057_),
    .Y(_0379_)
  );
  NAND _1108_ (
    .A(_0377_),
    .B(\MainFifo.memoria.iReadAddress [0]),
    .Y(_0381_)
  );
  NAND _1109_ (
    .A(_0381_),
    .B(_0379_),
    .Y(_0383_)
  );
  NOR _1110_ (
    .A(_0383_),
    .B(_0378_),
    .Y(_0157_)
  );
  NOT _1111_ (
    .A(\MainFifo.memoria.iReadAddress [1]),
    .Y(_0384_)
  );
  NOR _1112_ (
    .A(_0381_),
    .B(_0384_),
    .Y(_0385_)
  );
  NAND _1113_ (
    .A(_0381_),
    .B(_0384_),
    .Y(_0386_)
  );
  NAND _1114_ (
    .A(_0386_),
    .B(_0379_),
    .Y(_0387_)
  );
  NOR _1115_ (
    .A(_0387_),
    .B(_0385_),
    .Y(_0158_)
  );
  NAND _1116_ (
    .A(_0376_),
    .B(_0338_),
    .Y(_0388_)
  );
  NOR _1117_ (
    .A(_0388_),
    .B(\MainFifo.memoria.iWriteAddress [0]),
    .Y(_0389_)
  );
  NAND _1118_ (
    .A(_0388_),
    .B(\MainFifo.memoria.iWriteAddress [0]),
    .Y(_0390_)
  );
  NAND _1119_ (
    .A(_0390_),
    .B(_0379_),
    .Y(_0391_)
  );
  NOR _1120_ (
    .A(_0391_),
    .B(_0389_),
    .Y(_0170_)
  );
  NOT _1121_ (
    .A(\MainFifo.memoria.iWriteAddress [1]),
    .Y(_0394_)
  );
  NOR _1122_ (
    .A(_0390_),
    .B(_0394_),
    .Y(_0396_)
  );
  NAND _1123_ (
    .A(_0390_),
    .B(_0394_),
    .Y(_0397_)
  );
  NAND _1124_ (
    .A(_0397_),
    .B(_0379_),
    .Y(_0398_)
  );
  NOR _1125_ (
    .A(_0398_),
    .B(_0396_),
    .Y(_0172_)
  );
  NOR _1126_ (
    .A(_0394_),
    .B(_0369_),
    .Y(_0399_)
  );
  NAND _1127_ (
    .A(_0399_),
    .B(\MainFifo.memoria.iWriteAddress [0]),
    .Y(_0400_)
  );
  NOT _1128_ (
    .A(_0400_),
    .Y(_0401_)
  );
  NAND _1129_ (
    .A(_0401_),
    .B(data_in_principal[0]),
    .Y(_0402_)
  );
  NAND _1130_ (
    .A(_0400_),
    .B(\MainFifo.memoria.Ram[3] [0]),
    .Y(_0403_)
  );
  NAND _1131_ (
    .A(_0403_),
    .B(_0402_),
    .Y(_0188_)
  );
  NAND _1132_ (
    .A(_0401_),
    .B(data_in_principal[5]),
    .Y(_0404_)
  );
  NAND _1133_ (
    .A(_0400_),
    .B(\MainFifo.memoria.Ram[3] [5]),
    .Y(_0405_)
  );
  NAND _1134_ (
    .A(_0405_),
    .B(_0404_),
    .Y(_0191_)
  );
  NOT _1135_ (
    .A(\MainFifo.memoria.iWriteAddress [0]),
    .Y(_0406_)
  );
  NAND _1136_ (
    .A(_0399_),
    .B(_0406_),
    .Y(_0407_)
  );
  NOT _1137_ (
    .A(_0407_),
    .Y(_0408_)
  );
  NAND _1138_ (
    .A(_0408_),
    .B(data_in_principal[0]),
    .Y(_0409_)
  );
  NAND _1139_ (
    .A(_0407_),
    .B(\MainFifo.memoria.Ram[2] [0]),
    .Y(_0410_)
  );
  NAND _1140_ (
    .A(_0410_),
    .B(_0409_),
    .Y(_0195_)
  );
  NAND _1141_ (
    .A(_0408_),
    .B(data_in_principal[5]),
    .Y(_0411_)
  );
  NAND _1142_ (
    .A(_0407_),
    .B(\MainFifo.memoria.Ram[2] [5]),
    .Y(_0412_)
  );
  NAND _1143_ (
    .A(_0412_),
    .B(_0411_),
    .Y(_0198_)
  );
  NOR _1144_ (
    .A(\MainFifo.memoria.iWriteAddress [1]),
    .B(_0369_),
    .Y(_0413_)
  );
  NAND _1145_ (
    .A(_0413_),
    .B(\MainFifo.memoria.iWriteAddress [0]),
    .Y(_0414_)
  );
  NOT _1146_ (
    .A(_0414_),
    .Y(_0415_)
  );
  NAND _1147_ (
    .A(_0415_),
    .B(data_in_principal[0]),
    .Y(_0417_)
  );
  NAND _1148_ (
    .A(_0414_),
    .B(\MainFifo.memoria.Ram[1] [0]),
    .Y(_0418_)
  );
  NAND _1149_ (
    .A(_0418_),
    .B(_0417_),
    .Y(_0201_)
  );
  NAND _1150_ (
    .A(_0415_),
    .B(data_in_principal[5]),
    .Y(_0420_)
  );
  NAND _1151_ (
    .A(_0414_),
    .B(\MainFifo.memoria.Ram[1] [5]),
    .Y(_0421_)
  );
  NAND _1152_ (
    .A(_0421_),
    .B(_0420_),
    .Y(_0204_)
  );
  NAND _1153_ (
    .A(_0413_),
    .B(_0406_),
    .Y(_0423_)
  );
  NOT _1154_ (
    .A(_0423_),
    .Y(_0424_)
  );
  NAND _1155_ (
    .A(_0424_),
    .B(data_in_principal[0]),
    .Y(_0425_)
  );
  NAND _1156_ (
    .A(_0423_),
    .B(\MainFifo.memoria.Ram[0] [0]),
    .Y(_0427_)
  );
  NAND _1157_ (
    .A(_0427_),
    .B(_0425_),
    .Y(_0208_)
  );
  NAND _1158_ (
    .A(_0424_),
    .B(data_in_principal[5]),
    .Y(_0428_)
  );
  NAND _1159_ (
    .A(_0423_),
    .B(\MainFifo.memoria.Ram[0] [5]),
    .Y(_0429_)
  );
  NAND _1160_ (
    .A(_0429_),
    .B(_0428_),
    .Y(_0211_)
  );
  NOT _1161_ (
    .A(\VC0Fifo.memoria.iWriteEnable ),
    .Y(_0430_)
  );
  NOT _1162_ (
    .A(\VC0Fifo.num_mem [2]),
    .Y(_0431_)
  );
  NOR _1163_ (
    .A(\VC0Fifo.num_mem [4]),
    .B(\VC0Fifo.num_mem [3]),
    .Y(_0432_)
  );
  NOR _1164_ (
    .A(\VC0Fifo.num_mem [1]),
    .B(\VC0Fifo.num_mem [0]),
    .Y(_0433_)
  );
  NAND _1165_ (
    .A(_0433_),
    .B(_0432_),
    .Y(_0434_)
  );
  NOR _1166_ (
    .A(_0434_),
    .B(_0431_),
    .Y(_0435_)
  );
  NOR _1167_ (
    .A(_0435_),
    .B(_0430_),
    .Y(_0437_)
  );
  NOT _1168_ (
    .A(\VC0Fifo.num_mem [3]),
    .Y(_0438_)
  );
  NOT _1169_ (
    .A(\VC0Fifo.num_mem [4]),
    .Y(_0439_)
  );
  NAND _1170_ (
    .A(_0439_),
    .B(_0438_),
    .Y(_0441_)
  );
  NOT _1171_ (
    .A(\VC0Fifo.num_mem [0]),
    .Y(_0442_)
  );
  NOT _1172_ (
    .A(\VC0Fifo.num_mem [1]),
    .Y(_0443_)
  );
  NAND _1173_ (
    .A(_0443_),
    .B(_0442_),
    .Y(_0444_)
  );
  NOR _1174_ (
    .A(_0444_),
    .B(_0441_),
    .Y(_0446_)
  );
  NAND _1175_ (
    .A(_0446_),
    .B(_0431_),
    .Y(_0447_)
  );
  NAND _1176_ (
    .A(_0447_),
    .B(\VC0Fifo.memoria.iReadEnable ),
    .Y(_0448_)
  );
  NOR _1177_ (
    .A(_0448_),
    .B(\VC0Fifo.memoria.iWriteEnable ),
    .Y(_0449_)
  );
  NOR _1178_ (
    .A(_0449_),
    .B(_0437_),
    .Y(_0451_)
  );
  NOR _1179_ (
    .A(_0451_),
    .B(\VC0Fifo.num_mem [0]),
    .Y(_0452_)
  );
  NAND _1180_ (
    .A(_0430_),
    .B(\VC0Fifo.num_mem [0]),
    .Y(_0453_)
  );
  NOR _1181_ (
    .A(_0453_),
    .B(\VC0Fifo.memoria.iReadEnable ),
    .Y(_0454_)
  );
  NOR _1182_ (
    .A(_0454_),
    .B(_0452_),
    .Y(_0455_)
  );
  NOR _1183_ (
    .A(_0455_),
    .B(_0057_),
    .Y(_0255_)
  );
  NAND _1184_ (
    .A(\VC0Fifo.num_mem [1]),
    .B(\VC0Fifo.num_mem [0]),
    .Y(_0456_)
  );
  NOT _1185_ (
    .A(_0456_),
    .Y(_0457_)
  );
  NOR _1186_ (
    .A(_0457_),
    .B(_0433_),
    .Y(_0458_)
  );
  NOR _1187_ (
    .A(_0458_),
    .B(_0448_),
    .Y(_0459_)
  );
  NOT _1188_ (
    .A(\VC0Fifo.memoria.iReadEnable ),
    .Y(_0460_)
  );
  NAND _1189_ (
    .A(_0460_),
    .B(\VC0Fifo.num_mem [1]),
    .Y(_0461_)
  );
  NAND _1190_ (
    .A(_0461_),
    .B(_0430_),
    .Y(_0462_)
  );
  NOR _1191_ (
    .A(_0462_),
    .B(_0459_),
    .Y(_0463_)
  );
  NOT _1192_ (
    .A(_0458_),
    .Y(_0464_)
  );
  NAND _1193_ (
    .A(_0464_),
    .B(\VC0Fifo.memoria.iWriteEnable ),
    .Y(_0465_)
  );
  NAND _1194_ (
    .A(_0465_),
    .B(reset_L),
    .Y(_0466_)
  );
  NOR _1195_ (
    .A(_0466_),
    .B(_0463_),
    .Y(_0256_)
  );
  NAND _1196_ (
    .A(_0433_),
    .B(\VC0Fifo.memoria.iReadEnable ),
    .Y(_0467_)
  );
  NAND _1197_ (
    .A(_0467_),
    .B(\VC0Fifo.num_mem [2]),
    .Y(_0468_)
  );
  NOR _1198_ (
    .A(_0467_),
    .B(\VC0Fifo.num_mem [2]),
    .Y(_0469_)
  );
  NAND _1199_ (
    .A(_0469_),
    .B(_0441_),
    .Y(_0470_)
  );
  NAND _1200_ (
    .A(_0470_),
    .B(_0468_),
    .Y(_0471_)
  );
  NOR _1201_ (
    .A(_0471_),
    .B(\VC0Fifo.memoria.iWriteEnable ),
    .Y(_0472_)
  );
  NAND _1202_ (
    .A(_0456_),
    .B(_0431_),
    .Y(_0473_)
  );
  NOR _1203_ (
    .A(_0456_),
    .B(_0431_),
    .Y(_0474_)
  );
  NOT _1204_ (
    .A(_0474_),
    .Y(_0475_)
  );
  NAND _1205_ (
    .A(_0475_),
    .B(_0473_),
    .Y(_0476_)
  );
  NAND _1206_ (
    .A(_0476_),
    .B(\VC0Fifo.memoria.iWriteEnable ),
    .Y(_0477_)
  );
  NAND _1207_ (
    .A(_0477_),
    .B(reset_L),
    .Y(_0478_)
  );
  NOR _1208_ (
    .A(_0478_),
    .B(_0472_),
    .Y(_0258_)
  );
  NOR _1209_ (
    .A(_0469_),
    .B(_0438_),
    .Y(_0479_)
  );
  NAND _1210_ (
    .A(_0469_),
    .B(_0438_),
    .Y(_0480_)
  );
  NOR _1211_ (
    .A(_0480_),
    .B(_0439_),
    .Y(_0481_)
  );
  NOR _1212_ (
    .A(_0481_),
    .B(_0479_),
    .Y(_0482_)
  );
  NOR _1213_ (
    .A(_0482_),
    .B(\VC0Fifo.memoria.iWriteEnable ),
    .Y(_0483_)
  );
  NAND _1214_ (
    .A(_0446_),
    .B(\VC0Fifo.num_mem [2]),
    .Y(_0484_)
  );
  NAND _1215_ (
    .A(_0484_),
    .B(\VC0Fifo.memoria.iWriteEnable ),
    .Y(_0485_)
  );
  NAND _1216_ (
    .A(_0474_),
    .B(\VC0Fifo.num_mem [3]),
    .Y(_0487_)
  );
  NAND _1217_ (
    .A(_0475_),
    .B(_0438_),
    .Y(_0488_)
  );
  NAND _1218_ (
    .A(_0488_),
    .B(_0487_),
    .Y(_0489_)
  );
  NOR _1219_ (
    .A(_0489_),
    .B(_0485_),
    .Y(_0490_)
  );
  NOR _1220_ (
    .A(_0490_),
    .B(_0483_),
    .Y(_0491_)
  );
  NOR _1221_ (
    .A(_0491_),
    .B(_0057_),
    .Y(_0260_)
  );
  NOT _1222_ (
    .A(_0487_),
    .Y(_0492_)
  );
  NOR _1223_ (
    .A(_0492_),
    .B(_0439_),
    .Y(_0493_)
  );
  NOR _1224_ (
    .A(_0487_),
    .B(\VC0Fifo.num_mem [4]),
    .Y(_0494_)
  );
  NOR _1225_ (
    .A(_0494_),
    .B(_0493_),
    .Y(_0495_)
  );
  NOR _1226_ (
    .A(_0495_),
    .B(_0485_),
    .Y(_0497_)
  );
  NAND _1227_ (
    .A(_0480_),
    .B(\VC0Fifo.num_mem [4]),
    .Y(_0498_)
  );
  NOR _1228_ (
    .A(_0498_),
    .B(\VC0Fifo.memoria.iWriteEnable ),
    .Y(_0499_)
  );
  NOR _1229_ (
    .A(_0499_),
    .B(_0497_),
    .Y(_0500_)
  );
  NOR _1230_ (
    .A(_0500_),
    .B(_0057_),
    .Y(_0261_)
  );
  NOT _1231_ (
    .A(\VC0Fifo.memoria.iReadAddress [0]),
    .Y(_0501_)
  );
  NOR _1232_ (
    .A(_0434_),
    .B(\VC0Fifo.num_mem [2]),
    .Y(_0502_)
  );
  NOR _1233_ (
    .A(_0502_),
    .B(_0460_),
    .Y(_0503_)
  );
  NOR _1234_ (
    .A(_0460_),
    .B(_0430_),
    .Y(_0504_)
  );
  NOR _1235_ (
    .A(_0504_),
    .B(_0503_),
    .Y(_0505_)
  );
  NOR _1236_ (
    .A(_0505_),
    .B(_0501_),
    .Y(_0506_)
  );
  NOR _1237_ (
    .A(_0504_),
    .B(reset_L),
    .Y(_0507_)
  );
  NOT _1238_ (
    .A(_0507_),
    .Y(_0508_)
  );
  NAND _1239_ (
    .A(_0505_),
    .B(_0501_),
    .Y(_0509_)
  );
  NAND _1240_ (
    .A(_0509_),
    .B(_0508_),
    .Y(_0510_)
  );
  NOR _1241_ (
    .A(_0510_),
    .B(_0506_),
    .Y(_0272_)
  );
  NAND _1242_ (
    .A(_0506_),
    .B(\VC0Fifo.memoria.iReadAddress [1]),
    .Y(_0511_)
  );
  NOT _1243_ (
    .A(\VC0Fifo.memoria.iReadAddress [1]),
    .Y(_0512_)
  );
  NOT _1244_ (
    .A(_0504_),
    .Y(_0513_)
  );
  NAND _1245_ (
    .A(_0513_),
    .B(_0448_),
    .Y(_0514_)
  );
  NAND _1246_ (
    .A(_0514_),
    .B(\VC0Fifo.memoria.iReadAddress [0]),
    .Y(_0515_)
  );
  NAND _1247_ (
    .A(_0515_),
    .B(_0512_),
    .Y(_0516_)
  );
  NAND _1248_ (
    .A(_0516_),
    .B(_0511_),
    .Y(_0517_)
  );
  NOR _1249_ (
    .A(_0517_),
    .B(_0507_),
    .Y(_0273_)
  );
  NAND _1250_ (
    .A(_0513_),
    .B(_0485_),
    .Y(_0518_)
  );
  NOR _1251_ (
    .A(_0518_),
    .B(\VC0Fifo.memoria.iWriteAddress [0]),
    .Y(_0519_)
  );
  NAND _1252_ (
    .A(_0518_),
    .B(\VC0Fifo.memoria.iWriteAddress [0]),
    .Y(_0520_)
  );
  NAND _1253_ (
    .A(_0520_),
    .B(_0508_),
    .Y(_0521_)
  );
  NOR _1254_ (
    .A(_0521_),
    .B(_0519_),
    .Y(_0282_)
  );
  NOT _1255_ (
    .A(\VC0Fifo.memoria.iWriteAddress [1]),
    .Y(_0522_)
  );
  NOR _1256_ (
    .A(_0520_),
    .B(_0522_),
    .Y(_0523_)
  );
  NAND _1257_ (
    .A(_0520_),
    .B(_0522_),
    .Y(_0524_)
  );
  NAND _1258_ (
    .A(_0524_),
    .B(_0508_),
    .Y(_0525_)
  );
  NOR _1259_ (
    .A(_0525_),
    .B(_0523_),
    .Y(_0283_)
  );
  NAND _1260_ (
    .A(_0447_),
    .B(reset_L),
    .Y(_0285_)
  );
  NOR _1261_ (
    .A(_0522_),
    .B(_0430_),
    .Y(_0526_)
  );
  NAND _1262_ (
    .A(_0526_),
    .B(\VC0Fifo.memoria.iWriteAddress [0]),
    .Y(_0527_)
  );
  NOT _1263_ (
    .A(_0527_),
    .Y(_0528_)
  );
  NAND _1264_ (
    .A(_0528_),
    .B(\VC0Fifo.Fifo_Data_in [0]),
    .Y(_0529_)
  );
  NAND _1265_ (
    .A(_0527_),
    .B(\VC0Fifo.memoria.Ram[3] [0]),
    .Y(_0530_)
  );
  NAND _1266_ (
    .A(_0530_),
    .B(_0529_),
    .Y(_0307_)
  );
  NOR _1267_ (
    .A(\VC0Fifo.memoria.iWriteAddress [0]),
    .B(_0430_),
    .Y(_0531_)
  );
  NAND _1268_ (
    .A(_0531_),
    .B(\VC0Fifo.memoria.iWriteAddress [1]),
    .Y(_0532_)
  );
  NOT _1269_ (
    .A(_0532_),
    .Y(_0533_)
  );
  NAND _1270_ (
    .A(_0533_),
    .B(\VC0Fifo.Fifo_Data_in [0]),
    .Y(_0534_)
  );
  NAND _1271_ (
    .A(_0532_),
    .B(\VC0Fifo.memoria.Ram[2] [0]),
    .Y(_0535_)
  );
  NAND _1272_ (
    .A(_0535_),
    .B(_0534_),
    .Y(_0311_)
  );
  NOT _1273_ (
    .A(\VC0Fifo.memoria.iWriteAddress [0]),
    .Y(_0536_)
  );
  NOR _1274_ (
    .A(_0536_),
    .B(_0430_),
    .Y(_0537_)
  );
  NAND _1275_ (
    .A(_0537_),
    .B(_0522_),
    .Y(_0538_)
  );
  NOT _1276_ (
    .A(_0538_),
    .Y(_0539_)
  );
  NAND _1277_ (
    .A(_0539_),
    .B(\VC0Fifo.Fifo_Data_in [0]),
    .Y(_0540_)
  );
  NAND _1278_ (
    .A(_0538_),
    .B(\VC0Fifo.memoria.Ram[1] [0]),
    .Y(_0541_)
  );
  NAND _1279_ (
    .A(_0541_),
    .B(_0540_),
    .Y(_0315_)
  );
  NAND _1280_ (
    .A(_0531_),
    .B(_0522_),
    .Y(_0542_)
  );
  NOT _1281_ (
    .A(_0542_),
    .Y(_0543_)
  );
  NAND _1282_ (
    .A(_0543_),
    .B(\VC0Fifo.Fifo_Data_in [0]),
    .Y(_0544_)
  );
  NAND _1283_ (
    .A(_0542_),
    .B(\VC0Fifo.memoria.Ram[0] [0]),
    .Y(_0545_)
  );
  NAND _1284_ (
    .A(_0545_),
    .B(_0544_),
    .Y(_0318_)
  );
  NOT _1285_ (
    .A(\VC1Fifo.memoria.iWriteEnable ),
    .Y(_0546_)
  );
  NOT _1286_ (
    .A(\VC1Fifo.num_mem [2]),
    .Y(_0547_)
  );
  NOR _1287_ (
    .A(\VC1Fifo.num_mem [1]),
    .B(\VC1Fifo.num_mem [0]),
    .Y(_0549_)
  );
  NOR _1288_ (
    .A(\VC1Fifo.num_mem [4]),
    .B(\VC1Fifo.num_mem [3]),
    .Y(_0551_)
  );
  NAND _1289_ (
    .A(_0551_),
    .B(_0549_),
    .Y(_0553_)
  );
  NOR _1290_ (
    .A(_0553_),
    .B(_0547_),
    .Y(_0555_)
  );
  NOR _1291_ (
    .A(_0555_),
    .B(_0546_),
    .Y(_0556_)
  );
  NOT _1292_ (
    .A(\VC1Fifo.num_mem [0]),
    .Y(_0558_)
  );
  NOT _1293_ (
    .A(\VC1Fifo.num_mem [1]),
    .Y(_0559_)
  );
  NAND _1294_ (
    .A(_0559_),
    .B(_0558_),
    .Y(_0560_)
  );
  NOR _1295_ (
    .A(_0560_),
    .B(\VC1Fifo.num_mem [2]),
    .Y(_0561_)
  );
  NAND _1296_ (
    .A(_0561_),
    .B(_0551_),
    .Y(_0562_)
  );
  NAND _1297_ (
    .A(_0562_),
    .B(\VC1Fifo.memoria.iReadEnable ),
    .Y(_0563_)
  );
  NOR _1298_ (
    .A(_0563_),
    .B(\VC1Fifo.memoria.iWriteEnable ),
    .Y(_0564_)
  );
  NOR _1299_ (
    .A(_0564_),
    .B(_0556_),
    .Y(_0565_)
  );
  NOR _1300_ (
    .A(_0565_),
    .B(\VC1Fifo.num_mem [0]),
    .Y(_0566_)
  );
  NOT _1301_ (
    .A(\VC1Fifo.memoria.iReadEnable ),
    .Y(_0567_)
  );
  NAND _1302_ (
    .A(\VC1Fifo.num_mem [0]),
    .B(_0567_),
    .Y(_0568_)
  );
  NOR _1303_ (
    .A(_0568_),
    .B(\VC1Fifo.memoria.iWriteEnable ),
    .Y(_0569_)
  );
  NOR _1304_ (
    .A(_0569_),
    .B(_0566_),
    .Y(_0571_)
  );
  NOR _1305_ (
    .A(_0571_),
    .B(_0057_),
    .Y(_0360_)
  );
  NAND _1306_ (
    .A(\VC1Fifo.num_mem [1]),
    .B(\VC1Fifo.num_mem [0]),
    .Y(_0574_)
  );
  NOT _1307_ (
    .A(_0574_),
    .Y(_0576_)
  );
  NOR _1308_ (
    .A(_0576_),
    .B(_0549_),
    .Y(_0577_)
  );
  NOR _1309_ (
    .A(_0577_),
    .B(_0563_),
    .Y(_0579_)
  );
  NAND _1310_ (
    .A(\VC1Fifo.num_mem [1]),
    .B(_0567_),
    .Y(_0580_)
  );
  NAND _1311_ (
    .A(_0580_),
    .B(_0546_),
    .Y(_0582_)
  );
  NOR _1312_ (
    .A(_0582_),
    .B(_0579_),
    .Y(_0583_)
  );
  NOT _1313_ (
    .A(_0577_),
    .Y(_0585_)
  );
  NAND _1314_ (
    .A(_0585_),
    .B(\VC1Fifo.memoria.iWriteEnable ),
    .Y(_0586_)
  );
  NAND _1315_ (
    .A(_0586_),
    .B(reset_L),
    .Y(_0587_)
  );
  NOR _1316_ (
    .A(_0587_),
    .B(_0583_),
    .Y(_0362_)
  );
  NOR _1317_ (
    .A(_0576_),
    .B(\VC1Fifo.num_mem [2]),
    .Y(_0588_)
  );
  NOR _1318_ (
    .A(_0574_),
    .B(_0547_),
    .Y(_0589_)
  );
  NOT _1319_ (
    .A(_0589_),
    .Y(_0590_)
  );
  NAND _1320_ (
    .A(_0590_),
    .B(\VC1Fifo.memoria.iWriteEnable ),
    .Y(_0591_)
  );
  NOR _1321_ (
    .A(_0591_),
    .B(_0588_),
    .Y(_0592_)
  );
  NOR _1322_ (
    .A(_0560_),
    .B(_0567_),
    .Y(_0593_)
  );
  NOR _1323_ (
    .A(_0593_),
    .B(_0547_),
    .Y(_0594_)
  );
  NAND _1324_ (
    .A(_0549_),
    .B(_0547_),
    .Y(_0595_)
  );
  NOT _1325_ (
    .A(\VC1Fifo.num_mem [3]),
    .Y(_0596_)
  );
  NOT _1326_ (
    .A(\VC1Fifo.num_mem [4]),
    .Y(_0598_)
  );
  NAND _1327_ (
    .A(_0598_),
    .B(_0596_),
    .Y(_0599_)
  );
  NAND _1328_ (
    .A(_0599_),
    .B(\VC1Fifo.memoria.iReadEnable ),
    .Y(_0600_)
  );
  NOR _1329_ (
    .A(_0600_),
    .B(_0595_),
    .Y(_0602_)
  );
  NOR _1330_ (
    .A(_0602_),
    .B(_0594_),
    .Y(_0603_)
  );
  NOR _1331_ (
    .A(_0603_),
    .B(\VC1Fifo.memoria.iWriteEnable ),
    .Y(_0604_)
  );
  NOR _1332_ (
    .A(_0604_),
    .B(_0592_),
    .Y(_0605_)
  );
  NOR _1333_ (
    .A(_0605_),
    .B(_0057_),
    .Y(_0364_)
  );
  NOR _1334_ (
    .A(_0595_),
    .B(_0567_),
    .Y(_0606_)
  );
  NOR _1335_ (
    .A(_0606_),
    .B(_0596_),
    .Y(_0607_)
  );
  NAND _1336_ (
    .A(_0561_),
    .B(_0596_),
    .Y(_0609_)
  );
  NOR _1337_ (
    .A(_0609_),
    .B(_0600_),
    .Y(_0610_)
  );
  NOR _1338_ (
    .A(_0610_),
    .B(_0607_),
    .Y(_0611_)
  );
  NOR _1339_ (
    .A(_0611_),
    .B(\VC1Fifo.memoria.iWriteEnable ),
    .Y(_0612_)
  );
  NOR _1340_ (
    .A(_0599_),
    .B(_0560_),
    .Y(_0613_)
  );
  NAND _1341_ (
    .A(_0613_),
    .B(\VC1Fifo.num_mem [2]),
    .Y(_0614_)
  );
  NAND _1342_ (
    .A(_0614_),
    .B(\VC1Fifo.memoria.iWriteEnable ),
    .Y(_0615_)
  );
  NAND _1343_ (
    .A(_0589_),
    .B(\VC1Fifo.num_mem [3]),
    .Y(_0616_)
  );
  NAND _1344_ (
    .A(_0590_),
    .B(_0596_),
    .Y(_0617_)
  );
  NAND _1345_ (
    .A(_0617_),
    .B(_0616_),
    .Y(_0618_)
  );
  NOR _1346_ (
    .A(_0618_),
    .B(_0615_),
    .Y(_0620_)
  );
  NOR _1347_ (
    .A(_0620_),
    .B(_0612_),
    .Y(_0621_)
  );
  NOR _1348_ (
    .A(_0621_),
    .B(_0057_),
    .Y(_0365_)
  );
  NOT _1349_ (
    .A(_0616_),
    .Y(_0622_)
  );
  NOR _1350_ (
    .A(_0622_),
    .B(_0598_),
    .Y(_0623_)
  );
  NOR _1351_ (
    .A(_0616_),
    .B(\VC1Fifo.num_mem [4]),
    .Y(_0624_)
  );
  NOR _1352_ (
    .A(_0624_),
    .B(_0623_),
    .Y(_0625_)
  );
  NOR _1353_ (
    .A(_0625_),
    .B(_0615_),
    .Y(_0626_)
  );
  NOR _1354_ (
    .A(_0609_),
    .B(_0567_),
    .Y(_0627_)
  );
  NAND _1355_ (
    .A(_0546_),
    .B(\VC1Fifo.num_mem [4]),
    .Y(_0628_)
  );
  NOR _1356_ (
    .A(_0628_),
    .B(_0627_),
    .Y(_0629_)
  );
  NOR _1357_ (
    .A(_0629_),
    .B(_0626_),
    .Y(_0630_)
  );
  NOR _1358_ (
    .A(_0630_),
    .B(_0057_),
    .Y(_0367_)
  );
  NAND _1359_ (
    .A(\VC1Fifo.memoria.iWriteEnable ),
    .B(\VC1Fifo.memoria.iReadEnable ),
    .Y(_0631_)
  );
  NAND _1360_ (
    .A(_0631_),
    .B(_0563_),
    .Y(_0632_)
  );
  NOR _1361_ (
    .A(_0632_),
    .B(\VC1Fifo.memoria.iReadAddress [0]),
    .Y(_0633_)
  );
  NAND _1362_ (
    .A(_0631_),
    .B(_0057_),
    .Y(_0634_)
  );
  NAND _1363_ (
    .A(_0632_),
    .B(\VC1Fifo.memoria.iReadAddress [0]),
    .Y(_0635_)
  );
  NAND _1364_ (
    .A(_0635_),
    .B(_0634_),
    .Y(_0636_)
  );
  NOR _1365_ (
    .A(_0636_),
    .B(_0633_),
    .Y(_0380_)
  );
  NOT _1366_ (
    .A(\VC1Fifo.memoria.iReadAddress [1]),
    .Y(_0637_)
  );
  NOR _1367_ (
    .A(_0635_),
    .B(_0637_),
    .Y(_0638_)
  );
  NAND _1368_ (
    .A(_0635_),
    .B(_0637_),
    .Y(_0639_)
  );
  NAND _1369_ (
    .A(_0639_),
    .B(_0634_),
    .Y(_0640_)
  );
  NOR _1370_ (
    .A(_0640_),
    .B(_0638_),
    .Y(_0382_)
  );
  NAND _1371_ (
    .A(_0631_),
    .B(_0615_),
    .Y(_0641_)
  );
  NOR _1372_ (
    .A(_0641_),
    .B(\VC1Fifo.memoria.iWriteAddress [0]),
    .Y(_0642_)
  );
  NAND _1373_ (
    .A(_0641_),
    .B(\VC1Fifo.memoria.iWriteAddress [0]),
    .Y(_0643_)
  );
  NAND _1374_ (
    .A(_0643_),
    .B(_0634_),
    .Y(_0644_)
  );
  NOR _1375_ (
    .A(_0644_),
    .B(_0642_),
    .Y(_0392_)
  );
  NOT _1376_ (
    .A(\VC1Fifo.memoria.iWriteAddress [1]),
    .Y(_0645_)
  );
  NOR _1377_ (
    .A(_0643_),
    .B(_0645_),
    .Y(_0646_)
  );
  NAND _1378_ (
    .A(_0643_),
    .B(_0645_),
    .Y(_0647_)
  );
  NAND _1379_ (
    .A(_0647_),
    .B(_0634_),
    .Y(_0648_)
  );
  NOR _1380_ (
    .A(_0648_),
    .B(_0646_),
    .Y(_0393_)
  );
  NAND _1381_ (
    .A(_0562_),
    .B(reset_L),
    .Y(_0395_)
  );
  NOR _1382_ (
    .A(_0645_),
    .B(_0546_),
    .Y(_0649_)
  );
  NAND _1383_ (
    .A(_0649_),
    .B(\VC1Fifo.memoria.iWriteAddress [0]),
    .Y(_0650_)
  );
  NOT _1384_ (
    .A(_0650_),
    .Y(_0651_)
  );
  NAND _1385_ (
    .A(_0651_),
    .B(\VC1Fifo.Fifo_Data_in [0]),
    .Y(_0652_)
  );
  NAND _1386_ (
    .A(_0650_),
    .B(\VC1Fifo.memoria.Ram[3] [0]),
    .Y(_0653_)
  );
  NAND _1387_ (
    .A(_0653_),
    .B(_0652_),
    .Y(_0416_)
  );
  NOR _1388_ (
    .A(\VC1Fifo.memoria.iWriteAddress [0]),
    .B(_0546_),
    .Y(_0654_)
  );
  NAND _1389_ (
    .A(_0654_),
    .B(\VC1Fifo.memoria.iWriteAddress [1]),
    .Y(_0655_)
  );
  NOT _1390_ (
    .A(_0655_),
    .Y(_0656_)
  );
  NAND _1391_ (
    .A(_0656_),
    .B(\VC1Fifo.Fifo_Data_in [0]),
    .Y(_0657_)
  );
  NAND _1392_ (
    .A(_0655_),
    .B(\VC1Fifo.memoria.Ram[2] [0]),
    .Y(_0658_)
  );
  NAND _1393_ (
    .A(_0658_),
    .B(_0657_),
    .Y(_0419_)
  );
  NOT _1394_ (
    .A(\VC1Fifo.memoria.iWriteAddress [0]),
    .Y(_0659_)
  );
  NOR _1395_ (
    .A(_0659_),
    .B(_0546_),
    .Y(_0660_)
  );
  NAND _1396_ (
    .A(_0660_),
    .B(_0645_),
    .Y(_0661_)
  );
  NOT _1397_ (
    .A(_0661_),
    .Y(_0662_)
  );
  NAND _1398_ (
    .A(_0662_),
    .B(\VC1Fifo.Fifo_Data_in [0]),
    .Y(_0663_)
  );
  NAND _1399_ (
    .A(_0661_),
    .B(\VC1Fifo.memoria.Ram[1] [0]),
    .Y(_0664_)
  );
  NAND _1400_ (
    .A(_0664_),
    .B(_0663_),
    .Y(_0422_)
  );
  NAND _1401_ (
    .A(_0654_),
    .B(_0645_),
    .Y(_0665_)
  );
  NOT _1402_ (
    .A(_0665_),
    .Y(_0666_)
  );
  NAND _1403_ (
    .A(_0666_),
    .B(\VC1Fifo.Fifo_Data_in [0]),
    .Y(_0667_)
  );
  NAND _1404_ (
    .A(_0665_),
    .B(\VC1Fifo.memoria.Ram[0] [0]),
    .Y(_0668_)
  );
  NAND _1405_ (
    .A(_0668_),
    .B(_0667_),
    .Y(_0426_)
  );
  NOR _1406_ (
    .A(\MainFifo.memoria.Ram[2] [5]),
    .B(_0384_),
    .Y(_0670_)
  );
  NOR _1407_ (
    .A(\MainFifo.memoria.Ram[0] [5]),
    .B(\MainFifo.memoria.iReadAddress [1]),
    .Y(_0671_)
  );
  NOR _1408_ (
    .A(_0671_),
    .B(_0670_),
    .Y(_0672_)
  );
  NOR _1409_ (
    .A(_0672_),
    .B(\MainFifo.memoria.iReadAddress [0]),
    .Y(_0673_)
  );
  NOR _1410_ (
    .A(_0341_),
    .B(_0057_),
    .Y(_0674_)
  );
  NOT _1411_ (
    .A(\MainFifo.memoria.Ram[3] [5]),
    .Y(_0675_)
  );
  NAND _1412_ (
    .A(_0675_),
    .B(\MainFifo.memoria.iReadAddress [1]),
    .Y(_0676_)
  );
  NOT _1413_ (
    .A(\MainFifo.memoria.Ram[1] [5]),
    .Y(_0677_)
  );
  NAND _1414_ (
    .A(_0677_),
    .B(_0384_),
    .Y(_0678_)
  );
  NAND _1415_ (
    .A(_0678_),
    .B(_0676_),
    .Y(_0679_)
  );
  NAND _1416_ (
    .A(_0679_),
    .B(\MainFifo.memoria.iReadAddress [0]),
    .Y(_0680_)
  );
  NAND _1417_ (
    .A(_0680_),
    .B(_0674_),
    .Y(_0681_)
  );
  NOR _1418_ (
    .A(_0681_),
    .B(_0673_),
    .Y(_0682_)
  );
  NOR _1419_ (
    .A(Fifo_Empty_VC1),
    .B(Fifo_Empty_VC0),
    .Y(_0683_)
  );
  NOT _1420_ (
    .A(_0683_),
    .Y(_0684_)
  );
  NAND _1421_ (
    .A(_0684_),
    .B(reset_L),
    .Y(_0685_)
  );
  NOR _1422_ (
    .A(_0685_),
    .B(_0682_),
    .Y(_0436_)
  );
  NOT _1423_ (
    .A(\MainFifo.memoria.iReadAddress [0]),
    .Y(_0686_)
  );
  NOR _1424_ (
    .A(_0677_),
    .B(_0686_),
    .Y(_0687_)
  );
  NOT _1425_ (
    .A(\MainFifo.memoria.Ram[0] [5]),
    .Y(_0688_)
  );
  NOR _1426_ (
    .A(_0688_),
    .B(\MainFifo.memoria.iReadAddress [0]),
    .Y(_0689_)
  );
  NOR _1427_ (
    .A(_0689_),
    .B(_0687_),
    .Y(_0690_)
  );
  NAND _1428_ (
    .A(_0690_),
    .B(_0384_),
    .Y(_0691_)
  );
  NOT _1429_ (
    .A(_0674_),
    .Y(_0692_)
  );
  NOR _1430_ (
    .A(_0675_),
    .B(_0686_),
    .Y(_0693_)
  );
  NAND _1431_ (
    .A(\MainFifo.memoria.Ram[2] [5]),
    .B(_0686_),
    .Y(_0694_)
  );
  NAND _1432_ (
    .A(_0694_),
    .B(\MainFifo.memoria.iReadAddress [1]),
    .Y(_0695_)
  );
  NOR _1433_ (
    .A(_0695_),
    .B(_0693_),
    .Y(_0696_)
  );
  NOR _1434_ (
    .A(_0696_),
    .B(_0692_),
    .Y(_0697_)
  );
  NAND _1435_ (
    .A(_0697_),
    .B(_0691_),
    .Y(_0698_)
  );
  NOR _1436_ (
    .A(_0683_),
    .B(_0698_),
    .Y(_0440_)
  );
  NAND _1437_ (
    .A(_0683_),
    .B(_0546_),
    .Y(_0699_)
  );
  NAND _1438_ (
    .A(_0699_),
    .B(\VC1Fifo.Fifo_Data_in [0]),
    .Y(_0700_)
  );
  NOR _1439_ (
    .A(_0700_),
    .B(_0440_),
    .Y(_0701_)
  );
  NAND _1440_ (
    .A(_0684_),
    .B(_0682_),
    .Y(_0702_)
  );
  NAND _1441_ (
    .A(\MainFifo.memoria.Ram[3] [0]),
    .B(\MainFifo.memoria.iReadAddress [0]),
    .Y(_0703_)
  );
  NOT _1442_ (
    .A(\MainFifo.memoria.Ram[2] [0]),
    .Y(_0704_)
  );
  NOR _1443_ (
    .A(_0704_),
    .B(\MainFifo.memoria.iReadAddress [0]),
    .Y(_0705_)
  );
  NOR _1444_ (
    .A(_0705_),
    .B(_0384_),
    .Y(_0706_)
  );
  NAND _1445_ (
    .A(_0706_),
    .B(_0703_),
    .Y(_0707_)
  );
  NOT _1446_ (
    .A(\MainFifo.memoria.Ram[1] [0]),
    .Y(_0708_)
  );
  NOR _1447_ (
    .A(_0708_),
    .B(_0686_),
    .Y(_0709_)
  );
  NOT _1448_ (
    .A(\MainFifo.memoria.Ram[0] [0]),
    .Y(_0710_)
  );
  NOR _1449_ (
    .A(_0710_),
    .B(\MainFifo.memoria.iReadAddress [0]),
    .Y(_0711_)
  );
  NOR _1450_ (
    .A(_0711_),
    .B(_0709_),
    .Y(_0712_)
  );
  NAND _1451_ (
    .A(_0712_),
    .B(_0384_),
    .Y(_0713_)
  );
  NAND _1452_ (
    .A(_0713_),
    .B(_0707_),
    .Y(_0714_)
  );
  NOR _1453_ (
    .A(_0714_),
    .B(_0702_),
    .Y(_0715_)
  );
  NOR _1454_ (
    .A(_0715_),
    .B(_0701_),
    .Y(_0716_)
  );
  NOR _1455_ (
    .A(_0716_),
    .B(_0057_),
    .Y(_0445_)
  );
  NAND _1456_ (
    .A(_0683_),
    .B(\VC0Fifo.memoria.iWriteEnable ),
    .Y(_0717_)
  );
  NAND _1457_ (
    .A(_0717_),
    .B(_0702_),
    .Y(_0718_)
  );
  NOT _1458_ (
    .A(\VC0Fifo.Fifo_Data_in [0]),
    .Y(_0719_)
  );
  NOR _1459_ (
    .A(_0719_),
    .B(_0057_),
    .Y(_0720_)
  );
  NAND _1460_ (
    .A(_0720_),
    .B(_0718_),
    .Y(_0721_)
  );
  NOR _1461_ (
    .A(_0714_),
    .B(_0341_),
    .Y(_0722_)
  );
  NAND _1462_ (
    .A(_0722_),
    .B(_0436_),
    .Y(_0723_)
  );
  NAND _1463_ (
    .A(_0723_),
    .B(_0721_),
    .Y(_0450_)
  );
  NOT _1464_ (
    .A(init),
    .Y(_0724_)
  );
  NAND _1465_ (
    .A(_0724_),
    .B(\fsm_Control1.nxt_state [0]),
    .Y(_0725_)
  );
  NAND _1466_ (
    .A(_0725_),
    .B(reset_L),
    .Y(_0548_)
  );
  NOR _1467_ (
    .A(\fsm_Control1.nxt_state [1]),
    .B(init),
    .Y(_0726_)
  );
  NOR _1468_ (
    .A(_0726_),
    .B(_0057_),
    .Y(_0550_)
  );
  NOT _1469_ (
    .A(\fsm_Control1.nxt_state [2]),
    .Y(_0727_)
  );
  NAND _1470_ (
    .A(_0724_),
    .B(reset_L),
    .Y(_0728_)
  );
  NOR _1471_ (
    .A(_0728_),
    .B(_0727_),
    .Y(_0552_)
  );
  NOT _1472_ (
    .A(\fsm_Control1.nxt_state [3]),
    .Y(_0729_)
  );
  NOR _1473_ (
    .A(_0728_),
    .B(_0729_),
    .Y(_0554_)
  );
  NOT _1474_ (
    .A(\fsm_Control1.nxt_state [4]),
    .Y(_0730_)
  );
  NOR _1475_ (
    .A(_0728_),
    .B(_0730_),
    .Y(_0557_)
  );
  NOT _1476_ (
    .A(\fsm_Control1.state [0]),
    .Y(_0731_)
  );
  NOT _1477_ (
    .A(\fsm_Control1.state [1]),
    .Y(_0732_)
  );
  NAND _1478_ (
    .A(_0732_),
    .B(_0731_),
    .Y(_0733_)
  );
  NOR _1479_ (
    .A(_0733_),
    .B(\fsm_Control1.state [4]),
    .Y(_0734_)
  );
  NOT _1480_ (
    .A(\fsm_Control1.state [2]),
    .Y(_0735_)
  );
  NOR _1481_ (
    .A(\fsm_Control1.state [3]),
    .B(_0735_),
    .Y(_0736_)
  );
  NAND _1482_ (
    .A(_0736_),
    .B(_0734_),
    .Y(_0737_)
  );
  NOT _1483_ (
    .A(\fsm_Control1.state [4]),
    .Y(_0738_)
  );
  NOR _1484_ (
    .A(\fsm_Control1.state [3]),
    .B(\fsm_Control1.state [2]),
    .Y(_0739_)
  );
  NAND _1485_ (
    .A(_0739_),
    .B(_0738_),
    .Y(_0740_)
  );
  NOR _1486_ (
    .A(_0732_),
    .B(\fsm_Control1.state [0]),
    .Y(_0741_)
  );
  NOT _1487_ (
    .A(_0741_),
    .Y(_0742_)
  );
  NOR _1488_ (
    .A(_0742_),
    .B(_0740_),
    .Y(_0743_)
  );
  NOR _1489_ (
    .A(\fsm_Control1.state [1]),
    .B(_0731_),
    .Y(_0744_)
  );
  NOT _1490_ (
    .A(_0744_),
    .Y(_0745_)
  );
  NOR _1491_ (
    .A(_0745_),
    .B(_0740_),
    .Y(_0573_)
  );
  NOR _1492_ (
    .A(_0573_),
    .B(_0743_),
    .Y(_0746_)
  );
  NOT _1493_ (
    .A(\fsm_Control1.state [3]),
    .Y(_0747_)
  );
  NOR _1494_ (
    .A(_0747_),
    .B(\fsm_Control1.state [2]),
    .Y(_0748_)
  );
  NAND _1495_ (
    .A(_0748_),
    .B(_0734_),
    .Y(_0749_)
  );
  NAND _1496_ (
    .A(_0749_),
    .B(_0737_),
    .Y(_0750_)
  );
  NAND _1497_ (
    .A(_0739_),
    .B(\fsm_Control1.state [4]),
    .Y(_0751_)
  );
  NOR _1498_ (
    .A(_0751_),
    .B(_0733_),
    .Y(_0752_)
  );
  NOR _1499_ (
    .A(_0752_),
    .B(_0750_),
    .Y(_0753_)
  );
  NAND _1500_ (
    .A(_0753_),
    .B(_0746_),
    .Y(_0754_)
  );
  NOR _1501_ (
    .A(_0754_),
    .B(_0057_),
    .Y(_0755_)
  );
  NAND _1502_ (
    .A(_0755_),
    .B(idle_out),
    .Y(_0756_)
  );
  NAND _1503_ (
    .A(_0756_),
    .B(_0737_),
    .Y(_0570_)
  );
  NAND _1504_ (
    .A(_0752_),
    .B(_0057_),
    .Y(_0757_)
  );
  NAND _1505_ (
    .A(_0757_),
    .B(_0754_),
    .Y(_0572_)
  );
  NOT _1506_ (
    .A(_0743_),
    .Y(_0758_)
  );
  NOR _1507_ (
    .A(_0747_),
    .B(_0735_),
    .Y(_0759_)
  );
  NOR _1508_ (
    .A(_0759_),
    .B(_0739_),
    .Y(_0760_)
  );
  NAND _1509_ (
    .A(_0760_),
    .B(_0734_),
    .Y(_0761_)
  );
  NAND _1510_ (
    .A(_0761_),
    .B(_0758_),
    .Y(_0575_)
  );
  NOT _1511_ (
    .A(_0752_),
    .Y(_0762_)
  );
  NOR _1512_ (
    .A(_0762_),
    .B(_0057_),
    .Y(_0578_)
  );
  NOT _1513_ (
    .A(active_out),
    .Y(_0763_)
  );
  NOT _1514_ (
    .A(_0573_),
    .Y(_0764_)
  );
  NAND _1515_ (
    .A(_0762_),
    .B(_0764_),
    .Y(_0765_)
  );
  NOR _1516_ (
    .A(_0765_),
    .B(_0575_),
    .Y(_0766_)
  );
  NAND _1517_ (
    .A(_0766_),
    .B(reset_L),
    .Y(_0767_)
  );
  NOR _1518_ (
    .A(_0767_),
    .B(_0763_),
    .Y(_0581_)
  );
  NOT _1519_ (
    .A(error_out),
    .Y(_0768_)
  );
  NAND _1520_ (
    .A(_0746_),
    .B(reset_L),
    .Y(_0769_)
  );
  NOR _1521_ (
    .A(_0769_),
    .B(_0768_),
    .Y(_0584_)
  );
  NOR _1522_ (
    .A(\VC0Fifo.memoria.iReadEnable ),
    .B(\VC1Fifo.memoria.iReadEnable ),
    .Y(_0770_)
  );
  NOR _1523_ (
    .A(_0770_),
    .B(_0057_),
    .Y(_0597_)
  );
  NOT _1524_ (
    .A(\VC1Fifo.memoria.iReadAddress [0]),
    .Y(_0771_)
  );
  NOR _1525_ (
    .A(\VC1Fifo.memoria.Ram[3] [0]),
    .B(_0771_),
    .Y(_0003_)
  );
  NOR _1526_ (
    .A(\VC1Fifo.memoria.Ram[2] [0]),
    .B(\VC1Fifo.memoria.iReadAddress [0]),
    .Y(_0004_)
  );
  NOR _1527_ (
    .A(_0004_),
    .B(_0003_),
    .Y(_0005_)
  );
  NOR _1528_ (
    .A(_0005_),
    .B(_0637_),
    .Y(_0006_)
  );
  NOR _1529_ (
    .A(\VC1Fifo.memoria.Ram[1] [0]),
    .B(_0771_),
    .Y(_0007_)
  );
  NOR _1530_ (
    .A(\VC1Fifo.memoria.Ram[0] [0]),
    .B(\VC1Fifo.memoria.iReadAddress [0]),
    .Y(_0008_)
  );
  NOR _1531_ (
    .A(_0008_),
    .B(_0007_),
    .Y(_0009_)
  );
  NOR _1532_ (
    .A(_0009_),
    .B(\VC1Fifo.memoria.iReadAddress [1]),
    .Y(_0010_)
  );
  NOR _1533_ (
    .A(_0010_),
    .B(\VC0Fifo.memoria.iReadEnable ),
    .Y(_0011_)
  );
  NAND _1534_ (
    .A(_0011_),
    .B(\VC1Fifo.memoria.iReadEnable ),
    .Y(_0012_)
  );
  NOR _1535_ (
    .A(_0012_),
    .B(_0006_),
    .Y(_0013_)
  );
  NOR _1536_ (
    .A(\VC0Fifo.memoria.Ram[0] [0]),
    .B(\VC0Fifo.memoria.iReadAddress [0]),
    .Y(_0014_)
  );
  NOT _1537_ (
    .A(\VC0Fifo.memoria.Ram[1] [0]),
    .Y(_0015_)
  );
  NAND _1538_ (
    .A(_0015_),
    .B(\VC0Fifo.memoria.iReadAddress [0]),
    .Y(_0016_)
  );
  NAND _1539_ (
    .A(_0016_),
    .B(_0512_),
    .Y(_0017_)
  );
  NOR _1540_ (
    .A(_0017_),
    .B(_0014_),
    .Y(_0018_)
  );
  NOR _1541_ (
    .A(\VC0Fifo.memoria.Ram[2] [0]),
    .B(\VC0Fifo.memoria.iReadAddress [0]),
    .Y(_0019_)
  );
  NOT _1542_ (
    .A(\VC0Fifo.memoria.Ram[3] [0]),
    .Y(_0020_)
  );
  NAND _1543_ (
    .A(_0020_),
    .B(\VC0Fifo.memoria.iReadAddress [0]),
    .Y(_0021_)
  );
  NAND _1544_ (
    .A(_0021_),
    .B(\VC0Fifo.memoria.iReadAddress [1]),
    .Y(_0022_)
  );
  NOR _1545_ (
    .A(_0022_),
    .B(_0019_),
    .Y(_0023_)
  );
  NOR _1546_ (
    .A(_0023_),
    .B(_0018_),
    .Y(_0024_)
  );
  NOR _1547_ (
    .A(_0024_),
    .B(_0460_),
    .Y(_0025_)
  );
  NOR _1548_ (
    .A(_0025_),
    .B(_0013_),
    .Y(_0026_)
  );
  NOR _1549_ (
    .A(_0026_),
    .B(_0057_),
    .Y(_0601_)
  );
  DFF _1550_ (
    .C(clk),
    .D(_0000_),
    .Q(pausaD0D1)
  );
  DFF _1551_ (
    .C(clk),
    .D(_0001_),
    .Q(\VC0Fifo.memoria.iReadEnable )
  );
  DFF _1552_ (
    .C(clk),
    .D(_0002_),
    .Q(\VC1Fifo.memoria.iReadEnable )
  );
  DFF _1553_ (
    .C(clk),
    .D(_0608_),
    .Q(\D0Fifo.memoria.iWriteAddress [0])
  );
  DFF _1554_ (
    .C(clk),
    .D(_0619_),
    .Q(\D0Fifo.memoria.iWriteAddress [1])
  );
  DFF _1555_ (
    .C(clk),
    .D(_0486_),
    .Q(\D0Fifo.memoria.iReadAddress [0])
  );
  DFF _1556_ (
    .C(clk),
    .D(_0496_),
    .Q(\D0Fifo.memoria.iReadAddress [1])
  );
  DFF _1557_ (
    .C(clk),
    .D(_0334_),
    .Q(\D0Fifo.num_mem [0])
  );
  DFF _1558_ (
    .C(clk),
    .D(_0344_),
    .Q(\D0Fifo.num_mem [1])
  );
  DFF _1559_ (
    .C(clk),
    .D(_0354_),
    .Q(\D0Fifo.num_mem [2])
  );
  DFF _1560_ (
    .C(clk),
    .D(_0669_),
    .Q(\D0Fifo.Pausa )
  );
  DFF _1561_ (
    .C(clk),
    .D(_0045_),
    .Q(\D0Fifo.memoria.Ram[0] [0])
  );
  DFF _1562_ (
    .C(clk),
    .D(_0046_),
    .Q(\D0Fifo.memoria.Ram[0] [1])
  );
  DFF _1563_ (
    .C(clk),
    .D(_0047_),
    .Q(\D0Fifo.memoria.Ram[0] [2])
  );
  DFF _1564_ (
    .C(clk),
    .D(_0048_),
    .Q(\D0Fifo.memoria.Ram[0] [3])
  );
  DFF _1565_ (
    .C(clk),
    .D(_0049_),
    .Q(\D0Fifo.memoria.Ram[0] [4])
  );
  DFF _1566_ (
    .C(clk),
    .D(_0050_),
    .Q(\D0Fifo.memoria.Ram[0] [5])
  );
  DFF _1567_ (
    .C(clk),
    .D(_0039_),
    .Q(\D0Fifo.memoria.Ram[1] [0])
  );
  DFF _1568_ (
    .C(clk),
    .D(_0040_),
    .Q(\D0Fifo.memoria.Ram[1] [1])
  );
  DFF _1569_ (
    .C(clk),
    .D(_0041_),
    .Q(\D0Fifo.memoria.Ram[1] [2])
  );
  DFF _1570_ (
    .C(clk),
    .D(_0042_),
    .Q(\D0Fifo.memoria.Ram[1] [3])
  );
  DFF _1571_ (
    .C(clk),
    .D(_0043_),
    .Q(\D0Fifo.memoria.Ram[1] [4])
  );
  DFF _1572_ (
    .C(clk),
    .D(_0044_),
    .Q(\D0Fifo.memoria.Ram[1] [5])
  );
  DFF _1573_ (
    .C(clk),
    .D(_0033_),
    .Q(\D0Fifo.memoria.Ram[2] [0])
  );
  DFF _1574_ (
    .C(clk),
    .D(_0034_),
    .Q(\D0Fifo.memoria.Ram[2] [1])
  );
  DFF _1575_ (
    .C(clk),
    .D(_0035_),
    .Q(\D0Fifo.memoria.Ram[2] [2])
  );
  DFF _1576_ (
    .C(clk),
    .D(_0036_),
    .Q(\D0Fifo.memoria.Ram[2] [3])
  );
  DFF _1577_ (
    .C(clk),
    .D(_0037_),
    .Q(\D0Fifo.memoria.Ram[2] [4])
  );
  DFF _1578_ (
    .C(clk),
    .D(_0038_),
    .Q(\D0Fifo.memoria.Ram[2] [5])
  );
  DFF _1579_ (
    .C(clk),
    .D(_0027_),
    .Q(\D0Fifo.memoria.Ram[3] [0])
  );
  DFF _1580_ (
    .C(clk),
    .D(_0028_),
    .Q(\D0Fifo.memoria.Ram[3] [1])
  );
  DFF _1581_ (
    .C(clk),
    .D(_0029_),
    .Q(\D0Fifo.memoria.Ram[3] [2])
  );
  DFF _1582_ (
    .C(clk),
    .D(_0030_),
    .Q(\D0Fifo.memoria.Ram[3] [3])
  );
  DFF _1583_ (
    .C(clk),
    .D(_0031_),
    .Q(\D0Fifo.memoria.Ram[3] [4])
  );
  DFF _1584_ (
    .C(clk),
    .D(_0032_),
    .Q(\D0Fifo.memoria.Ram[3] [5])
  );
  DFF _1585_ (
    .C(clk),
    .D(_0054_),
    .Q(\D1Fifo.memoria.iReadAddress [0])
  );
  DFF _1586_ (
    .C(clk),
    .D(_0055_),
    .Q(\D1Fifo.memoria.iReadAddress [1])
  );
  DFF _1587_ (
    .C(clk),
    .D(_0051_),
    .Q(\D1Fifo.num_mem [0])
  );
  DFF _1588_ (
    .C(clk),
    .D(_0052_),
    .Q(\D1Fifo.num_mem [1])
  );
  DFF _1589_ (
    .C(clk),
    .D(_0053_),
    .Q(\D1Fifo.num_mem [2])
  );
  DFF _1590_ (
    .C(clk),
    .D(_0056_),
    .Q(\D1Fifo.Pausa )
  );
  DFF _1591_ (
    .C(clk),
    .D(_0107_),
    .Q(\D0Fifo.Fifo_Data_in [0])
  );
  DFF _1592_ (
    .C(clk),
    .D(_0109_),
    .Q(\D0Fifo.Fifo_Data_in [1])
  );
  DFF _1593_ (
    .C(clk),
    .D(_0111_),
    .Q(\D0Fifo.Fifo_Data_in [2])
  );
  DFF _1594_ (
    .C(clk),
    .D(_0112_),
    .Q(\D0Fifo.Fifo_Data_in [3])
  );
  DFF _1595_ (
    .C(clk),
    .D(_0114_),
    .Q(\D0Fifo.Fifo_Data_in [4])
  );
  DFF _1596_ (
    .C(clk),
    .D(_0116_),
    .Q(\D0Fifo.Fifo_Data_in [5])
  );
  DFF _1597_ (
    .C(clk),
    .D(_0094_),
    .Q(\D0Fifo.memoria.iWriteEnable )
  );
  DFF _1598_ (
    .C(clk),
    .D(_0170_),
    .Q(\MainFifo.memoria.iWriteAddress [0])
  );
  DFF _1599_ (
    .C(clk),
    .D(_0172_),
    .Q(\MainFifo.memoria.iWriteAddress [1])
  );
  DFF _1600_ (
    .C(clk),
    .D(_0157_),
    .Q(\MainFifo.memoria.iReadAddress [0])
  );
  DFF _1601_ (
    .C(clk),
    .D(_0158_),
    .Q(\MainFifo.memoria.iReadAddress [1])
  );
  DFF _1602_ (
    .C(clk),
    .D(_0140_),
    .Q(\MainFifo.num_mem [0])
  );
  DFF _1603_ (
    .C(clk),
    .D(_0142_),
    .Q(\MainFifo.num_mem [1])
  );
  DFF _1604_ (
    .C(clk),
    .D(_0144_),
    .Q(\MainFifo.num_mem [2])
  );
  DFF _1605_ (
    .C(clk),
    .D(_0208_),
    .Q(\MainFifo.memoria.Ram[0] [0])
  );
  DFF _1606_ (
    .C(clk),
    .D(_0211_),
    .Q(\MainFifo.memoria.Ram[0] [5])
  );
  DFF _1607_ (
    .C(clk),
    .D(_0201_),
    .Q(\MainFifo.memoria.Ram[1] [0])
  );
  DFF _1608_ (
    .C(clk),
    .D(_0204_),
    .Q(\MainFifo.memoria.Ram[1] [5])
  );
  DFF _1609_ (
    .C(clk),
    .D(_0195_),
    .Q(\MainFifo.memoria.Ram[2] [0])
  );
  DFF _1610_ (
    .C(clk),
    .D(_0198_),
    .Q(\MainFifo.memoria.Ram[2] [5])
  );
  DFF _1611_ (
    .C(clk),
    .D(_0188_),
    .Q(\MainFifo.memoria.Ram[3] [0])
  );
  DFF _1612_ (
    .C(clk),
    .D(_0191_),
    .Q(\MainFifo.memoria.Ram[3] [5])
  );
  DFF _1613_ (
    .C(clk),
    .D(_0282_),
    .Q(\VC0Fifo.memoria.iWriteAddress [0])
  );
  DFF _1614_ (
    .C(clk),
    .D(_0283_),
    .Q(\VC0Fifo.memoria.iWriteAddress [1])
  );
  DFF _1615_ (
    .C(clk),
    .D(_0272_),
    .Q(\VC0Fifo.memoria.iReadAddress [0])
  );
  DFF _1616_ (
    .C(clk),
    .D(_0273_),
    .Q(\VC0Fifo.memoria.iReadAddress [1])
  );
  DFF _1617_ (
    .C(clk),
    .D(_0255_),
    .Q(\VC0Fifo.num_mem [0])
  );
  DFF _1618_ (
    .C(clk),
    .D(_0256_),
    .Q(\VC0Fifo.num_mem [1])
  );
  DFF _1619_ (
    .C(clk),
    .D(_0258_),
    .Q(\VC0Fifo.num_mem [2])
  );
  DFF _1620_ (
    .C(clk),
    .D(_0260_),
    .Q(\VC0Fifo.num_mem [3])
  );
  DFF _1621_ (
    .C(clk),
    .D(_0261_),
    .Q(\VC0Fifo.num_mem [4])
  );
  DFF _1622_ (
    .C(clk),
    .D(_0285_),
    .Q(Fifo_Empty_VC0)
  );
  DFF _1623_ (
    .C(clk),
    .D(_0318_),
    .Q(\VC0Fifo.memoria.Ram[0] [0])
  );
  DFF _1624_ (
    .C(clk),
    .D(_0315_),
    .Q(\VC0Fifo.memoria.Ram[1] [0])
  );
  DFF _1625_ (
    .C(clk),
    .D(_0311_),
    .Q(\VC0Fifo.memoria.Ram[2] [0])
  );
  DFF _1626_ (
    .C(clk),
    .D(_0307_),
    .Q(\VC0Fifo.memoria.Ram[3] [0])
  );
  DFF _1627_ (
    .C(clk),
    .D(_0392_),
    .Q(\VC1Fifo.memoria.iWriteAddress [0])
  );
  DFF _1628_ (
    .C(clk),
    .D(_0393_),
    .Q(\VC1Fifo.memoria.iWriteAddress [1])
  );
  DFF _1629_ (
    .C(clk),
    .D(_0380_),
    .Q(\VC1Fifo.memoria.iReadAddress [0])
  );
  DFF _1630_ (
    .C(clk),
    .D(_0382_),
    .Q(\VC1Fifo.memoria.iReadAddress [1])
  );
  DFF _1631_ (
    .C(clk),
    .D(_0360_),
    .Q(\VC1Fifo.num_mem [0])
  );
  DFF _1632_ (
    .C(clk),
    .D(_0362_),
    .Q(\VC1Fifo.num_mem [1])
  );
  DFF _1633_ (
    .C(clk),
    .D(_0364_),
    .Q(\VC1Fifo.num_mem [2])
  );
  DFF _1634_ (
    .C(clk),
    .D(_0365_),
    .Q(\VC1Fifo.num_mem [3])
  );
  DFF _1635_ (
    .C(clk),
    .D(_0367_),
    .Q(\VC1Fifo.num_mem [4])
  );
  DFF _1636_ (
    .C(clk),
    .D(_0395_),
    .Q(Fifo_Empty_VC1)
  );
  DFF _1637_ (
    .C(clk),
    .D(_0426_),
    .Q(\VC1Fifo.memoria.Ram[0] [0])
  );
  DFF _1638_ (
    .C(clk),
    .D(_0422_),
    .Q(\VC1Fifo.memoria.Ram[1] [0])
  );
  DFF _1639_ (
    .C(clk),
    .D(_0419_),
    .Q(\VC1Fifo.memoria.Ram[2] [0])
  );
  DFF _1640_ (
    .C(clk),
    .D(_0416_),
    .Q(\VC1Fifo.memoria.Ram[3] [0])
  );
  DFF _1641_ (
    .C(clk),
    .D(_0450_),
    .Q(\VC0Fifo.Fifo_Data_in [0])
  );
  DFF _1642_ (
    .C(clk),
    .D(_0445_),
    .Q(\VC1Fifo.Fifo_Data_in [0])
  );
  DFF _1643_ (
    .C(clk),
    .D(_0436_),
    .Q(\VC0Fifo.memoria.iWriteEnable )
  );
  DFF _1644_ (
    .C(clk),
    .D(_0440_),
    .Q(\VC1Fifo.memoria.iWriteEnable )
  );
  DFF _1645_ (
    .C(clk),
    .D(_0581_),
    .Q(active_out)
  );
  DFF _1646_ (
    .C(clk),
    .D(_0570_),
    .Q(idle_out)
  );
  DFF _1647_ (
    .C(clk),
    .D(_0584_),
    .Q(error_out)
  );
  DFF _1648_ (
    .C(clk),
    .D(_0548_),
    .Q(\fsm_Control1.state [0])
  );
  DFF _1649_ (
    .C(clk),
    .D(_0550_),
    .Q(\fsm_Control1.state [1])
  );
  DFF _1650_ (
    .C(clk),
    .D(_0552_),
    .Q(\fsm_Control1.state [2])
  );
  DFF _1651_ (
    .C(clk),
    .D(_0554_),
    .Q(\fsm_Control1.state [3])
  );
  DFF _1652_ (
    .C(clk),
    .D(_0557_),
    .Q(\fsm_Control1.state [4])
  );
  DFF _1653_ (
    .C(clk),
    .D(_0572_),
    .Q(\fsm_Control1.nxt_state [0])
  );
  DFF _1654_ (
    .C(clk),
    .D(_0573_),
    .Q(\fsm_Control1.nxt_state [1])
  );
  DFF _1655_ (
    .C(clk),
    .D(_0575_),
    .Q(\fsm_Control1.nxt_state [2])
  );
  DFF _1656_ (
    .C(clk),
    .D(1'b0),
    .Q(\fsm_Control1.nxt_state [3])
  );
  DFF _1657_ (
    .C(clk),
    .D(_0578_),
    .Q(\fsm_Control1.nxt_state [4])
  );
  DFF _1658_ (
    .C(clk),
    .D(_0601_),
    .Q(\Demux_D0_D1.data_in [0])
  );
  DFF _1659_ (
    .C(clk),
    .D(_0597_),
    .Q(\Demux_D0_D1.valid_in )
  );
  assign data_out1 = 6'b000000;
endmodule
