/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-zWLHjG/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module fsmControlEstructural(clk, reset, init, umbral_MF, umbral_VC0, umbral_VC1, umbral_D0, umbral_D1, FIFO_error, FIFO_empty, umbrales_I, active_out, idle_out, error_out);
  wire _000_;
  wire [4:0] _001_;
  wire _002_;
  wire [4:0] _003_;
  wire [1:0] _004_;
  wire [1:0] _005_;
  wire [1:0] _006_;
  wire [3:0] _007_;
  wire [3:0] _008_;
  wire [4:0] _009_;
  wire [13:0] _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  input [4:0] FIFO_empty;
  input [4:0] FIFO_error;
  output active_out;
  input clk;
  output [4:0] error_out;
  output idle_out;
  input init;
  wire [4:0] nxt_state;
  wire [1:0] nxt_umbral_D0;
  wire [1:0] nxt_umbral_D1;
  wire [1:0] nxt_umbral_MF;
  wire [3:0] nxt_umbral_VC0;
  wire [3:0] nxt_umbral_VC1;
  input reset;
  wire [4:0] state;
  input [1:0] umbral_D0;
  input [1:0] umbral_D1;
  input [1:0] umbral_MF;
  input [3:0] umbral_VC0;
  input [3:0] umbral_VC1;
  output [13:0] umbrales_I;
  NAND _203_ (
    .A(_150_),
    .B(_147_),
    .Y(_010_[0])
  );
  NAND _204_ (
    .A(_146_),
    .B(nxt_umbral_D1[1]),
    .Y(_151_)
  );
  NOT _205_ (
    .A(umbrales_I[1]),
    .Y(_152_)
  );
  NOR _206_ (
    .A(_152_),
    .B(_013_),
    .Y(_153_)
  );
  NAND _207_ (
    .A(_153_),
    .B(_116_),
    .Y(_154_)
  );
  NAND _208_ (
    .A(_154_),
    .B(_151_),
    .Y(_010_[1])
  );
  NAND _209_ (
    .A(_146_),
    .B(nxt_umbral_D0[0]),
    .Y(_155_)
  );
  NOT _210_ (
    .A(umbrales_I[2]),
    .Y(_156_)
  );
  NOR _211_ (
    .A(_156_),
    .B(_013_),
    .Y(_157_)
  );
  NAND _212_ (
    .A(_157_),
    .B(_116_),
    .Y(_158_)
  );
  NAND _213_ (
    .A(_158_),
    .B(_155_),
    .Y(_010_[2])
  );
  NAND _214_ (
    .A(_146_),
    .B(nxt_umbral_D0[1]),
    .Y(_159_)
  );
  NOT _215_ (
    .A(umbrales_I[3]),
    .Y(_160_)
  );
  NOR _216_ (
    .A(_160_),
    .B(_013_),
    .Y(_161_)
  );
  NAND _217_ (
    .A(_161_),
    .B(_116_),
    .Y(_162_)
  );
  NAND _218_ (
    .A(_162_),
    .B(_159_),
    .Y(_010_[3])
  );
  NAND _219_ (
    .A(_146_),
    .B(nxt_umbral_VC1[0]),
    .Y(_163_)
  );
  NOT _220_ (
    .A(umbrales_I[4]),
    .Y(_164_)
  );
  NOR _221_ (
    .A(_164_),
    .B(_013_),
    .Y(_165_)
  );
  NAND _222_ (
    .A(_165_),
    .B(_116_),
    .Y(_166_)
  );
  NAND _223_ (
    .A(_166_),
    .B(_163_),
    .Y(_010_[4])
  );
  NAND _224_ (
    .A(_146_),
    .B(nxt_umbral_VC1[1]),
    .Y(_167_)
  );
  NOT _225_ (
    .A(umbrales_I[5]),
    .Y(_168_)
  );
  NOR _226_ (
    .A(_168_),
    .B(_013_),
    .Y(_169_)
  );
  NAND _227_ (
    .A(_169_),
    .B(_116_),
    .Y(_170_)
  );
  NAND _228_ (
    .A(_170_),
    .B(_167_),
    .Y(_010_[5])
  );
  NAND _229_ (
    .A(_146_),
    .B(nxt_umbral_VC1[2]),
    .Y(_171_)
  );
  NOT _230_ (
    .A(umbrales_I[6]),
    .Y(_172_)
  );
  NOR _231_ (
    .A(_172_),
    .B(_013_),
    .Y(_173_)
  );
  NAND _232_ (
    .A(_173_),
    .B(_116_),
    .Y(_174_)
  );
  NAND _233_ (
    .A(_174_),
    .B(_171_),
    .Y(_010_[6])
  );
  NAND _234_ (
    .A(_146_),
    .B(nxt_umbral_VC1[3]),
    .Y(_175_)
  );
  NOT _235_ (
    .A(umbrales_I[7]),
    .Y(_176_)
  );
  NOR _236_ (
    .A(_176_),
    .B(_013_),
    .Y(_177_)
  );
  NAND _237_ (
    .A(_177_),
    .B(_116_),
    .Y(_178_)
  );
  NAND _238_ (
    .A(_178_),
    .B(_175_),
    .Y(_010_[7])
  );
  NAND _239_ (
    .A(_146_),
    .B(nxt_umbral_VC0[0]),
    .Y(_179_)
  );
  NOT _240_ (
    .A(umbrales_I[8]),
    .Y(_180_)
  );
  NOR _241_ (
    .A(_180_),
    .B(_013_),
    .Y(_181_)
  );
  NAND _242_ (
    .A(_181_),
    .B(_116_),
    .Y(_182_)
  );
  NAND _243_ (
    .A(_182_),
    .B(_179_),
    .Y(_010_[8])
  );
  NAND _244_ (
    .A(_146_),
    .B(nxt_umbral_VC0[1]),
    .Y(_183_)
  );
  NOT _245_ (
    .A(umbrales_I[9]),
    .Y(_184_)
  );
  NOR _246_ (
    .A(_184_),
    .B(_013_),
    .Y(_185_)
  );
  NAND _247_ (
    .A(_185_),
    .B(_116_),
    .Y(_186_)
  );
  NAND _248_ (
    .A(_186_),
    .B(_183_),
    .Y(_010_[9])
  );
  NAND _249_ (
    .A(_146_),
    .B(nxt_umbral_VC0[2]),
    .Y(_187_)
  );
  NOT _250_ (
    .A(umbrales_I[10]),
    .Y(_188_)
  );
  NOR _251_ (
    .A(_188_),
    .B(_013_),
    .Y(_189_)
  );
  NAND _252_ (
    .A(_189_),
    .B(_116_),
    .Y(_190_)
  );
  NAND _253_ (
    .A(_190_),
    .B(_187_),
    .Y(_010_[10])
  );
  NAND _254_ (
    .A(_146_),
    .B(nxt_umbral_VC0[3]),
    .Y(_191_)
  );
  NOT _255_ (
    .A(umbrales_I[11]),
    .Y(_192_)
  );
  NOR _256_ (
    .A(_192_),
    .B(_013_),
    .Y(_193_)
  );
  NAND _257_ (
    .A(_193_),
    .B(_116_),
    .Y(_194_)
  );
  NAND _258_ (
    .A(_194_),
    .B(_191_),
    .Y(_010_[11])
  );
  NAND _259_ (
    .A(_146_),
    .B(nxt_umbral_MF[0]),
    .Y(_195_)
  );
  NOT _260_ (
    .A(umbrales_I[12]),
    .Y(_196_)
  );
  NOR _261_ (
    .A(_196_),
    .B(_013_),
    .Y(_197_)
  );
  NAND _262_ (
    .A(_197_),
    .B(_116_),
    .Y(_198_)
  );
  NAND _263_ (
    .A(_198_),
    .B(_195_),
    .Y(_010_[12])
  );
  NAND _264_ (
    .A(_146_),
    .B(nxt_umbral_MF[1]),
    .Y(_199_)
  );
  NOT _265_ (
    .A(umbrales_I[13]),
    .Y(_200_)
  );
  NOR _266_ (
    .A(_200_),
    .B(_013_),
    .Y(_201_)
  );
  NAND _267_ (
    .A(_201_),
    .B(_116_),
    .Y(_202_)
  );
  NAND _268_ (
    .A(_202_),
    .B(_199_),
    .Y(_010_[13])
  );
  NOT _269_ (
    .A(init),
    .Y(_011_)
  );
  NAND _270_ (
    .A(nxt_state[0]),
    .B(_011_),
    .Y(_012_)
  );
  NAND _271_ (
    .A(_012_),
    .B(reset),
    .Y(_009_[0])
  );
  NOT _272_ (
    .A(reset),
    .Y(_013_)
  );
  NOR _273_ (
    .A(nxt_state[1]),
    .B(init),
    .Y(_014_)
  );
  NOR _274_ (
    .A(_014_),
    .B(_013_),
    .Y(_009_[1])
  );
  NOT _275_ (
    .A(nxt_state[2]),
    .Y(_015_)
  );
  NAND _276_ (
    .A(reset),
    .B(_011_),
    .Y(_016_)
  );
  NOR _277_ (
    .A(_016_),
    .B(_015_),
    .Y(_009_[2])
  );
  NOT _278_ (
    .A(nxt_state[3]),
    .Y(_017_)
  );
  NOR _279_ (
    .A(_016_),
    .B(_017_),
    .Y(_009_[3])
  );
  NOT _280_ (
    .A(nxt_state[4]),
    .Y(_018_)
  );
  NOR _281_ (
    .A(_016_),
    .B(_018_),
    .Y(_009_[4])
  );
  NOT _282_ (
    .A(FIFO_error[0]),
    .Y(_019_)
  );
  NOT _283_ (
    .A(FIFO_error[1]),
    .Y(_020_)
  );
  NAND _284_ (
    .A(_020_),
    .B(_019_),
    .Y(_021_)
  );
  NOT _285_ (
    .A(FIFO_error[4]),
    .Y(_022_)
  );
  NOR _286_ (
    .A(FIFO_error[3]),
    .B(FIFO_error[2]),
    .Y(_023_)
  );
  NAND _287_ (
    .A(_023_),
    .B(_022_),
    .Y(_024_)
  );
  NOR _288_ (
    .A(_024_),
    .B(_021_),
    .Y(_025_)
  );
  NOT _289_ (
    .A(_025_),
    .Y(_026_)
  );
  NOT _290_ (
    .A(state[4]),
    .Y(_027_)
  );
  NAND _291_ (
    .A(state[3]),
    .B(_027_),
    .Y(_028_)
  );
  NOT _292_ (
    .A(state[2]),
    .Y(_029_)
  );
  NOR _293_ (
    .A(state[1]),
    .B(state[0]),
    .Y(_030_)
  );
  NAND _294_ (
    .A(_030_),
    .B(_029_),
    .Y(_031_)
  );
  NOR _295_ (
    .A(_031_),
    .B(_028_),
    .Y(_032_)
  );
  NOR _296_ (
    .A(FIFO_empty[4]),
    .B(FIFO_empty[2]),
    .Y(_033_)
  );
  NOT _297_ (
    .A(FIFO_empty[0]),
    .Y(_034_)
  );
  NOT _298_ (
    .A(FIFO_empty[1]),
    .Y(_035_)
  );
  NAND _299_ (
    .A(_035_),
    .B(_034_),
    .Y(_036_)
  );
  NOR _300_ (
    .A(_036_),
    .B(FIFO_empty[3]),
    .Y(_037_)
  );
  NAND _301_ (
    .A(_037_),
    .B(_033_),
    .Y(_038_)
  );
  NAND _302_ (
    .A(_038_),
    .B(_032_),
    .Y(_039_)
  );
  NOR _303_ (
    .A(_039_),
    .B(_026_),
    .Y(_040_)
  );
  NAND _304_ (
    .A(_040_),
    .B(nxt_state[0]),
    .Y(_041_)
  );
  NAND _305_ (
    .A(reset),
    .B(init),
    .Y(_042_)
  );
  NOT _306_ (
    .A(_042_),
    .Y(_043_)
  );
  NOT _307_ (
    .A(state[0]),
    .Y(_044_)
  );
  NOT _308_ (
    .A(state[1]),
    .Y(_045_)
  );
  NAND _309_ (
    .A(_045_),
    .B(_044_),
    .Y(_046_)
  );
  NOR _310_ (
    .A(state[3]),
    .B(state[2]),
    .Y(_047_)
  );
  NAND _311_ (
    .A(_047_),
    .B(state[4]),
    .Y(_048_)
  );
  NOR _312_ (
    .A(_048_),
    .B(_046_),
    .Y(_049_)
  );
  NAND _313_ (
    .A(_049_),
    .B(_025_),
    .Y(_050_)
  );
  NOR _314_ (
    .A(_050_),
    .B(_043_),
    .Y(_051_)
  );
  NOT _315_ (
    .A(state[3]),
    .Y(_052_)
  );
  NAND _316_ (
    .A(_052_),
    .B(_029_),
    .Y(_053_)
  );
  NOR _317_ (
    .A(_053_),
    .B(state[4]),
    .Y(_054_)
  );
  NOR _318_ (
    .A(_045_),
    .B(state[0]),
    .Y(_055_)
  );
  NAND _319_ (
    .A(_055_),
    .B(_054_),
    .Y(_056_)
  );
  NOR _320_ (
    .A(_049_),
    .B(_032_),
    .Y(_057_)
  );
  NAND _321_ (
    .A(_057_),
    .B(_056_),
    .Y(_058_)
  );
  NOR _322_ (
    .A(state[1]),
    .B(_044_),
    .Y(_059_)
  );
  NAND _323_ (
    .A(_059_),
    .B(_054_),
    .Y(_060_)
  );
  NAND _324_ (
    .A(_052_),
    .B(state[2]),
    .Y(_061_)
  );
  NOR _325_ (
    .A(_061_),
    .B(state[4]),
    .Y(_062_)
  );
  NAND _326_ (
    .A(_062_),
    .B(_030_),
    .Y(_063_)
  );
  NAND _327_ (
    .A(_063_),
    .B(_060_),
    .Y(_064_)
  );
  NOR _328_ (
    .A(_064_),
    .B(_058_),
    .Y(_065_)
  );
  NOR _329_ (
    .A(_065_),
    .B(_051_),
    .Y(_066_)
  );
  NAND _330_ (
    .A(_066_),
    .B(_041_),
    .Y(_003_[0])
  );
  NAND _331_ (
    .A(_040_),
    .B(nxt_state[1]),
    .Y(_067_)
  );
  NAND _332_ (
    .A(_047_),
    .B(_027_),
    .Y(_068_)
  );
  NAND _333_ (
    .A(_045_),
    .B(state[0]),
    .Y(_069_)
  );
  NOR _334_ (
    .A(_069_),
    .B(_068_),
    .Y(_070_)
  );
  NOR _335_ (
    .A(_050_),
    .B(_042_),
    .Y(_071_)
  );
  NOR _336_ (
    .A(_071_),
    .B(_070_),
    .Y(_072_)
  );
  NAND _337_ (
    .A(_072_),
    .B(_067_),
    .Y(_003_[1])
  );
  NOT _338_ (
    .A(_038_),
    .Y(_073_)
  );
  NOT _339_ (
    .A(_063_),
    .Y(_074_)
  );
  NAND _340_ (
    .A(_074_),
    .B(_073_),
    .Y(_075_)
  );
  NAND _341_ (
    .A(_038_),
    .B(_015_),
    .Y(_076_)
  );
  NAND _342_ (
    .A(_076_),
    .B(_032_),
    .Y(_077_)
  );
  NAND _343_ (
    .A(_077_),
    .B(_056_),
    .Y(_078_)
  );
  NOR _344_ (
    .A(_065_),
    .B(_026_),
    .Y(_079_)
  );
  NAND _345_ (
    .A(_079_),
    .B(_078_),
    .Y(_080_)
  );
  NAND _346_ (
    .A(_080_),
    .B(_075_),
    .Y(_003_[2])
  );
  NAND _347_ (
    .A(_074_),
    .B(_038_),
    .Y(_081_)
  );
  NAND _348_ (
    .A(_040_),
    .B(nxt_state[3]),
    .Y(_082_)
  );
  NAND _349_ (
    .A(_082_),
    .B(_081_),
    .Y(_003_[3])
  );
  NAND _350_ (
    .A(_058_),
    .B(_026_),
    .Y(_083_)
  );
  NAND _351_ (
    .A(_040_),
    .B(nxt_state[4]),
    .Y(_084_)
  );
  NAND _352_ (
    .A(_084_),
    .B(_083_),
    .Y(_003_[4])
  );
  NOR _353_ (
    .A(_070_),
    .B(_049_),
    .Y(_085_)
  );
  NAND _354_ (
    .A(_085_),
    .B(nxt_umbral_VC1[0]),
    .Y(_086_)
  );
  NAND _355_ (
    .A(_049_),
    .B(umbral_VC1[0]),
    .Y(_087_)
  );
  NAND _356_ (
    .A(_087_),
    .B(_086_),
    .Y(_008_[0])
  );
  NAND _357_ (
    .A(_085_),
    .B(nxt_umbral_VC1[1]),
    .Y(_088_)
  );
  NAND _358_ (
    .A(_049_),
    .B(umbral_VC1[1]),
    .Y(_089_)
  );
  NAND _359_ (
    .A(_089_),
    .B(_088_),
    .Y(_008_[1])
  );
  NAND _360_ (
    .A(_085_),
    .B(nxt_umbral_VC1[2]),
    .Y(_090_)
  );
  NAND _361_ (
    .A(_049_),
    .B(umbral_VC1[2]),
    .Y(_091_)
  );
  NAND _362_ (
    .A(_091_),
    .B(_090_),
    .Y(_008_[2])
  );
  NAND _363_ (
    .A(_085_),
    .B(nxt_umbral_VC1[3]),
    .Y(_092_)
  );
  NAND _364_ (
    .A(_049_),
    .B(umbral_VC1[3]),
    .Y(_093_)
  );
  NAND _365_ (
    .A(_093_),
    .B(_092_),
    .Y(_008_[3])
  );
  NAND _366_ (
    .A(_085_),
    .B(nxt_umbral_VC0[0]),
    .Y(_094_)
  );
  NAND _367_ (
    .A(_049_),
    .B(umbral_VC0[0]),
    .Y(_095_)
  );
  NAND _368_ (
    .A(_095_),
    .B(_094_),
    .Y(_007_[0])
  );
  NAND _369_ (
    .A(_085_),
    .B(nxt_umbral_VC0[1]),
    .Y(_096_)
  );
  NAND _370_ (
    .A(_049_),
    .B(umbral_VC0[1]),
    .Y(_097_)
  );
  NAND _371_ (
    .A(_097_),
    .B(_096_),
    .Y(_007_[1])
  );
  NAND _372_ (
    .A(_085_),
    .B(nxt_umbral_VC0[2]),
    .Y(_098_)
  );
  NAND _373_ (
    .A(_049_),
    .B(umbral_VC0[2]),
    .Y(_099_)
  );
  NAND _374_ (
    .A(_099_),
    .B(_098_),
    .Y(_007_[2])
  );
  NAND _375_ (
    .A(_085_),
    .B(nxt_umbral_VC0[3]),
    .Y(_100_)
  );
  NAND _376_ (
    .A(_049_),
    .B(umbral_VC0[3]),
    .Y(_101_)
  );
  NAND _377_ (
    .A(_101_),
    .B(_100_),
    .Y(_007_[3])
  );
  NAND _378_ (
    .A(_085_),
    .B(nxt_umbral_D1[0]),
    .Y(_102_)
  );
  NAND _379_ (
    .A(_049_),
    .B(umbral_D1[0]),
    .Y(_103_)
  );
  NAND _380_ (
    .A(_103_),
    .B(_102_),
    .Y(_005_[0])
  );
  NAND _381_ (
    .A(_085_),
    .B(nxt_umbral_D1[1]),
    .Y(_104_)
  );
  NAND _382_ (
    .A(_049_),
    .B(umbral_D1[1]),
    .Y(_105_)
  );
  NAND _383_ (
    .A(_105_),
    .B(_104_),
    .Y(_005_[1])
  );
  NAND _384_ (
    .A(_085_),
    .B(nxt_umbral_D0[0]),
    .Y(_106_)
  );
  NAND _385_ (
    .A(_049_),
    .B(umbral_D0[0]),
    .Y(_107_)
  );
  NAND _386_ (
    .A(_107_),
    .B(_106_),
    .Y(_004_[0])
  );
  NAND _387_ (
    .A(_085_),
    .B(nxt_umbral_D0[1]),
    .Y(_108_)
  );
  NAND _388_ (
    .A(_049_),
    .B(umbral_D0[1]),
    .Y(_109_)
  );
  NAND _389_ (
    .A(_109_),
    .B(_108_),
    .Y(_004_[1])
  );
  NAND _390_ (
    .A(_085_),
    .B(nxt_umbral_MF[0]),
    .Y(_110_)
  );
  NAND _391_ (
    .A(_049_),
    .B(umbral_MF[0]),
    .Y(_111_)
  );
  NAND _392_ (
    .A(_111_),
    .B(_110_),
    .Y(_006_[0])
  );
  NAND _393_ (
    .A(_085_),
    .B(nxt_umbral_MF[1]),
    .Y(_112_)
  );
  NAND _394_ (
    .A(_049_),
    .B(umbral_MF[1]),
    .Y(_113_)
  );
  NAND _395_ (
    .A(_113_),
    .B(_112_),
    .Y(_006_[1])
  );
  NAND _396_ (
    .A(_049_),
    .B(FIFO_error[0]),
    .Y(_114_)
  );
  NAND _397_ (
    .A(_085_),
    .B(_056_),
    .Y(_115_)
  );
  NAND _398_ (
    .A(_115_),
    .B(_050_),
    .Y(_116_)
  );
  NOT _399_ (
    .A(error_out[0]),
    .Y(_117_)
  );
  NOR _400_ (
    .A(_117_),
    .B(_013_),
    .Y(_118_)
  );
  NAND _401_ (
    .A(_118_),
    .B(_116_),
    .Y(_119_)
  );
  NAND _402_ (
    .A(_119_),
    .B(_114_),
    .Y(_001_[0])
  );
  NAND _403_ (
    .A(_049_),
    .B(FIFO_error[1]),
    .Y(_120_)
  );
  NOT _404_ (
    .A(error_out[1]),
    .Y(_121_)
  );
  NOR _405_ (
    .A(_121_),
    .B(_013_),
    .Y(_122_)
  );
  NAND _406_ (
    .A(_122_),
    .B(_116_),
    .Y(_123_)
  );
  NAND _407_ (
    .A(_123_),
    .B(_120_),
    .Y(_001_[1])
  );
  NAND _408_ (
    .A(_049_),
    .B(FIFO_error[2]),
    .Y(_124_)
  );
  NOT _409_ (
    .A(error_out[2]),
    .Y(_125_)
  );
  NOR _410_ (
    .A(_125_),
    .B(_013_),
    .Y(_126_)
  );
  NAND _411_ (
    .A(_126_),
    .B(_116_),
    .Y(_127_)
  );
  NAND _412_ (
    .A(_127_),
    .B(_124_),
    .Y(_001_[2])
  );
  NAND _413_ (
    .A(_049_),
    .B(FIFO_error[3]),
    .Y(_128_)
  );
  NOT _414_ (
    .A(error_out[3]),
    .Y(_129_)
  );
  NOR _415_ (
    .A(_129_),
    .B(_013_),
    .Y(_130_)
  );
  NAND _416_ (
    .A(_130_),
    .B(_116_),
    .Y(_131_)
  );
  NAND _417_ (
    .A(_131_),
    .B(_128_),
    .Y(_001_[3])
  );
  NAND _418_ (
    .A(_049_),
    .B(FIFO_error[4]),
    .Y(_132_)
  );
  NOT _419_ (
    .A(error_out[4]),
    .Y(_133_)
  );
  NOR _420_ (
    .A(_133_),
    .B(_013_),
    .Y(_134_)
  );
  NAND _421_ (
    .A(_134_),
    .B(_116_),
    .Y(_135_)
  );
  NAND _422_ (
    .A(_135_),
    .B(_132_),
    .Y(_001_[4])
  );
  NOT _423_ (
    .A(idle_out),
    .Y(_136_)
  );
  NOR _424_ (
    .A(_136_),
    .B(_013_),
    .Y(_137_)
  );
  NAND _425_ (
    .A(_137_),
    .B(_065_),
    .Y(_138_)
  );
  NAND _426_ (
    .A(_138_),
    .B(_075_),
    .Y(_002_)
  );
  NOR _427_ (
    .A(_073_),
    .B(_026_),
    .Y(_139_)
  );
  NAND _428_ (
    .A(_139_),
    .B(_032_),
    .Y(_140_)
  );
  NOR _429_ (
    .A(_032_),
    .B(_013_),
    .Y(_141_)
  );
  NAND _430_ (
    .A(_141_),
    .B(active_out),
    .Y(_142_)
  );
  NOR _431_ (
    .A(_142_),
    .B(_115_),
    .Y(_143_)
  );
  NAND _432_ (
    .A(_143_),
    .B(_063_),
    .Y(_144_)
  );
  NAND _433_ (
    .A(_144_),
    .B(_140_),
    .Y(_000_)
  );
  NAND _434_ (
    .A(_049_),
    .B(_026_),
    .Y(_145_)
  );
  NAND _435_ (
    .A(_145_),
    .B(_056_),
    .Y(_146_)
  );
  NAND _436_ (
    .A(_146_),
    .B(nxt_umbral_D1[0]),
    .Y(_147_)
  );
  NOT _437_ (
    .A(umbrales_I[0]),
    .Y(_148_)
  );
  NOR _438_ (
    .A(_148_),
    .B(_013_),
    .Y(_149_)
  );
  NAND _439_ (
    .A(_149_),
    .B(_116_),
    .Y(_150_)
  );
  DFF _440_ (
    .C(clk),
    .D(_010_[0]),
    .Q(umbrales_I[0])
  );
  DFF _441_ (
    .C(clk),
    .D(_010_[1]),
    .Q(umbrales_I[1])
  );
  DFF _442_ (
    .C(clk),
    .D(_010_[2]),
    .Q(umbrales_I[2])
  );
  DFF _443_ (
    .C(clk),
    .D(_010_[3]),
    .Q(umbrales_I[3])
  );
  DFF _444_ (
    .C(clk),
    .D(_010_[4]),
    .Q(umbrales_I[4])
  );
  DFF _445_ (
    .C(clk),
    .D(_010_[5]),
    .Q(umbrales_I[5])
  );
  DFF _446_ (
    .C(clk),
    .D(_010_[6]),
    .Q(umbrales_I[6])
  );
  DFF _447_ (
    .C(clk),
    .D(_010_[7]),
    .Q(umbrales_I[7])
  );
  DFF _448_ (
    .C(clk),
    .D(_010_[8]),
    .Q(umbrales_I[8])
  );
  DFF _449_ (
    .C(clk),
    .D(_010_[9]),
    .Q(umbrales_I[9])
  );
  DFF _450_ (
    .C(clk),
    .D(_010_[10]),
    .Q(umbrales_I[10])
  );
  DFF _451_ (
    .C(clk),
    .D(_010_[11]),
    .Q(umbrales_I[11])
  );
  DFF _452_ (
    .C(clk),
    .D(_010_[12]),
    .Q(umbrales_I[12])
  );
  DFF _453_ (
    .C(clk),
    .D(_010_[13]),
    .Q(umbrales_I[13])
  );
  DFF _454_ (
    .C(clk),
    .D(_000_),
    .Q(active_out)
  );
  DFF _455_ (
    .C(clk),
    .D(_002_),
    .Q(idle_out)
  );
  DFF _456_ (
    .C(clk),
    .D(_001_[0]),
    .Q(error_out[0])
  );
  DFF _457_ (
    .C(clk),
    .D(_001_[1]),
    .Q(error_out[1])
  );
  DFF _458_ (
    .C(clk),
    .D(_001_[2]),
    .Q(error_out[2])
  );
  DFF _459_ (
    .C(clk),
    .D(_001_[3]),
    .Q(error_out[3])
  );
  DFF _460_ (
    .C(clk),
    .D(_001_[4]),
    .Q(error_out[4])
  );
  DFF _461_ (
    .C(clk),
    .D(_006_[0]),
    .Q(nxt_umbral_MF[0])
  );
  DFF _462_ (
    .C(clk),
    .D(_006_[1]),
    .Q(nxt_umbral_MF[1])
  );
  DFF _463_ (
    .C(clk),
    .D(_004_[0]),
    .Q(nxt_umbral_D0[0])
  );
  DFF _464_ (
    .C(clk),
    .D(_004_[1]),
    .Q(nxt_umbral_D0[1])
  );
  DFF _465_ (
    .C(clk),
    .D(_005_[0]),
    .Q(nxt_umbral_D1[0])
  );
  DFF _466_ (
    .C(clk),
    .D(_005_[1]),
    .Q(nxt_umbral_D1[1])
  );
  DFF _467_ (
    .C(clk),
    .D(_007_[0]),
    .Q(nxt_umbral_VC0[0])
  );
  DFF _468_ (
    .C(clk),
    .D(_007_[1]),
    .Q(nxt_umbral_VC0[1])
  );
  DFF _469_ (
    .C(clk),
    .D(_007_[2]),
    .Q(nxt_umbral_VC0[2])
  );
  DFF _470_ (
    .C(clk),
    .D(_007_[3]),
    .Q(nxt_umbral_VC0[3])
  );
  DFF _471_ (
    .C(clk),
    .D(_008_[0]),
    .Q(nxt_umbral_VC1[0])
  );
  DFF _472_ (
    .C(clk),
    .D(_008_[1]),
    .Q(nxt_umbral_VC1[1])
  );
  DFF _473_ (
    .C(clk),
    .D(_008_[2]),
    .Q(nxt_umbral_VC1[2])
  );
  DFF _474_ (
    .C(clk),
    .D(_008_[3]),
    .Q(nxt_umbral_VC1[3])
  );
  DFF _475_ (
    .C(clk),
    .D(_009_[0]),
    .Q(state[0])
  );
  DFF _476_ (
    .C(clk),
    .D(_009_[1]),
    .Q(state[1])
  );
  DFF _477_ (
    .C(clk),
    .D(_009_[2]),
    .Q(state[2])
  );
  DFF _478_ (
    .C(clk),
    .D(_009_[3]),
    .Q(state[3])
  );
  DFF _479_ (
    .C(clk),
    .D(_009_[4]),
    .Q(state[4])
  );
  DFF _480_ (
    .C(clk),
    .D(_003_[0]),
    .Q(nxt_state[0])
  );
  DFF _481_ (
    .C(clk),
    .D(_003_[1]),
    .Q(nxt_state[1])
  );
  DFF _482_ (
    .C(clk),
    .D(_003_[2]),
    .Q(nxt_state[2])
  );
  DFF _483_ (
    .C(clk),
    .D(_003_[3]),
    .Q(nxt_state[3])
  );
  DFF _484_ (
    .C(clk),
    .D(_003_[4]),
    .Q(nxt_state[4])
  );
endmodule
