/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-zWLHjG/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module fsmControlEstructural(clk, reset, init, umbral_MF, umbral_VC0, umbral_VC1, umbral_D0, umbral_D1, FIFO_error, FIFO_empty, umbrales_I, active_out, idle_out, error_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire [4:0] _003_;
  wire [4:0] _004_;
  wire [13:0] _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  input [4:0] FIFO_empty;
  input [4:0] FIFO_error;
  output active_out;
  input clk;
  output error_out;
  output idle_out;
  input init;
  wire [4:0] nxt_state;
  input reset;
  wire [4:0] state;
  input [1:0] umbral_D0;
  input [1:0] umbral_D1;
  input [1:0] umbral_MF;
  input [3:0] umbral_VC0;
  input [3:0] umbral_VC1;
  output [13:0] umbrales_I;
  NOT _109_ (
    .A(reset),
    .Y(_084_)
  );
  NOT _110_ (
    .A(init),
    .Y(_085_)
  );
  NOR _111_ (
    .A(_085_),
    .B(_084_),
    .Y(_086_)
  );
  NOR _112_ (
    .A(_084_),
    .B(nxt_state[0]),
    .Y(_087_)
  );
  NOR _113_ (
    .A(_087_),
    .B(_086_),
    .Y(_004_[0])
  );
  NOR _114_ (
    .A(init),
    .B(nxt_state[1]),
    .Y(_088_)
  );
  NOR _115_ (
    .A(_088_),
    .B(_084_),
    .Y(_004_[1])
  );
  NOT _116_ (
    .A(nxt_state[2]),
    .Y(_089_)
  );
  NAND _117_ (
    .A(_085_),
    .B(reset),
    .Y(_090_)
  );
  NOR _118_ (
    .A(_090_),
    .B(_089_),
    .Y(_004_[2])
  );
  NOT _119_ (
    .A(nxt_state[3]),
    .Y(_091_)
  );
  NOR _120_ (
    .A(_090_),
    .B(_091_),
    .Y(_004_[3])
  );
  NOT _121_ (
    .A(nxt_state[4]),
    .Y(_092_)
  );
  NOR _122_ (
    .A(_090_),
    .B(_092_),
    .Y(_004_[4])
  );
  NOT _123_ (
    .A(state[1]),
    .Y(_093_)
  );
  NOT _124_ (
    .A(state[0]),
    .Y(_094_)
  );
  NAND _125_ (
    .A(_094_),
    .B(_093_),
    .Y(_095_)
  );
  NOR _126_ (
    .A(state[2]),
    .B(state[3]),
    .Y(_096_)
  );
  NAND _127_ (
    .A(_096_),
    .B(state[4]),
    .Y(_097_)
  );
  NOR _128_ (
    .A(_097_),
    .B(_095_),
    .Y(_098_)
  );
  NOT _129_ (
    .A(_098_),
    .Y(_099_)
  );
  NAND _130_ (
    .A(error_out),
    .B(reset),
    .Y(_100_)
  );
  NAND _131_ (
    .A(_100_),
    .B(_099_),
    .Y(_001_)
  );
  NOT _132_ (
    .A(state[4]),
    .Y(_101_)
  );
  NAND _133_ (
    .A(_096_),
    .B(_101_),
    .Y(_102_)
  );
  NAND _134_ (
    .A(_094_),
    .B(state[1]),
    .Y(_103_)
  );
  NOR _135_ (
    .A(_103_),
    .B(_102_),
    .Y(_104_)
  );
  NOT _136_ (
    .A(_104_),
    .Y(_105_)
  );
  NAND _137_ (
    .A(_105_),
    .B(_099_),
    .Y(_106_)
  );
  NAND _138_ (
    .A(_086_),
    .B(umbrales_I[0]),
    .Y(_107_)
  );
  NOR _139_ (
    .A(_107_),
    .B(_106_),
    .Y(_005_[0])
  );
  NAND _140_ (
    .A(_086_),
    .B(umbrales_I[1]),
    .Y(_108_)
  );
  NOR _141_ (
    .A(_108_),
    .B(_106_),
    .Y(_005_[1])
  );
  NAND _142_ (
    .A(_086_),
    .B(umbrales_I[2]),
    .Y(_006_)
  );
  NOR _143_ (
    .A(_006_),
    .B(_106_),
    .Y(_005_[2])
  );
  NAND _144_ (
    .A(_086_),
    .B(umbrales_I[3]),
    .Y(_007_)
  );
  NOR _145_ (
    .A(_007_),
    .B(_106_),
    .Y(_005_[3])
  );
  NAND _146_ (
    .A(_086_),
    .B(umbrales_I[4]),
    .Y(_008_)
  );
  NOR _147_ (
    .A(_008_),
    .B(_106_),
    .Y(_005_[4])
  );
  NAND _148_ (
    .A(_086_),
    .B(umbrales_I[5]),
    .Y(_009_)
  );
  NOR _149_ (
    .A(_009_),
    .B(_106_),
    .Y(_005_[5])
  );
  NAND _150_ (
    .A(_086_),
    .B(umbrales_I[6]),
    .Y(_010_)
  );
  NOR _151_ (
    .A(_010_),
    .B(_106_),
    .Y(_005_[6])
  );
  NAND _152_ (
    .A(_086_),
    .B(umbrales_I[7]),
    .Y(_011_)
  );
  NOR _153_ (
    .A(_011_),
    .B(_106_),
    .Y(_005_[7])
  );
  NAND _154_ (
    .A(_086_),
    .B(umbrales_I[8]),
    .Y(_012_)
  );
  NOR _155_ (
    .A(_012_),
    .B(_106_),
    .Y(_005_[8])
  );
  NAND _156_ (
    .A(_086_),
    .B(umbrales_I[9]),
    .Y(_013_)
  );
  NOR _157_ (
    .A(_013_),
    .B(_106_),
    .Y(_005_[9])
  );
  NAND _158_ (
    .A(_086_),
    .B(umbrales_I[10]),
    .Y(_014_)
  );
  NOR _159_ (
    .A(_014_),
    .B(_106_),
    .Y(_005_[10])
  );
  NAND _160_ (
    .A(_086_),
    .B(umbrales_I[11]),
    .Y(_015_)
  );
  NOR _161_ (
    .A(_015_),
    .B(_106_),
    .Y(_005_[11])
  );
  NAND _162_ (
    .A(_086_),
    .B(umbrales_I[12]),
    .Y(_016_)
  );
  NOR _163_ (
    .A(_016_),
    .B(_106_),
    .Y(_005_[12])
  );
  NAND _164_ (
    .A(_086_),
    .B(umbrales_I[13]),
    .Y(_017_)
  );
  NOR _165_ (
    .A(_017_),
    .B(_106_),
    .Y(_005_[13])
  );
  NOT _166_ (
    .A(_087_),
    .Y(_018_)
  );
  NAND _167_ (
    .A(_098_),
    .B(_018_),
    .Y(_019_)
  );
  NOT _168_ (
    .A(nxt_state[0]),
    .Y(_020_)
  );
  NOT _169_ (
    .A(FIFO_empty[0]),
    .Y(_021_)
  );
  NOT _170_ (
    .A(FIFO_empty[1]),
    .Y(_022_)
  );
  NAND _171_ (
    .A(_022_),
    .B(_021_),
    .Y(_023_)
  );
  NOT _172_ (
    .A(FIFO_empty[4]),
    .Y(_024_)
  );
  NOR _173_ (
    .A(FIFO_empty[3]),
    .B(FIFO_empty[2]),
    .Y(_025_)
  );
  NAND _174_ (
    .A(_025_),
    .B(_024_),
    .Y(_026_)
  );
  NOR _175_ (
    .A(_026_),
    .B(_023_),
    .Y(_027_)
  );
  NOR _176_ (
    .A(_095_),
    .B(state[4]),
    .Y(_028_)
  );
  NOT _177_ (
    .A(state[3]),
    .Y(_029_)
  );
  NOR _178_ (
    .A(state[2]),
    .B(_029_),
    .Y(_030_)
  );
  NAND _179_ (
    .A(_030_),
    .B(_028_),
    .Y(_031_)
  );
  NAND _180_ (
    .A(_031_),
    .B(_027_),
    .Y(_032_)
  );
  NOR _181_ (
    .A(FIFO_error[4]),
    .B(FIFO_error[2]),
    .Y(_033_)
  );
  NOT _182_ (
    .A(FIFO_error[0]),
    .Y(_034_)
  );
  NOT _183_ (
    .A(FIFO_error[1]),
    .Y(_035_)
  );
  NAND _184_ (
    .A(_035_),
    .B(_034_),
    .Y(_036_)
  );
  NOR _185_ (
    .A(_036_),
    .B(FIFO_error[3]),
    .Y(_037_)
  );
  NAND _186_ (
    .A(_037_),
    .B(_033_),
    .Y(_038_)
  );
  NOR _187_ (
    .A(state[0]),
    .B(state[1]),
    .Y(_039_)
  );
  NAND _188_ (
    .A(_039_),
    .B(_101_),
    .Y(_040_)
  );
  NAND _189_ (
    .A(state[2]),
    .B(_029_),
    .Y(_041_)
  );
  NOR _190_ (
    .A(_041_),
    .B(_040_),
    .Y(_042_)
  );
  NOR _191_ (
    .A(_027_),
    .B(_042_),
    .Y(_043_)
  );
  NOR _192_ (
    .A(_043_),
    .B(_038_),
    .Y(_044_)
  );
  NAND _193_ (
    .A(_044_),
    .B(_032_),
    .Y(_045_)
  );
  NOR _194_ (
    .A(_045_),
    .B(_020_),
    .Y(_046_)
  );
  NOR _195_ (
    .A(_042_),
    .B(_104_),
    .Y(_047_)
  );
  NAND _196_ (
    .A(_047_),
    .B(_031_),
    .Y(_048_)
  );
  NOR _197_ (
    .A(_102_),
    .B(_094_),
    .Y(_049_)
  );
  NAND _198_ (
    .A(_049_),
    .B(_093_),
    .Y(_050_)
  );
  NAND _199_ (
    .A(_050_),
    .B(_099_),
    .Y(_051_)
  );
  NOR _200_ (
    .A(_051_),
    .B(_048_),
    .Y(_052_)
  );
  NOR _201_ (
    .A(_052_),
    .B(_046_),
    .Y(_053_)
  );
  NAND _202_ (
    .A(_053_),
    .B(_019_),
    .Y(_003_[0])
  );
  NAND _203_ (
    .A(_098_),
    .B(reset),
    .Y(_054_)
  );
  NAND _204_ (
    .A(_054_),
    .B(_045_),
    .Y(_055_)
  );
  NAND _205_ (
    .A(_055_),
    .B(nxt_state[1]),
    .Y(_056_)
  );
  NAND _206_ (
    .A(_056_),
    .B(_050_),
    .Y(_003_[1])
  );
  NOT _207_ (
    .A(_038_),
    .Y(_057_)
  );
  NAND _208_ (
    .A(_057_),
    .B(_104_),
    .Y(_058_)
  );
  NAND _209_ (
    .A(_055_),
    .B(nxt_state[2]),
    .Y(_059_)
  );
  NAND _210_ (
    .A(_059_),
    .B(_058_),
    .Y(_003_[2])
  );
  NOT _211_ (
    .A(_030_),
    .Y(_060_)
  );
  NOR _212_ (
    .A(_060_),
    .B(_040_),
    .Y(_061_)
  );
  NAND _213_ (
    .A(_027_),
    .B(_091_),
    .Y(_062_)
  );
  NAND _214_ (
    .A(_062_),
    .B(_061_),
    .Y(_063_)
  );
  NOR _215_ (
    .A(FIFO_empty[4]),
    .B(FIFO_empty[2]),
    .Y(_064_)
  );
  NOR _216_ (
    .A(_023_),
    .B(FIFO_empty[3]),
    .Y(_065_)
  );
  NAND _217_ (
    .A(_065_),
    .B(_064_),
    .Y(_066_)
  );
  NAND _218_ (
    .A(_066_),
    .B(_091_),
    .Y(_067_)
  );
  NAND _219_ (
    .A(_067_),
    .B(_042_),
    .Y(_068_)
  );
  NAND _220_ (
    .A(_068_),
    .B(_063_),
    .Y(_069_)
  );
  NAND _221_ (
    .A(_069_),
    .B(_057_),
    .Y(_070_)
  );
  NOT _222_ (
    .A(_054_),
    .Y(_071_)
  );
  NAND _223_ (
    .A(_071_),
    .B(nxt_state[3]),
    .Y(_072_)
  );
  NAND _224_ (
    .A(_072_),
    .B(_070_),
    .Y(_003_[3])
  );
  NAND _225_ (
    .A(_071_),
    .B(nxt_state[4]),
    .Y(_073_)
  );
  NOR _226_ (
    .A(_043_),
    .B(_092_),
    .Y(_074_)
  );
  NAND _227_ (
    .A(_074_),
    .B(_032_),
    .Y(_075_)
  );
  NAND _228_ (
    .A(_075_),
    .B(_057_),
    .Y(_076_)
  );
  NAND _229_ (
    .A(_076_),
    .B(_048_),
    .Y(_077_)
  );
  NAND _230_ (
    .A(_077_),
    .B(_073_),
    .Y(_003_[4])
  );
  NOT _231_ (
    .A(_042_),
    .Y(_078_)
  );
  NOR _232_ (
    .A(_098_),
    .B(_084_),
    .Y(_079_)
  );
  NOT _233_ (
    .A(idle_out),
    .Y(_080_)
  );
  NOR _234_ (
    .A(_061_),
    .B(_080_),
    .Y(_081_)
  );
  NAND _235_ (
    .A(_081_),
    .B(_079_),
    .Y(_082_)
  );
  NAND _236_ (
    .A(_082_),
    .B(_078_),
    .Y(_002_)
  );
  NAND _237_ (
    .A(_079_),
    .B(active_out),
    .Y(_083_)
  );
  NAND _238_ (
    .A(_083_),
    .B(_031_),
    .Y(_000_)
  );
  DFF _239_ (
    .C(clk),
    .D(_005_[0]),
    .Q(umbrales_I[0])
  );
  DFF _240_ (
    .C(clk),
    .D(_005_[1]),
    .Q(umbrales_I[1])
  );
  DFF _241_ (
    .C(clk),
    .D(_005_[2]),
    .Q(umbrales_I[2])
  );
  DFF _242_ (
    .C(clk),
    .D(_005_[3]),
    .Q(umbrales_I[3])
  );
  DFF _243_ (
    .C(clk),
    .D(_005_[4]),
    .Q(umbrales_I[4])
  );
  DFF _244_ (
    .C(clk),
    .D(_005_[5]),
    .Q(umbrales_I[5])
  );
  DFF _245_ (
    .C(clk),
    .D(_005_[6]),
    .Q(umbrales_I[6])
  );
  DFF _246_ (
    .C(clk),
    .D(_005_[7]),
    .Q(umbrales_I[7])
  );
  DFF _247_ (
    .C(clk),
    .D(_005_[8]),
    .Q(umbrales_I[8])
  );
  DFF _248_ (
    .C(clk),
    .D(_005_[9]),
    .Q(umbrales_I[9])
  );
  DFF _249_ (
    .C(clk),
    .D(_005_[10]),
    .Q(umbrales_I[10])
  );
  DFF _250_ (
    .C(clk),
    .D(_005_[11]),
    .Q(umbrales_I[11])
  );
  DFF _251_ (
    .C(clk),
    .D(_005_[12]),
    .Q(umbrales_I[12])
  );
  DFF _252_ (
    .C(clk),
    .D(_005_[13]),
    .Q(umbrales_I[13])
  );
  DFF _253_ (
    .C(clk),
    .D(_000_),
    .Q(active_out)
  );
  DFF _254_ (
    .C(clk),
    .D(_002_),
    .Q(idle_out)
  );
  DFF _255_ (
    .C(clk),
    .D(_001_),
    .Q(error_out)
  );
  DFF _256_ (
    .C(clk),
    .D(_004_[0]),
    .Q(state[0])
  );
  DFF _257_ (
    .C(clk),
    .D(_004_[1]),
    .Q(state[1])
  );
  DFF _258_ (
    .C(clk),
    .D(_004_[2]),
    .Q(state[2])
  );
  DFF _259_ (
    .C(clk),
    .D(_004_[3]),
    .Q(state[3])
  );
  DFF _260_ (
    .C(clk),
    .D(_004_[4]),
    .Q(state[4])
  );
  DFF _261_ (
    .C(clk),
    .D(_003_[0]),
    .Q(nxt_state[0])
  );
  DFF _262_ (
    .C(clk),
    .D(_003_[1]),
    .Q(nxt_state[1])
  );
  DFF _263_ (
    .C(clk),
    .D(_003_[2]),
    .Q(nxt_state[2])
  );
  DFF _264_ (
    .C(clk),
    .D(_003_[3]),
    .Q(nxt_state[3])
  );
  DFF _265_ (
    .C(clk),
    .D(_003_[4]),
    .Q(nxt_state[4])
  );
endmodule
